### ISSUE TITLE
flaky sensorlog test

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1005]
this test has been flaky for a few days ... 
https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fx%2Fsensorlog%2Finternal%2Fsbutil&job=vanadium-go-race&n=17193&os=linux&part=6&suite=v.io%2Fx%2Fsensorlog%2Finternal%2Fsbutil&test=TestCreateOrOpenDB+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by ivanpi-mtv** [comment]
Disabled for now - v.io/c/18472
@hpucha is investigating.

**Comment by ivanpi-mtv** [comment]
Underlying cause fixed in v.io/c/18853
Test reenabled in v.io/c/18874
