### ISSUE TITLE
flaky 3rd party ssh test on linux

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1006]
this is had been flaky for a few days ...
golang::org/x/crypto/ssh::TestClientAuthPublicKey [GoTest - linux,amd64]
https://dashboard.staging.v.io/?arch=amd64&class=golang.org%2Fx%2Fcrypto%2Fssh&job=third_party-go-test&n=17193&os=linux&part=0&suite=golang.org%2Fx%2Fcrypto%2Fssh&test=TestClientAuthPublicKey+%5BGoTest+-+linux%2Camd64%5D&type=presubmit

If we're not concerned about the test, I can easily add another test exclusion.

**Comment by asimshankar** [comment]
Obsolete
