### ISSUE TITLE
vanadium-mojo-syncbase-test flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1010]
Nick, have you seen this?
https://dashboard.staging.v.io/?arch=amd64&class=vanadium-mojo-syncbase-test&job=vanadium-mojo-syncbase-test&n=17241&os=linux&part=0&suite=vanadium-mojo-syncbase-test&test=Make+test&type=presubmit

**Comment by nlacasse** [comment]
I saw that yesterday with mojo profile version @3.  This is happening with version @2, which is the "good" one.

I think it's just a flake.  Not sure what to do about it.

**Comment by asadovsky** [comment]
Any idea why the test is flaky? Is there some sort of non-determinism, e.g. a timing-dependent component or something along these lines?

**Comment by nlacasse** [comment]
It looks like this test started failing on main jenkins as well, so maybe it's not a flake.  I'll investigate.

**Comment by nlacasse** [comment]
A new version of the mojo dart package was released on Dec 9, which is incompatible with the mojo artifacts installed as part of our current mojo profile.

The following CL fixes the mojo dart package at the known working version.

https://vanadium-review.googlesource.com/#/c/18458/
