### ISSUE TITLE
Reading ProxyStatus is racy in server.

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#1011]
Currently, we trigger a Status.Valid change if changes to a server's connection to a proxy happen.
When a connection to a proxy changes, so does flow.Manager.ListeningEndpoints, but this is noticed in another thread by the server. We need the ProxyStatus and ListeningEndpoints change to either both happen or neither happen.

@mattr-google

**Comment by caprita** [comment]
Subscribing.

**Comment by suharshs** [comment]
https://vanadium-review.googlesource.com/#/q/topic:suharshs-manstatus

**Comment by suharshs** [comment]
This has been submitted above.
