### ISSUE TITLE
TestV23CRAppResolved is flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1013]
Example: https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fv23%2Fsyncbase%2Ffeaturetests&job=vanadium-integration-test&n=17308&os=darwin&part=0&suite=v.io%2Fv23%2Fsyncbase%2Ffeaturetests&test=TestV23CRAppResolved+%5BV23Test+-+darwin%2Camd64%5D&type=presubmit

**Comment by jatinlodhia** [comment]
Fix in CL https://vanadium-review.googlesource.com/#/c/18888/
