### ISSUE TITLE
TestAppDestroyAndRecreate flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1021]
Ivan, looks like this test is still flaky - could you take a look?
https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fv23%2Fsyncbase&job=vanadium-go-test&n=17713&os=linux&part=0&suite=v.io%2Fv23%2Fsyncbase&test=TestAppDestroyAndRecreate+%5BGoTest+-+linux%2Camd64%5D&type=presubmit

**Comment by ivanpi-mtv** [comment]
Looks like same underlying issue as #1005

**Comment by ivanpi-mtv** [comment]
Fixed by v.io/c/18853
