### ISSUE TITLE
Optimize filterAndOrderServers

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#1022]
Right now we call filterAndOrderServers on every RPC call attempt, even if we end up using an already established connection.

Even though we cache some network state info this function is slow and does many allocations.  We should either make it fast or avoid calling it altogether most of the time.

**Comment by bjornick** [comment]
don't we need to filter and order the servers before we know which connections in the cache are valid?

**Comment by suharshs** [comment]
I am taking a look here. https://vanadium-review.googlesource.com/#/q/topic:suharshs-fservers
