### ISSUE TITLE
Hello World tutorial does no work on Mac OS

### ISSUE THREAD

**Issue by pcasaretto** [vanadium/issues#1024]
https://v.io/scenario-a-setup.sh

Line 96 in this script does fails with:

```
wait: -n: invalid option
wait: usage: wait [n]
```

It seems that apple provided bash `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)` does not like that flag.
Installing bash via homebrew `GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin14.5.0)` fixes the problem.

**Comment by asimshankar** [comment]
Duplicate of #1057 , which has been fixed now.
