### ISSUE TITLE
Syncbase TestV23CRRuleConfig flaky

### ISSUE THREAD

**Issue by hpucha** [vanadium/issues#1027]
Issue on Linux: https://veyron.corp.google.com/jenkins/job/vanadium-integration-test/OS=linux/1454/testReport/junit/v/io_v23_syncbase_featuretests/TestV23CRRuleConfig__V23Test___linux_amd64_/

Issue on Darwin: Need to see how the conflict call count can be 3. If this is valid, we should bump up the expected count.

In a different test, same issue with max and expected call count

https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fv23%2Fsyncbase%2Ffeaturetests&job=vanadium-integration-test&n=17909&os=darwin&part=0&suite=v.io%2Fv23%2Fsyncbase%2Ffeaturetests&test=TestV23CRAppResolved+%5BV23Test+-+darwin%2Camd64%5D&type=presubmit

Other runs with similar error
https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/548/ARCH=amd64,OS=linux,TEST=vanadium-integration-test/console

https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/544/ARCH=amd64,OS=darwin,TEST=vanadium-integration-test/console
# 

 I1221 13:44:19.693008   78784 util.go:52] Started root mount table: /@6@wsh@127.0.0.1:53744@@5a9e18395035f194f50121066e5a836c@m@root:child@@
2015/12/21 13:44:19 [Started root mount table: /@6@wsh@127.0.0.1:53744@@5a9e18395035f194f50121066e5a836c@m@root:child@@]
I1221 13:44:19.830918   78784 util.go:87] Started syncbase: /@6@wsh@127.0.0.1:53754@@7a782d0ffd89193f8106175e020f602d@s@root:s0@@
2015/12/21 13:44:19 [Started syncbase: /@6@wsh@127.0.0.1:53754@@7a782d0ffd89193f8106175e020f602d@s@root:s0@@]
I1221 13:44:19.952503   78784 util.go:87] Started syncbase: /@6@wsh@127.0.0.1:53759@@9a80643fb75e49476d345709a562d024@s@root:s1@@
2015/12/21 13:44:19 [Started syncbase: /@6@wsh@127.0.0.1:53759@@9a80643fb75e49476d345709a562d024@s@root:s1@@]
I1221 13:44:22.339408   78784 funcs.go:22] Starting a new conflict resolution connection. Reconnection count: 1
I1221 13:44:22.339413   78784 funcs.go:22] Starting a new conflict resolution connection. Reconnection count: 1
E1221 13:44:23.540943   78784 funcs.go:94] Conflict resolution connection ended with error: featuretests.test:&lt;rpc.Client&gt;&#34;s0/a/d&#34;.StartConflictResolver: Canceled: [remote=@6@wsh@127.0.0.1:53754@@7a782d0ffd89193f8106175e020f602d@s@root:s0@@: featuretests.test:&lt;rpc.Client&gt;&#34;s0/a/d&#34;.StartConflictResolver: Bad protocol or type: failed to decode response: EOF]
I1221 13:44:23.541919   78784 funcs.go:22] Shutting down conflict resolution connection.
E1221 13:44:23.541083   78784 funcs.go:94] Conflict resolution connection ended with error: featuretests.test:&lt;rpc.Client&gt;&#34;s1/a/d&#34;.StartConflictResolver: Canceled: [remote=@6@wsh@127.0.0.1:53759@@9a80643fb75e49476d345709a562d024@s@root:s1@@: featuretests.test:&lt;rpc.Client&gt;&#34;s1/a/d&#34;.StartConflictResolver: Bad protocol or type: failed to decode response: EOF]
I1221 13:44:23.541935   78784 funcs.go:22] Shutting down conflict resolution connection.
/Users/veyron/jenkins/workspace/vanadium-integration-test/OS/darwin/root/release/go/src/v.io/x/ref/services/syncbase/testutil/util.go:33 (0x41d2c58)
    Fatal: debug.PrintStack()
/Users/veyron/jenkins/workspace/vanadium-integration-test/OS/darwin/root/release/go/src/v.io/v23/syncbase/featuretests/test_util_test.go:334 (0x40a5510)
    ok: tu.Fatal(t, err)
/Users/veyron/jenkins/workspace/vanadium-integration-test/OS/darwin/root/release/go/src/v.io/v23/syncbase/featuretests/cr_v23_test.go:329 (0x40afacf)
    runWithAppBasedResolver.func2: ok(t, runConflictResolver(client1Ctx, &#34;s1&#34;, schemaPrefix, &#34;endKey&#34;, maxCallCount))
/Users/veyron/jenkins/workspace/vanadium-integration-test/OS/darwin/root/profiles/go/amd64_darwin/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/runtime/asm_amd64.s:1696 (0x4061a11)
    goexit: BYTE    $0x90   // NOP
    util.go:34: Unexpected OnConflict call count. Max: 2, Actual: 3
    v23test.go:272: /Users/veyron/tmp/vit/281005361/bin-228213558/syncbased (PID 80473) did not die
    v23test.go:272: Sent SIGKILL to all remaining child processes
# 

See output at 

https://veyron.corp.google.com/jenkins/job/vanadium-integration-test/OS=darwin/1454/testReport/junit/v/io_v23_syncbase_featuretests/TestV23CRRuleConfig__V23Test___darwin_amd64_/

**Comment by jatinlodhia** [comment]
Fix in CL https://vanadium-review.googlesource.com/#/c/18888/
