### ISSUE TITLE
While running integration test:  "Failed to create e-mail address for @google.com"

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1035]
https://veyron.corp.google.com/jenkins/job/vanadium-integration-test/1473/console

```
Failed to create e-mail address for @google.com
An attempt to send an e-mail to empty list of recipients, ignored.
Finished: FAILURE
```

**Comment by bprosnitz** [comment]
@jinjingforever  @nlacasse

**Comment by bprosnitz** [comment]
This shows up as a failure in v.io/v23/syncbase/featuretests.TestV23CRAppResolved

**Comment by bprosnitz** [comment]
@bjornick

**Comment by jinjingforever** [comment]
There seems to be a bug in vanadium_scm plugin. I will fix that. Thanks for catching it!

**Comment by jinjingforever** [comment]
Should be fixed by v.io/c/18795
