### ISSUE TITLE
Submodule mapping error in mojo profile installation

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1046]
No submodule mapping found in .gitmodules for path 'third_party/dart-pkg/archive'
https://veyron.corp.google.com/jenkins/job/vanadium-mojo-syncbase-test/231/console

Did something change in the configuration recently?

@tatatodd @nlacasse @afandria

**Comment by nlacasse** [comment]
https://github.com/domokit/mojo/issues/608

**Comment by nlacasse** [comment]
Fixed by https://github.com/vanadium/go.devtools/commit/beb739f96e250706f4e2e21161b84fccc7d777cb
