### ISSUE TITLE
Tutorial images still use slashes in blessings

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1058]
Tutorial SVG currently on v.io/tutorials still use slashes in blessings.

For example: https://v.io/images/tut/security04-alice-carol-succeed-bob-fails.svg

**Comment by afandria** [comment]
We definitely need to update these images.

@asimshankar Do you know who created the .svg files for the security tutorials? We will need to update most of them, since they show "/" instead of ":" in the blessing strings.

**Comment by asimshankar** [comment]
@lnizix created them, will reach out to her for an update

**Comment by monopole** [comment]
dupe of https://github.com/vanadium/issues/issues/901
