### ISSUE TITLE
vbinary is using too many resources

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1060]
I'm concerned about vbinary's resource usage. It takes a long time to compile, which is fine, but when I run it (for releases), it takes a LOT of CPU and memory. Using `top`, it seems that CPU is usually 200% and peaks at around 400%, and the memory usage grows up to about 4.6 gb of memory.

The reason I was concerned is that vbinary froze my workstation the first time I tried to run it. After a hard restart, it worked fine. I think the freeze occurred because I ran out of memory on my workstation (Chrome/Atom/Sublime).

(I don't know who owns `vbinary`, so I have to figure that out first.)

**Comment by suharshs** [comment]
I wrote vbinary. What command did you run?

It downloads a bunch of binaries in parallel so I can see it being expensive :)

**Comment by afandria** [comment]
Great, thanks.

After installing `jiri go install v.io/x/devtools/vbinary`, I ran the very expensive command:

```
${JIRI_ROOT}/release/go/bin/vbinary --release download --output-dir=/tmp/releasebin
```

**Comment by jeffallen** [comment]
The Go tutorial has an exercise on how to rate limit a spider. Perhaps @suharshs should go give it a try. :)

Seriously, the typical solution to "too much work in parallel" is that each worker should take a ticket out of a buffered channel and put the ticket back in via a defer. The number of tickets in the channel at startup determines the parallelism.

I would be willing submit a CL for this, if you'd like.

**Comment by suharshs** [comment]
Oops, just saw your comment now :)

Just wrote a CL here: https://vanadium-review.googlesource.com/#/c/19041/

My solution is actually almost exactly what you said Jeff.
