### ISSUE TITLE
vanadium-baku-test failing

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1067]
It's not urgent since release.projects.baku seems relatively new, but it would be good to fix if you have time.

**Comment by jxson** [comment]
Hmm, that test is very simple. It calls `make clean` and then `make test`. Looking at the output it seems that recent updates to the jiri tool might be the issue. Lots of errors in the `jiri update` phase ending with:

```
lstat .manifest/git-hooks: no such file or directory
```

Maybe @nlacasse has an idea?

**Comment by nlacasse** [comment]
I submitted a change to jiri's git-hook logic 2 days ago, which is likely the culprit.  https://vanadium-review.googlesource.com/#/c/18880/

I'm investigating.

**Comment by nlacasse** [comment]
The failures were all on jenkins-node85.  It looks like that node had a very old workspace, and jiri wasn't able to update to the current version.

I deleted the baku workspace on that node, and it seems to have been recreated successfully, and the test is green again.

I'm going to run a task to clean up all old workspaces now, which will hopefully let us avoid this issue in the future.

**Comment by jxson** [comment]
@nlacasse thanks!!
