### ISSUE TITLE
proxy docs have bad link

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1068]
First, the documentation on proxying on v.io is... underwhelming at the moment. :)

But what's there has a bad link. https://v.io/tools/services.html links to https://godoc.v.io/pkg/v.io/x/ref/services/proxy/. It should be https://godoc.v.io/pkg/v.io/x/ref/services/xproxy/.

I'm also not really seeing the point of running godoc.v.io, since all this source is in github and godoc.org can index it.

**Comment by asimshankar** [comment]
Thanks for pointing this out Jeff.

a) Yeah, documentation is a bit sparse, apologies for that. Added a few lines that are hopefully useful. Will have to get to more detailed documentation at some point. Let me know what you think about what it currently has.

b) Fixed the link (should be deployed in the next half hour)

c) Regarding godoc.v.io, yeah, that is a relic from when the repositories were not open source in our initial days and so godoc.org couldn't index it (plus, it has styling more consistent with the website). Will look into replacing with godoc.org instead

**Comment by jeffallen** [comment]
Ah, I just discovered the new stuff you added. Nice.

I'll also explore on my own. If I figure it out, I'll try to contribute a tutorial on it. No promises, but it looks like something fun to play with.
