### ISSUE TITLE
Update proxy design document

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#1070]
The document at https://docs.google.com/document/d/1rfocoE98Fo9fTdxKtU_uaBmyhZNlvhDPvjzR5MelpDE/edit?usp=sharing
does not fully reflect the current state.

Please update that @suharshs  :)

FYI @mattr-google

**Comment by suharshs** [comment]
Updated doc here: https://docs.google.com/document/d/1ONrnxGhOrA8pd0pK0aN5Ued2Q1Eju4zn7vlLt9nzIRA/edit#
