### ISSUE TITLE
libssl-dev is missing from jiri profile

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1075]
When doing a new install on Debian, "jiri v23-profile install base" completed correctly. Then when I tried to build mounttabled, I got this:

jra@ns:~$ jiri go install v.io/x/ref/services/mounttable/mounttabled
# pkg-config --cflags libcrypto

Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
pkg-config: exit status 1

Thanks to an answer on StackOverflow I solved it with this: sudo apt-get install libssl-dev

The machine in question is Debian 8:
jra@ns:~$ uname -a
Linux ns 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux
jra@ns:~$ cat /etc/issue
Debian GNU/Linux 8 \n \l

It seems to me like jiri was supposed to take care of this for me?

**Comment by nlacasse** [comment]
https://vanadium-review.googlesource.com/19106

**Comment by nlacasse** [comment]
Yes.  It looks like there is a typo in the code that installs libssl-dev.

Thanks for reporting!
