### ISSUE TITLE
v.io/v23/naming/doc.go says that version 5 is current

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1080]
v.io/v23/naming/doc.go says that version 5 is current but the current behavior seems to be that version 6 is current.

It would be nice to have the v6 format documented here:
    https://github.com/vanadium/docs/blob/master/concepts/naming.md
(in section Endpoints, I think)

instead of in v.io/x/ref/runtime/internal/naming/endpoint.go:parseV6

**Comment by caprita** [comment]
@suharshs : I think you incremented the version from 5 to 6, can you please update v.io/v23/naming/model.go and see if there are other places as well?

@jeffallen : Thanks for reporting. Regarding the places where we document the endpoint format, we've been resisting putting that in the public v23 API. The idea was to make the endpoint format an implementation detail (akin to the RPC protocol for example) and avoid having people manipulate an endpoint string by hand. Though clearly some of it leaks through. Could you please briefly describe your need to operate on endpoints?

**Comment by suharshs** [comment]
Thanks for pointing this out: https://vanadium-review.googlesource.com/#/c/19117/

**Comment by jeffallen** [comment]
@caprita I get it, makes sense. I was trying to understand the endpoints because I was still booting up to understanding name resolution. (It wasn't working yet for me due to unrelated credential problems, so I was digging and digging looking for what was broken.)
