### ISSUE TITLE
"principal get publickey" is incompatible with "principal recognize"

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1081]
$ principal get publickey
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2xhOU1JaMGDjPZCy0K_XsUAIcsRGww4jbnJ07d-nc-isXXkq4flcFCMESxcw_obYnZ5MrFeduxOygeTXBSjUDw==

$ principal recognize MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2xhOU1JaMGDjPZCy0K_XsUAIcsRGww4jbnJ07d-nc-isXXkq4flcFCMESxcw_obYnZ5MrFeduxOygeTXBSjUDw== mounttabled
ERROR: invalid base64 encoding of public key: illegal base64 data at input byte 8

Everything up to the _ is valid base64. It seems like there is other junk encoded in there?

This might be working right, but the UI is all jacked up. :)

**Comment by jeffallen** [comment]
Use the source, luke! Turns out this is just a problem with the help text. Putting the blessing pattern first fixes it:

principal recognize mounttabled "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2xhOU1JaMGDjPZCy0K_XsUAIcsRGww4jbnJ07d-nc-isXXkq4flcFCMESxcw_obYnZ5MrFeduxOygeTXBSjUDw=="

A CL that fixes this is: https://vanadium-review.googlesource.com/#/c/19091/

**Comment by asimshankar** [comment]
Thanks for the fix Jeff! Submitted it.
