### ISSUE TITLE
Syncbase: Values are inconsistently exposed as []byte or vdlValue or interface{} throughout the client libraries

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1083]
Currently the value of a row in exposed in three different ways throughout the client API: `[]byte` or `VdlValue` or a method that force decoding to a type or interface{}

There are a few parts of the API where value of a row is surfaced. `row.get`, `scan`, `query`, `watch` and `conflict resolver` and each is different in how it exposes value. (Might be missing some)
- `row.get` and `scan` force decoding to a type
- `conflict resolver` and `watch` expose it as `[]byte`
- `query` exposes it as `VdlValue`

Unless there is a very good reason for this, we should expose value of a row consistently as a single type. Maybe we can have a `RowValue` interface that allows getting it as `[]bytes` or `VdlValue` and has methods for decoding to a type or even decoding to a JSON string.

I am thinking about this for the Dart API and will come up with a proposal that hopefully we can implement in every client library.

(Althought I used Go as reference here, same is true about the Java API).

@kenashcraft @asadovsky @m3bm3b

**Comment by kenashcraft** [comment]
Agreed that this is an important issue, but don't jump into it right away.  This is very closely related to the VOM type discussions that are going on.

**Comment by m3bm3b** [comment]
One of the reasons for the confusion in types used is that if we
presented the fully decoded value, VOM did not make it easy for
us to avoid unnecessary marhsalling and unmarshalling.
(The data might be retrieved as an array of bytes from the disc,
unmarshalled a first time to give to the RPC system, then the RPC
system would remarshal it into an array of bytes for transmission
over the wire to the client side,  which would unmarshal it a
second time for presentation to the application.)
To give the client an array of bytes is uglier, but
potentially significantly faster:  the data could in principle
be unmarshalled  just once, by the client assuming the implementation
did the right thing.

The hope is that this will improve in the next few weeks with the
introduction of vdl.RawBytes.  This type allows us to transmit
data via RPC that has already been marshalled, and unmarshal it
only on demand.    Thus, by using vdl.RawBytes for syncbase's
internal RPC interfaces, we could avoid the redundant marshal/unmarshal
steps.

It is not clear to me whether the syncbase client library should
expose vdl.RawBytes to clients.  In principle, it will sometimes
save time there too (imagine the client doesn't need to decode
every value from a Scan, or that it is actually a security proxy
that merely passes the values through to its clients) Btu I do
not know whether such applications will be important enough to
influence the choice of type at the client interface.

**Comment by asadovsky** [comment]
WRT @m3bm3b's last paragraph: one can imagine a special per-language type (perhaps named `RawBytes`) that, when presented to the `Get(key string, value interface{})` API (and other such APIs), results in the bytes not getting decoded. This would provide an escape hatch for performance-conscious developers who don't want the decoding to happen, while avoiding adding an extra method and preserving API simplicity for what I presume to be the common case.

**Comment by m3bm3b** [comment]
> a special per-language type

Yes, though you might need a different scheme if you wished to support it
in a language lacking well-defined types, or one lacking reflection.

**Comment by aghassemi** [comment]
So what I had in mind when I was thinking about this for the Dart API is something like below. I quickly checked with @tatatodd  and he liked the idea so maybe it can serve as a starting point for the conversation.

Idea is to express the value of a row as a new struct called `RowValue` everywhere; so we would have 
`Get(key String) RowValue` for Row API and `Value RowValue` as a field in `WatchChange` and so on...

`RowValue` would hold the new unmarshaled `vdl.RawValue` it gets from RPC calls and provides the following convenience methods:

```
// Decodes to a specific type. The common use-case.
To(value interface{})

// Decodes to a vdl.Value. 
// Equivalent to "var v *vdl.Value; rowValue.To(v);"
ToVdlValue() vdl.Value

// For when we support VOM -> JSON. 
// Equivalent to "String json; vom.decodeJson(rawValue,json);"
ToJson() String

// Returns unmarshalled bytes from the underlying RawValue. 
// Maybe it should return vom.RawValue instead of []byte?
ToVomBytes() []byte
```

Note that `RowValue` is mostly there to 
1- Be the canonical type for Syncbase values everywhere in the client facing API.
2- Provide helpers for developers to consume the value.  

It does not require any fundamental changes to the system. Also since we just hold the `vdl.RawValue`, decoding is on-demand with calls to one of `ToX()` methods and raw bytes are available to developers without performance penalty.

**Comment by kenashcraft** [comment]
Ali's change seems reasonable to me, but I don't see the need to rush to make this change.  Let's finish the VOM type problem first and see if that informs this problem.

Also, RowValue is just a few pixels different from RawValue.  Maybe pick a name that is more visually different.

**Comment by tatatodd** [comment]
Just to be clear, the name that we're actually using is vom.RawBytes.  When you decode into vom.RawBytes, we only decode the type information, but leave the value part as raw bytes.  And when you encode vom.RawBytes, we only need to encode the type information, while the value part is just written out directly.

(Earlier in this thread it's been called vdl.RawBytes and vdl.RawValue, both of which are incorrect)

**Comment by asadovsky** [comment]
I agree with Ken - these API changes seem to be on the right track, but I'd like to put them off for a bit. There are various other API cleanups to do, and in general these kinds of cleanups should be done holistically (both across languages and across methods), so my inclination would be to get a few of us in a room sometime later this quarter to hash this stuff out.

**Comment by aghassemi** [comment]
This might be a higher priority for Dart API with supporting mojom and/or json work and since it will be used externally and ideally we can minimize breaking changes. But we can decide on that as we discuss what we should currently do to support structured data in Dart.

**Comment by aghassemi** [comment]
https://vanadium-review.googlesource.com/#/c/20263/ is fixing this.

**Comment by m3bm3b** [comment]
https://vanadium-review.googlesource.com/#/c/20263/ 

is now submitted.  So, aside from the fact that the Java world is still disabled for other reasons, this should be ok now.
