### ISSUE TITLE
Remove gosh Send{Ready,Vars} and Await{Ready,Vars}

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1084]
These functions have always bothered me, because they don't seem to belong in gosh.

The child implementation just writes special `#! {Type: "ready"}` strings to stdout, which are parsed by the parent gosh shell, which is also very weird.  After all what's preventing a user from writing `#! INVALID` to stdout themselves?  At the moment that'll cause our recvWriter to fail the json.Unmarshal call, which I believe will cause the command to fail.

The only usage of these functions is in x/ref/services/internal/servicetest/modules.go.  Everywhere else when we want to do something similar, we just write stuff directly to stdout, and use the x/ref/test/expect package to do the waiting.  In the short term we can change servicetest to do something similar; in the longer term we might try to come up with a better general-purpose "expect" package.

Note that Await{Ready,Vars} have two ways to terminate - either "ready" or "vars" have been read from the cmd, or the cmd has exited.  Originally I thought we might need to replicate the "or the cmd has exited" behavior somehow.  But then I realized that this just works naturally.  I.e. the "expect" package reads from StdoutPipe(), which will be closed when the cmd exits, causing an EOF.

I think this one is pretty clear-cut, but we can also discuss on Tuesday.  :)

**Comment by asadovsky** [comment]
I agree that the message-passing implementation may not be ideal (in particular the `#! INVALID` handling), but I would like for there to be a simple/recommended way to transmit vars from child to parent, without bringing in heavier dependencies such as `expect`. (For example, I use `AwaitReady` here: https://github.com/asadovsky/goatee/blob/master/demo/main.go#L61)

How would you feel if we dropped `AwaitReady` and modified `AwaitVars` to simply ignore "malformed" messages?

**Comment by tatatodd** [comment]
Here's a simple way to transmit vars from child to parent:

// CHILD
fmt.Println("ready")

// PARENT
var str string
if fmt.Fscanln(c.StdoutPipe(), &str); str != "ready" {
  ...
}

I like this better than SendVars / AwaitVars, because I think it's very clear what we're doing, and it doesn't require any special gosh logic.

**Comment by asadovsky** [comment]
That assumes the first line of output is "ready" - or perhaps you meant to use a for loop?

I'd probably be fine with moving {Send,Await} out of gosh.Cmd, but I think I'd at least want to provide standalone helper functions in gosh for SendVars/AwaitVars.

There are two annoyances with making AwaitVars a helper function:
1. One must call StdoutPipe() before starting the command
2. (minor) There's a resource cost to it, because StdoutPipe will hold the entire stdout in a buffer

I don't mind (2) too much since we've already accepted this cost as reasonable in gosh (trading performance for usability). I do think (1) is kind of annoying, but not a dealbreaker.

Btw, I see Send/AwaitVars as somewhat analogous to BuildGoPkg - methods that are not strictly essential or central to the purpose of the library, but convenient and somewhat helpful in demonstrating how to extend the functionality. Perhaps all of these should be converted into standalone helpers.

**Comment by tatatodd** [comment]
I was indeed assuming the first line of output is "ready".  I think that's better for the simple case; the user is in control of what output is showing up on their stdout anyways.

Good point about (1) where we must call StdoutPipe() before starting the command.  In practice I don't think it'll be that bad (see example below).

I'm still in favor of removing SendVars/AwaitVars from gosh completely.  If the user needs something more complicated than fmt.{Print,Scan}, we should move expect into "v.io/x/lib/expect", remove its dependency on "testing", and add Await (possibly with other API changes).  I'm thinking the usage would look like:

```
func TestFoo(t *testing.T) {
  sh := gosh.NewShell(gosh.Opts{Fatalf: t.Fatalf, Logf: t.Logf})
  defer sh.Cleanup()

  c := sh.Cmd("foo")
  stdout := c.StdoutPipe()
  c.Start()

  e := expect.E{In: stdout, Fatalf: t.Fatalf, Logf: t.Logf}
  e.AwaitLn("ready") // waits until "ready" shows up, skipping other lines.
  e.ExpectLn("foo") // next line read must be "foo"
}
```

The reason I like this better is because each package provides orthogonal logic; gosh is all about running commands and cleanup, while expect is all about checking expectations on a stream of text.  It's true that users that want the "AwaitVars" behavior will need to import another package, but I don't think that's so bad.

**Comment by tatatodd** [comment]
BTW - I agree in concept with the BuildGoPkg observation, but I haven't thought through the details, especially wrt BinDir handling.

**Comment by asadovsky** [comment]
Settled on keeping {Send,Await}Vars as the one simple builtin for child->parent messaging; for anything else, do it yourself a la `v.io/x/ref/test/expect`.
https://vanadium-review.googlesource.com/#/c/19156/
https://vanadium-review.googlesource.com/#/c/19192/
