### ISSUE TITLE
Embed gosh.Opts in gosh.Shell

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1087]
Our current gosh usage looks like this:

```
sh := gosh.NewShell(gosh.Opts{Fatalf: t.Fatalf, Logf: t.Logf})
defer sh.Cleanup()
sh.Opts.PropagateChildOutput = true
sh.Vars["foo"] = "bar"
```

The Opts is kind of annoying, since it's inconsistent with Cmd (where all options are at the top-level), and its easy to forget.  If we embed gosh.Opts in gosh.Shell, we can write this instead, which seems better:

```
sh := gosh.NewShell(gosh.Opts{Fatalf: t.Fatalf, Logf: t.Logf})
defer sh.Cleanup()
sh.PropagateChildOutput = true
sh.Vars["foo"] = "bar"
```

Of course for this particular example, we could always use the literal directly, which is even simpler.  But the general problem still holds.

```
sh := gosh.NewShell(gosh.Opts{Fatalf: t.Fatalf, Logf: t.Logf, PropagateChildOutput: true})
defer sh.Cleanup()
sh.Vars["foo"] = "bar"
```

**Comment by asadovsky** [comment]
Seems reasonable to me. I'll plan on making this change soon, but I'll take on #1125, #1127, and #1128 first since they're somewhat related (in terms of options defaulting behavior).

**Comment by asadovsky** [comment]
Done in https://v.io/c/20205 - gosh.Opts is gone, and all options are now fields in Shell.
