### ISSUE TITLE
panic failing to connect to agentd

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1089]
I accidentally pointed "principal dump" at a non-existing agent.sock:

jra@ns:~$ V23_AGENT_PATH=$HOME/.credentials/agent.sock principal dump

I got this panic. I was expecting a nice error message.

panic: dial unix /home/jra/.credentials/agent.sock: connect: no such file or directory

goroutine 1 [running]:
v.io/v23.internalInit(0x2, 0x2)
    /home/jra/vanadium/release/go/src/v.io/v23/model.go:483 +0x47b
v.io/v23.Init(0xc82016e960, 0x2)
    /home/jra/vanadium/release/go/src/v.io/v23/init.go:17 +0x18
v.io/x/ref/lib/v23cmd.runner.Run(0xf053e0, 0xf05d68, 0xc820172dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/jra/vanadium/release/go/src/v.io/x/ref/lib/v23cmd/v23cmd.go:29 +0x33
v.io/x/ref/lib/v23cmd.(*runner).Run(0xc8200e4aa0, 0xc820172dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:1 +0xcc
v.io/x/lib/cmdline.ParseAndRun(0xc8200cfb00, 0xc820172dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/jra/vanadium/release/go/src/v.io/x/lib/cmdline/cmdline.go:238 +0x185
v.io/x/lib/cmdline.Main(0xc8200cfb00)
    /home/jra/vanadium/release/go/src/v.io/x/lib/cmdline/cmdline.go:138 +0x254
main.main()
    /home/jra/vanadium/release/go/src/v.io/x/ref/cmd/principal/main.go:1024 +0x1311

**Comment by caprita** [comment]
I think this is related to #1079 in that at runtime initialization, the error in setting up the principal eventually becomes a panic.

**Comment by ghost** [comment]
Did you find the message itself (dial unix /home/jra/.credentials/agent.sock: connect: no such file or directory) insufficient?  Or just annoyed by the noisy stack trace?

**Comment by jeffallen** [comment]
I was raised by my momma to think that a well behaved program does not panic. Certainly not when it knows exactly what's wrong and can tell me what to do about it... :)

**Comment by ghost** [comment]
Resolved by https://vanadium-review.googlesource.com/#/c/19268/
