### ISSUE TITLE
vanadium-android-build is flaky in presubmits

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1095]
@spetrovic77 @aghassemi @sjamesr 

Here's an example:
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-android-build/19066/console

Here's the history, showing large swaths of redness:
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-android-build/

As with all other flaky tests recently, my workaround is to TBR.  kthxbye

**Comment by aghassemi** [comment]
The Java profile was messed up on `node76`, running `cleanup-profiles` to clean it up.

This can happen if an open CL that is trying to upgrade a profile fails to do so. When presubmit for that CL runs, it upgrades the profile for the whole machine.

In this case @mattr-google's https://vanadium-review.googlesource.com//#/c/19292/ was trying to upgrade the java profile and failed in its first presubmit with https://dashboard.staging.v.io/?arch=amd64&class=vanadium-android-build&job=vanadium-android-build&n=19047&os=darwin&part=0&suite=vanadium-android-build&test=Init&type=presubmit causing the Java profile to be broken on `node76`

For now, any open CL that tries to upgrade a profile but fails in presumit, needs to rerun the Jenkins "Clean up profiles" task.

@nlacasse @jinjingforever I guess we don't want to clean up profiles after every test run, but if we somehow detect a CL is changing profiles, then maybe we can clean up profiles for those runs?

**Comment by spetrovic77** [comment]
Thanks Ali, indeed, all the failures are on node 76...

**Comment by jinjingforever** [comment]
@aghassemi yes I think this can be done. I will create a CL.

**Comment by ghost** [comment]
Sorry!

**Comment by jinjingforever** [comment]
v.io/c/19330 and v.io/c/19331 added the profiles cleanup feature. I will submit them tomorrow.

**Comment by aghassemi** [comment]
wow thanks @jinjingforever ! That was quick.

**Comment by tatatodd** [comment]
FYI I just got another failure, on Veyrons-Mac-Pro-3.local

https://dashboard.staging.v.io/index.html?type=presubmit&n=19127&arch=amd64&os=darwin&job=vanadium-android-build

**Comment by spetrovic77** [comment]
James is on it!

**Comment by spetrovic77** [comment]
I've disabled the test for now, until we figure out why the profiles keep
reverting to non-default android version "4".
