### ISSUE TITLE
Jenkins Upstart failed

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1104]
Jenkins VM was restarted due to an outage but upstart did not start Jenkins.

Running `service jenkins start` also failed on `permission denied` when trying to write to `pid/jenkings.pid` file. Inspecting ACLs, looks like something changed the `pid` directory to be read-only and reverted ownership to root. I had to manually reset ACLs on the `pid` directory before `service jenkins start` started working again. I suspect this was the reason upstart script also failed.

It might be worth investigating what caused the `pid` dir to become read-only.

@jinjingforever @caprita @nlacasse

**Comment by jinjingforever** [comment]
I suspect somebody restarted Jenkins last time under the root user instead of the veyron user. I added a line to the init script to chown the pid file/dir to user veyron before starting Jenkins.

Thanks!
