### ISSUE TITLE
mojo/discovery: Go Panic Crash

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1107]
When I'm playing Croupier, I will randomly have the discovery binary crash in the background.

I collected some log files, and naively, it seems like there's an issue with mdns packing.

The log file is here since the panic is massive: [log.txt](https://github.com/vanadium/issues/files/113177/log.txt)

@aghassemi @bjornick @jhahn21

**Comment by jhahn21** [comment]
@afandria, can you please check whether https://vanadium-review.googlesource.com/#/c/19413/ fix this issue?

**Comment by afandria** [comment]
Sure, I'll try it out.

If Croupier survives a "long time" (i.e., a few hours) without crashing, then that is probably the fix.

**Comment by afandria** [comment]
I forgot to close this. I pushed out a working version of discovery this last week.
