### ISSUE TITLE
failures not being reported in presubmits

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1108]
From the looks of this [CL](https://vanadium-review.googlesource.com/#/c/19390/3/vom/binary_util.go), we don't seem to be running vanadium-copyright in presubmit tests.

**Comment by nlacasse** [comment]
Strange.  The copyright check did run, and it did fail.  Not sure why the presubmit thought it passed.

**Comment by nlacasse** [comment]
It looks like failures are not being reported in presubmits.  @jinjingforever

**Comment by afandria** [comment]
Oh shoot, yes. I see it too. That's why. `croupier-unit-go` failed earlier, and I didn't see it in my recent CLs.

**Comment by jinjingforever** [comment]
Sorry, looks like one of my recent changes broke it.. Fixing it now.

**Comment by jinjingforever** [comment]
Should be fixed by v.io/c/19416.

**Comment by afandria** [comment]
Thanks!
