### ISSUE TITLE
Syncbase: Watch should not require Resolve permission 

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1110]
The set of permissions needed to do a `Scan` v.s. `Watch` should be the same, that's not currently the case.

I  ran into  issue where my new integration test was failing when I was using `watch` but not when I was using `scan`. 

It turned out that although I had `read` permission on the table, I did not have 'resolve' which was required by `watch`. These ACL errors were also not surfaced (the rows were just omitted) which made it extra tough to figure out why my watch stream is empty, but that's an orthogonal problem of how and to what extend can we surface why some rows are omitted in Scan and Watch streams.

I understand the underlying implementation of `watch` uses `WatchGlob` and having `resolve` permission for glob is expected however in the context of the Syncbase, a developer may not know the details of other parts of Vanadium such as Glob or may not connect the dots that `database.Watch()` uses glob behind the scene.

We should ensure `Scan`, `Get` and `Watch` all behave the same when it come to ACL checks and for that I recommend assuming `Read` implies `Resolve` for Syncbase's watch.

@asadovsky @m3bm3b @hpucha @kenashcraft

**Comment by afandria** [comment]
@ivanpi-mtv and I ran into this too on Friday. We didn't realize our test setup didn't include Resolve until after trying a bunch of other (complex) security-related things to debug the problem.

**Comment by ivanpi-mtv** [comment]
Changed to Read.
