### ISSUE TITLE
mojo/discovery: Cannot build on Android

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1111]
Discussed earlier with @bjornick and @jhahn21 

There is some trickiness around building for Android. I end up with a gradle build exception:

```
cd java && ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'java'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.android.support:support-v4:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
     Required by:
         :java:unspecified > io.v:vanadium-android:1.3
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         :java:unspecified > io.v:vanadium-android:1.3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.258 secs
make[1]: *** [gradle-build] Error 1
make[1]: Leaving directory `/usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/mojo/discovery'
make: *** [local-publish] Error 2
```

Supposedly having a `MOJO_DIR` and Android build matters here, but I haven't had any success yet. This should be mentioned in the Makefile (or a README).

**Comment by afandria** [comment]
It looks like the missing jar file is NOT in out/android_Debug.

@sjamesr @spetrovic77 : Do you have any ideas? It's possible that one of the Maven dependencies have disappeared recently.

**Comment by sjamesr** [comment]
Looks like you don't have the Android support library installed. You should
use Jake Wharton's SDK manager to install it automatically. See the
android-lib/build.gradle file for an example or go to
https://github.com/JakeWharton/sdk-manager-plugin for instructions. Let me
know how you go.

**Comment by afandria** [comment]
Thanks, I'll give it a try.

**Comment by afandria** [comment]
It looks like `release/mojo/discovery/java/build.gradle` already has the sdk manager.

I tried changing `classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.0'` to `classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.+'`, but it didn't help.

I'll ask in person in the morning.

**Comment by sjamesr** [comment]
Ok, this is https://github.com/JakeWharton/sdk-manager-plugin/issues/14. As a workaround, try the following patch:

``` patch
diff --git a/java/build.gradle b/java/build.gradle
index 30d92e7..dc35d61 100644
--- a/java/build.gradle
+++ b/java/build.gradle
@@ -49,6 +49,7 @@ android.sourceSets.main.java.srcDirs += 'generated-src'

 dependencies {
     compile 'io.v:vanadium-android:1.3'
+    compile 'com.android.support:support-v4:23.0.1'
     compile files(System.getenv("MOJO_DIR") + "/src/out/android_Debug/gen/mojo/public/java/application.jar")
     compile files(System.getenv("MOJO_DIR") + "/src/out/android_Debug/gen/mojo/public/interfaces/application/application_java.jar")
     compile files(System.getenv("MOJO_DIR") + "/src/out/android_Debug/gen/mojo/public/java/bindings.jar")
```

**Comment by afandria** [comment]
It turns out that my android sdk was being drawn from mojo/third_party instead of being taken from a local installation. I'm not 100% sure about why, but upgrading mojo/third_party's android sdk manager to have the support libraries was enough.

There's a little more fixing/README'ing to do, but I am able to build now.
