### ISSUE TITLE
copyright: Use 2016 for new files

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1124]
`jiri copyright fix` should start putting 2016 in the copyright headers instead of 2015.

The copyright test should accept 2015 and 2016, however.

@ivanpi-mtv @nadava 

Assigned to @nlacasse since it's jiri-related, but it doesn't seem very hard to do at first glance. If I have some time, I may do this instead.

**Comment by nlacasse** [comment]
dupe of #1176
