### ISSUE TITLE
java discovery - clarify successful  completion of advertising

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#1130]
AFAICT, there are two ways to end discovery; deliberate, asychronous context cancellation (as the result of a button click) and context "deadline expiration".

Both throw a CancellationException, so both wind up executing the "onFailure" clause of a callback passed to the future returned by the future returned by [VDiscovery.advertise](https://vanadium.googlesource.com/release.java/+/master/lib/src/main/java/io/v/v23/discovery/VDiscovery.java#58).

This forces the client to look for CancellationException in the onFailure clause and treat it as a success.  It seems there's no way that the "onSuccess" method of the aforementioned callback will ever be executed.  

Suggest that either of the two termination conditions above don't result in an exception, and instead trigger onSuccess.  onFailure should be triggered for any other outcome.

Instead of passing 'Void' back, one could pass back an AdvertisingSession object with facts about the completed advertising session, including the reason it ended (cancellation or deadline exceeded) and stats like number of broadcasts, queries or whatnot.

**Comment by jhahn21** [comment]
Fixed by https://vanadium-review.googlesource.com/#/c/20087/.
