### ISSUE TITLE
"jiri cl mail -d" (draft mode) sends email

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#1131]
Would like to use "jiri cl" to push changes to gerrit without triggering emails.

My understanding of "-d" was that this was a 'draft' mode, not triggering an email.  When ready for review, the submitter would visit Gerrit and hit [Publish] to trigger normal email.  Possibly i misunderstood this, or perhaps Gerrit or jiri changed.

**Comment by nlacasse** [comment]
The emails are sent by gerrit, and I'm not sure how to tell gerrit not to email for draft CLs.

I'll look into this.

**Comment by monopole** [comment]
I don't see anything obvious in https://gerrit-review.googlesource.com/Documentation/user-notify.html

**Comment by nlacasse** [comment]
This is known gerrit behavior, and unfortunately there seems to be no way to configure it.

A bug is filed here: https://code.google.com/p/gerrit/issues/detail?id=3381

According to the following link, you can configure your personal notification settings to ignore draft CLs, but no way to prevent the email from going to others.

http://stackoverflow.com/questions/30380882/gerrit-suppress-draft-email-but-allow-drafts-to-be-visible

**Comment by nlacasse** [comment]
WONTFIX
