### ISSUE TITLE
panic in readRemoteAuth

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1132]
When talking to a Vanadium server with a misbehaving client, I made this panic happen. The misbehaving client sent an invalid Setup message (API = 14 but no endpoint name), and then stopped talking. I expected the server close the connection after a while, not panic.

So there's probably two issues, that a no endpoint Setup message does not cause an error, and that this panic happens.

E0207 21:20:50.749235   95802 manager.go:499] failed to accept flow.Conn on localEP @6@wsh@[::]:54879@@0c4fbc24ac9cf7c967620b9791b0b785@s@dev.v.io:u:jra@nella.org:bridge@@ failed: v.io/v23/verror.Timeout: vbridge 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x60 pc=0x44e757d]

goroutine 130 [running]:
v.io/x/ref/runtime/internal/flow/conn.(_Conn).readRemoteAuth(0xc8201c0340, 0xc820350230, 0xc8202e6180, 0xaf, 0xc0, 0xc8201d2200, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/jra/src/v.io/x/ref/runtime/internal/flow/conn/auth.go:215 +0x15d
v.io/x/ref/runtime/internal/flow/conn.(_Conn).acceptHandshake(0xc8201c0340, 0xc820350230, 0xe0000000a, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jra/src/v.io/x/ref/runtime/internal/flow/conn/auth.go:112 +0x5ec
v.io/x/ref/runtime/internal/flow/conn.NewAccepted.func1(0xc8201c0340, 0xc8202faf00, 0xc820350230, 0xe0000000a, 0x0, 0x0, 0x0)
    /Users/jra/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:266 +0x84
created by v.io/x/ref/runtime/internal/flow/conn.NewAccepted
    /Users/jra/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:267 +0x8c1

**Comment by jeffallen** [comment]
The problem is that at this point in the handshake c.remote == nil.

**Comment by jeffallen** [comment]
See v.io/c/19670

**Comment by suharshs** [comment]
Nice find!

> So there's probably two issues, that a no endpoint Setup message does not cause an error, and that this panic happens.

Yes, we should probably also be checking that the client is sending a complete setup message. Out of curiosity, what is the error given by the server after using the fix? I want to make sure that we are throwing an error because the client is using an invalid Setup message, and not accidentally failing for some other reason.

Also could you upload your repro code, we should adapt it into a test.

Thanks!

**Comment by jeffallen** [comment]
With my fix, the server logs a timeout error in readRemoteAuth, which is correct.

My misbehaving client is an experiment and would not be useful to you to write a test. It will also soon be behaving correctly, so... :)

**Comment by suharshs** [comment]
Ok. Sounds good to me.
