### ISSUE TITLE
a malicious client can send a 16 meg Setup message

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1133]
In TCP, the largest frame is 0xffffff bytes long, or 16 megs. A malicious client could fill those 16 megs with uninterpreted options, ensuring that the corresponding Setup message in the server was that big. Now stall the connection until timeout (15 seconds?) and repeat 1000 more times. Probably results in out of memory.

**Comment by ghost** [comment]
@tatatodd @suharshs 

Yes, we have many DOS vectors like this.  Another one is, encode a few 1GB VOM objects as part of your request.  The server will OOM.

We need to generate a comprehensive plan around these things.
