### ISSUE TITLE
Vanadium release-candidate tests failing

### ISSUE THREAD

**Issue by ankurtaly** [vanadium/issues#1136]
The tests started failing on: Feb 6, 2016 4:18:09 AM
https://veyron.corp.google.com/jenkins/job/release-candidate-1-snapshot/356/

It seems to be a jiri tool issue that Nick is working on to fix.

**Comment by ankurtaly** [comment]
Tests to track:
vanadium-go-snapshot
release-candidate-1-snapshot
release-candidate-2-test

**Comment by nlacasse** [comment]
Fixed by v.io/c/19736
