### ISSUE TITLE
jiri path errors

### ISSUE THREAD

**Issue by nlacasse** [vanadium/issues#1137]
Looks like this occurs when the init-vanadium.sh fails before the binaries are built.

java.io.IOException: Cannot run program "" (in directory "/home/veyron/jenkins/workspace/vanadium-js-build-extension"): error=2, No such file or directory

https://veyron.corp.google.com/jenkins/job/vanadium-js-build-extension/1576/console

**Comment by ankurtaly** [comment]
Can you also track: third-party-go-build? (it has a similar error with init-vanadium.sh failing)
https://veyron.corp.google.com/jenkins/job/third_party-go-build/

**Comment by nlacasse** [comment]
Should be fixed by go/vcl/19720
