### ISSUE TITLE
Website tests failing

### ISSUE THREAD

**Issue by ankurtaly** [vanadium/issues#1138]
Creating this issue to track the following failing tests:
- vanadium-website-tutorials-core
- vanadium-website-tutorials-external

**Comment by jxson** [comment]
@ankurtaly just to follow up, the build is green now. Seems like 15mins is the new magic number. I have a CL in review that increases the timeout to an hour for the external tutorial tests only. Hopefully we won't see this problem again for this test target after that is submitted.
