### ISSUE TITLE
RPC: publisher.Status is surprisingly blocky

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#1148]
@spetrovic77 noticed that calling publisher.Status tends to block until a server is mounted.  Upon investigating I realized that this is because there is a synchronous loop inside the publisher that is doing all the work.  When a server starts it issues a Mount command which blocks that loop.  If a user calls status they have to wait for that loop to become unblocked before their status request can be handled.

I think most users would be surprised that calling a Status method can potentially block on an RPC.

**Comment by ghost** [comment]
@suharshs

**Comment by suharshs** [comment]
Its seems like we should allow read access to the pubstate while the mount call is happening, just not while we are updating the state's values. This would involve adding a mutex though... want me to go ahead and do that?

**Comment by ghost** [comment]
Sure.  We might uncover some accidentally passing tests too.
