### ISSUE TITLE
Duplicated files in 'jiri' repo

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1159]
I noticed that there are some duplicated files, e.g.:

https://github.com/vanadium/go.jiri/blob/master/cmd/jiri/which_test.go
https://github.com/vanadium/go.jiri/blob/master/which_test.go

https://github.com/vanadium/go.jiri/blob/master/cmd/jiri/which.go
https://github.com/vanadium/go.jiri/blob/master/which.go

Is this intentional? Maybe it's done for backwards compatibility while deploying changes to jiri?
(I noticed this because I'm updating these files to reflect changes to gosh.)

**Comment by nlacasse** [comment]
This is intentional.  The jiri commands are moving to jiri/cmd, and are currently duplicated during the transition.

The CL in v.io/c/19936 deletes the toplevel files, leaving the ones in jiri/cmd.  I'll close this ticket once that CL is submitted.

**Comment by nlacasse** [comment]
v.io/c/19936 has landed.  duplicate files are gone
