### ISSUE TITLE
Data race/timeout in TestDeviceManagerUpdateAndRevert

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#1168]
Please see here (search for "WARNING: DATA RACE")

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/1642/OS=linux,P=0/consoleFull

It also says:

...
16:29:00 I0224 15:59:06.578827   21981 device_service.go:263] [testDeviceManager stderr] Found 1 data race(s)
16:29:00 I0224 15:59:06.578941   21981 device_service.go:263] [testDeviceManager stdout] READY
16:29:00 I0224 15:59:06.579004   21981 device_service.go:263] [testDeviceManager stdout] v2DM terminated
16:29:00 E0224 15:59:06.579309   21981 dispatcher.go:190] Invoke(method:Update argptrs:[]) returned error: impl.test:"device".Update: operation failed: testDeviceManager failed: impl.test:"device".Update: operation failed: new device manager failed to exit cleanly: exit status 66
**16:29:00 panic: test timed out after 30m0s**

Thanks!
- Jing

**Comment by caprita** [comment]
Moved to https://github.com/vanadium/build/issues/10
