### ISSUE TITLE
"jiri go" commands should not refer to tools in "$PATH"

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#1169]
The jiri tool builds and squirrels away a set of tools it needs (e.g. vdl); when it comes time to use these tools, it should pull them from the location it knows about, instead of letting the user's PATH dictate where the tools come from.

For example, if I have $JIRI_ROOT/release/go/bin as the first thing in my PATH, and run "jiri go build", it should _not_ use the version of the vdl tool from $JIRI_ROOT/release/go/bin.

@tatatodd and @bprosnitz have some ideas on the right way to do this.

**Comment by nlacasse** [comment]
If you run the jiri _script_ rather than running the jiri _binary_ directly, then the PATH will be set such that those "squirreled away" binaries are at front.  See v.io/c/20086.

We should be encouraging users to put $JIRI_ROOT/.jiri_root/scripts in their path, rather than $JIRI_ROOT/.jiri_root/bin, so that things will "just work" for them.

**Comment by nlacasse** [comment]
The Vanadium installation correctly instructs users to add `$JIRI_ROOT/.jiri_root/scripts` to their PATH.  So we are encouraging the correct behavior.

However, lots of current Vanadium devs still have devtools/bin in their PATH, but we need to phase that out.

**Comment by caprita** [comment]
The instructions I could dig up (https://vanadium.github.io/community/contributing.html) suggest:

export PATH=$PATH:$JIRI_ROOT/devtools/bin

That places $JIRI_ROOT/devtools/bin (which I'm guessing you'll soon replace with $JIRI_ROOT/.jiri_root/scripts?) at the _end_ of the PATH. It's still possible (and likely) that folks have $JIRI_ROOT/release/go/bin earlier in the PATH.

**Comment by caprita** [comment]
I just saw your first reply, which made your second reply make more sense :-) Perhaps we can add some logic in the jiri tool to warn people if the jiri tool was invoked directly instead of via the script you mention?

**Comment by bprosnitz** [comment]
There is a go test that regenerates the vdl tree using the vdl binary in your path. I'm not sure exactly what test it is, but I have noticed it when developing vdl. I think this test should probably not do this in general, but if it must we should make sure that it is straightforward to use your own built version of vdl when it regenerates the tree.

**Comment by nlacasse** [comment]
v.io/c/20235

**Comment by nlacasse** [comment]
v.io/c/20235 has been merged.
