### ISSUE TITLE
TestV23GroupServerAuthorization in groupsd is flaky

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#1171]
It timed out several times in the last a few days. Here is the related log:

fail v.io/x/ref/services/groups/groupsd
...
--- FAIL: TestV23GroupServerAuthorization (63.35s)
    expect.go:119: util.go:45: ExpectVar: NAME=/@6@wsh@127.0.0.1:33883@@983c81fbd1ca98e05894762e1b3ff3f2@m@root:child@@
    expect.go:119: groupsd_v23_test.go:256: Expect: SET OK
    expect.go:119: groupsd_v23_test.go:258: Expect: GET OK bar
    expect.go:119: groupsd_v23_test.go:260: Expect: GET OK bar
    expect.go:119: groupsd_v23_test.go:262: Expect: SET FAILED v.io/v23/verror.NoAccess
    expect.go:119: groupsd_v23_test.go:267: timeout: Expect:
    expect.go:131: groupsd_v23_test.go:267: timeout
FAIL
exit status 1
FAIL    v.io/x/ref/services/groups/groupsd  151.120s

Could you please take a look? (feel free to re-assign)

Thanks!
- Jing

**Comment by asadovsky** [comment]
Ack, will take a look and probably just bump the timeout.

**Comment by asadovsky** [comment]
Just took a look at this. This test builds several binaries (using v23test.BuildGoPkg), starts a couple servers, then runs client code and checks expectations. In my local runs, starting servers and running client code takes approximately 3 seconds (I tried several times). Nearly all of the test running time is spent building binaries. It's unfortunate that our Jenkins machines are so slow. I'll send a CL to add some logging, so we can better diagnose the slowdowns on Jenkins, but it seems we'll need to bump the Jenkins timeout for this test. How do I do that?

(Reassigning to Jing to answer my questions and/or bump the timeout.)

**Comment by jinjingforever** [comment]
Sent you a CL to bump the timeout. Thanks

**Comment by jinjingforever** [comment]
See logs here:

https://veyron.corp.google.com/jenkins/job/vanadium-integration-test/1768/OS=linux/console

The other thing is: at the time we were using 32 workers to run all go related tests. If many of them happen to be scheduled on a single virtual machine, it might cause cpu starvation. I've reduced the number of workers to 4 after that. I haven't seen any timeout in this test ever since.

**Comment by asadovsky** [comment]
Thanks. Hmm, it's too bad - it doesn't look like there's a way there to see the actual output from the child process, so there's no easy way to debug this. Perhaps that's what I should've added in my CL instead of the Infof logging - in hindsight (given what's timing out is the session) I don't think my Infof logs are particularly useful. I'll send you a CL to revert those...

OK, let's reopen this issue if we see timeouts again with the 4 worker limit.
