### ISSUE TITLE
v.io/x/ref/services/agent/internal/ipc.TestBadConnect is flaky

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#1172]
It failed a couple of times with the same error in the last few days. Here is the related log:

--- FAIL: TestBadConnect (0.01s)
  ipc_test.go:127: write unix @->/tmp/sock317425984/sock: write: broken pipe

Could you please take a look? Thanks!
- Jing

**Comment by suharshs** [comment]
Assigned @ribrdb since it seems to be an issue with the Agent closing the unix fd for some reason.

**Comment by caprita** [comment]
Moved to https://github.com/vanadium/build/issues/11
