### ISSUE TITLE
v.io/x/ref/lib/discovery.TestVisibility is flaky

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#1175]
It failed several  times in go-race test:

--- FAIL: TestVisibility (16.34s)
  discovery_test.go:163: Match failed; got [], but wanted [{6(2!hti7h9w^  v.io/v23/a map[a1:v1 a2:v2] [/h1:123/x /h2:123/y] map[]}]
discovery_test.go:170: Match failed; got [], but wanted [{6(2!hti7h9w^  v.io/v23/a map[a1:v1 a2:v2] [/h1:123/x /h2:123/y] map[]}]

Could you please take a look? Thanks!
- Jing

**Comment by caprita** [comment]
MOVED TO https://github.com/vanadium/build/issues/8
