### ISSUE TITLE
jiri profiles: Test `update` when multiple targets for the same profile are installed

### ISSUE THREAD

**Issue by nlacasse** [vanadium/issues#1177]
When running "jiri v23-profile update", the code loops through all installed targets, and if a newer target is available, it will install that target.

But consider if you have two versions of a profile installed with versions "6" and "7", and "7" is the default.

The code will encounter version "6" and try to update to "7", but "7" is already installed, so it will crash.

The error was triggered recently when we pushed a new version of the mojo profile, and everybody ended up in exactly this scenario.

The fix for this case is in v.io/c/20231, but it needs tests.

**Comment by cosnicolaou** [comment]
closed by v.io/c/20274
