### ISSUE TITLE
v.io/x/ref/services/agent/internal/ipc TestBadConnect flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1179]
Test appears to be flaky, e.g. from a recent presubmit:
https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&job=vanadium-go-race&n=20839&os=linux&part=1&suite=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&test=TestBadConnect+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by caprita** [comment]
Looks like the same issue as https://github.com/vanadium/build/issues/11 
Marking as duplicate.
