### ISSUE TITLE
TestBarrier test flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1180]
Test appears to be flaky, e.g. from a recent presubmit:
https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Flib%2Fdiscovery&job=vanadium-go-race&n=20839&os=linux&part=4&suite=v.io%2Fx%2Fref%2Flib%2Fdiscovery&test=TestBarrier+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by jhahn21** [comment]
I couldn't reproduce it, but I tried to remove the time dependency: 
https://vanadium-review.googlesource.com/#/c/20766/
