### ISSUE TITLE
flaky: vanadium-js-browser-integration::Timeout

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1182]
this test has been flaky in presubmits for a while now.

https://dashboard.v.io/?arch=amd64&class=vanadium-js-browser-integration&job=vanadium-js-browser-integration&n=20905&os=linux&part=0&suite=vanadium-js-browser-integration&test=Timeout&type=presubmit

**Comment by nlacasse** [comment]
This test has been disabled.
