### ISSUE TITLE
Syncbase docs: Guides - Batches

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1192]
Design Doc: https://docs.google.com/document/d/14iQKJQXPCe6OPmq3mkn86dxtXiQuhrx2NtC3eD-nBDU/edit#heading=h.sv2de67l143
- [ ] Content
- [ ] Java code snippets
- [ ] Go code snippets
- [ ] User testing

@ivanpi-mtv + @asadovsky

**Comment by ivanpi-mtv** [comment]
Reassigned to @razvanm + @ivanpi-mtv + @asadovsky
