### ISSUE TITLE
flaky vanadium-regression-test::Internal Error

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1204]
I've seen this vbinary flake several times this week....

https://dashboard.v.io/?arch=amd64&class=vanadium-regression-test&job=vanadium-regression-test&n=21048&os=linux&part=0&suite=vanadium-regression-test&test=Internal+Error&type=presubmit

**Comment by rthellend** [comment]
It's getting a 503 from googleapis

failed to download binary: failed to download file linux_amd64/2016-02-28T05:12:38-08:00/gosh_example: got StatusCode https://www.googleapis.com/download/storage/v1/b/vanadium-binaries/o/linux_amd64%2F2016-02-28T05%3A12%3A38-08%3A00%2Fgosh_example?alt=media for download 503

It looks like we're already retrying the downloads. It might just be a matter of retrying longer.

@jinjingforever , what do you think?

**Comment by rthellend** [comment]
Actually, I think the retry logic isn't quite right. It looks like the download succeeded after the retry, but then we got errors writing the downloaded files to disk.

Attempt 2/3:
failed to download binary: cmd.go:349: WriteFile(/home/veyron/tmp/vanadium-regression-test/260234639/regtest/2016-02-28/.done, ,  -rwxr-xr-x): open /home/veyron/tmp/vanadium-regression-test/260234639/regtest/2016-02-28/.done: no such file or directory
[...]

Should we add a MkdirAll() before the WriteFile() ?
