### ISSUE TITLE
Changes to vdl are not reflected in presubmits

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#1206]
Likely related to https://vanadium-review.googlesource.com//#/c/20235/3/jiri/x.go

After changing the vdl output, I now have errors in nearly all of my presubmits https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/21083/ 

If I put my modified vdl binary in devtools/bin, I don't see these errors but if I build locally with the version of vdl from jiri update I get an identical error so I believe it isn't using my modified version of vdl on jenkins.

**Comment by nlacasse** [comment]
The presubmit-test binary pulls the CL changes builds all tools into a "tmpBinDir", and adds that to the PATH.

The CL in v.io/c/20235 prepends .jiri_root/bin to the PATH, so the tmpBinDir is ignored, breaking tests that rely on the newly built subcommands.

Todd has fixes in v.io/c/20345 and v.io/c/20346.

**Comment by tatatodd** [comment]
@bprosnitz - can you confirm that the above CLs fix the problem, and if so, close this out?  I didn't write any tests for the above behavior.  :)

**Comment by bprosnitz** [comment]
Yes, the problem is fixed.
