### ISSUE TITLE
flaky v::io/x/ref/lib/discovery::TestVisibility [GoRace - linux,amd64]

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1209]
this test is flaky in presubmits: https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Flib%2Fdiscovery&job=vanadium-go-race&n=21160&os=linux&part=4&suite=v.io%2Fx%2Fref%2Flib%2Fdiscovery&test=TestVisibility+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by asimshankar** [comment]
Moved to vanadium/build#22
