### ISSUE TITLE
.jiri_root/scripts/jiri doesn't have execute permission

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#1216]
@nlacasse 

I tried adding `.jiri_root/scripts/jiri` to my path to use the new `jiri` script in favor of `jiri` binary.
Now when I run `jiri`, it says Permission denied.

```
youngseokyoon scripts$ ll
total 12
drwxr-x--- 2 youngseokyoon eng 4096 Mar  3 11:26 ./
drwxr-x--- 6 youngseokyoon eng 4096 Mar  3 11:26 ../
-rw-r----- 1 youngseokyoon eng 2191 Mar  3 11:26 jiri
youngseokyoon scripts$ 
```

It seems like the execute permission is not applied when copying the script from the repo.

**Comment by nlacasse** [comment]
https://vanadium-review.googlesource.com/#/c/20430/
