### ISSUE TITLE
gosh: revert v.io/c/20483 and resolve the underlying issue (w.r.t. concurrent BuildGoPkg)

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1220]
+cc @tatatodd @caprita 
See CL description for https://v.io/c/20483, along with my review comment.

**Comment by caprita** [comment]
The simplest fix (I was considering doing myself before settling on reverting instead) would be to have each test build its own binaries rather than being shared across all tests run as part of a vanadium-integration-test suite. There's of course the efficiency argument (we'd be rebuilding the same target repeatedly instead of only once), but I don't think it's a huge deal compared to the total execution time of the integration test suite. Moreover, it allows each test to build their binaries potentially with different configurations and flags. I am not a big fan of cross-test dependencies :-)

**Comment by asadovsky** [comment]
Where does the concurrency actually come from? Are we running "go test" with the -parallel flag? Or is it that we run something like "go test ...", which runs different packages' tests concurrently? If it's the latter, I suppose we could write binaries to a package-specific test location to retain binary sharing across tests within a given package.

Orthogonal to that: Resolving [this TODO](https://github.com/vanadium/go.ref/blob/master/test/v23test/v23test.go#L50) by refactoring StartRootMountTable and StartSyncbase to use FuncCmd-based execution would dramatically reduce the number of BuildGoPkg invocations in our tests.

I don't see any great way to make BuildGoPkg concurrency-safe. Even os.Rename is apparently not atomic: https://groups.google.com/forum/#!topic/golang-nuts/ZjRWB8bMhv4

Of course, we could make BuildGoPkg do more things to make races less likely, but I don't really want to venture down this path...

**Comment by caprita** [comment]
Running with: jiri test run vanadium-integration-test
The parallelism comes from the jiri tool: i goes out of its way to run things simultaneously (https://cs.corp.google.com/vanadium/release/go/src/v.io/x/devtools/jiri-test/internal/test/go.go?l=674)

I reiterate my personal preference for the simplest solution: no sharing of binaries, either across different tests, or the same test across invocations. It's the sort of hidden dependency that has and will bite us again and again. So as long as each shell uses a brand new location for binaries it builds, we should be ok (I hope :-))

Especially with your TODO about mounttable and syncbase, the argument for sharing binaries for efficiency's sake is diminished.

**Comment by tatatodd** [comment]
Yeah, it seems that in general there's no way to make BuildGoPkg concurrency-safe.  In theory, we could succeed if the target already exists _and_ is byte-wise identical to our freshly-built copy.  But there's no guarantee that multiple go builds produce byte-wise identical binaries.

I like the idea of resolving the TODO to reduce BuildGoPkg invocations, and also to not share binaries.

**Comment by asadovsky** [comment]
I fixed this a couple weeks ago or so, by updating v23test to stop sharing binary dirs across test packages, thus avoiding the race condition.
