### ISSUE TITLE
flaky: v::io/x/ref/services/agent/internal/ipc::TestBadConnect

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1229]
the following test is flaky:
v::io/x/ref/services/agent/internal/ipc::TestBadConnect [GoRace - linux,amd64]
https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&job=vanadium-go-race&n=21851&os=linux&part=1&suite=v.io%2Fx%2Fref%2Fservices%2Fagent%2Finternal%2Fipc&test=TestBadConnect+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by asimshankar** [comment]
Reopening vanadium/build#11
