### ISSUE TITLE
Website installation instructions are incongruent / v23_root and vanadium directory instructions conflict

### ISSUE THREAD

**Issue by danafergan** [vanadium/issues#1231]
Installing Vanadium on a fresh machine...

When I source the vanadium-install script from http://vanadium.github.io/installation/, it installs vanadium to $HOME/v23_root. However, http://vanadium.github.io/community/contributing.html instructs the user to set JIRI_ROOT to $HOME/vanadium. 

/devtools/bin is actually a symlink to $HOME/v23_root/.jiri_root/bin, so one can't just rename v23_root to vanadium (my 1st instinct), but changing $JIRI_ROOT to $HOME/v23_root works. 

I'm not sure what the intended/default home dir is for users that don't want to reconfigure it.
Possible solutions are to change the directions on contributing.html to ${HOME}/v23_root or changing the install script and site to reference $HOME/vanadium

**Comment by nlacasse** [comment]
One potential fix is to replace $HOME/vanadium with $HOME/v23_root in the contributor guide.
https://vanadium-review.googlesource.com/#/c/20715/

Another idea is to completely remove the redundant (and currently inconsistent) code block at the top of the contributor guide.

**Comment by nlacasse** [comment]
https://vanadium-review.googlesource.com/#/c/20715/ was checked in.
