### ISSUE TITLE
flaky v::io/x/ref/lib/discovery/global::TestVisibility

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1235]
I've seen this flake over the past week or so:

v::io/x/ref/lib/discovery/global::TestVisibility [GoRace - linux,amd64]
https://dashboard.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Flib%2Fdiscovery%2Fglobal&job=vanadium-go-race&n=21907&os=linux&part=4&suite=v.io%2Fx%2Fref%2Flib%2Fdiscovery%2Fglobal&test=TestVisibility+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by caprita** [comment]
Moved to https://github.com/vanadium/build/issues/26
