### ISSUE TITLE
Change jiri update to always rebuild all tools from clean branches

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1236]
@nlacasse @asadovsky 

Adam ran into a problem with my latest vdl changes.  I'm not sure exactly what the problem is (I haven't inspected the code), but roughly speaking it's something like this.

I think the current jiri tool only checks out the master branch of "v.io/jiri" when it rebuilds tools.  I.e. I think it only does ApplyToLocalMaster on the release.go.jiri project, and not any of the other branches.  This is problematic, since it can cause "jiri update" to fail to build the tools, and at that point it's really easy to get in a weird stuck state.

The easiest workaround is typically to checkout the master branch of all projects before running "jiri update".  As Adam noticed, sometimes there's a further catch, where you might have untracked files that screw things up.  So you need to deal with those too, either getting rid of them, or stashing them.

The behavior we actually want is for the jiri tool to update all projects to their desired configuration (i.e. revision/remotebranch), and _while in that state_, build all the tools.

Some details
1. In my examples above I loosely said "master branch", but really we want whatever revision/remotebranch the user has configured.
2. The desired configuration is determined by each project's attributes.  The import attributes are irrelevant, since they should only affect how we load the manifest file, and nothing else.
3. We also want the stash / pop logic baked into this, so that every project is really in a completely clean state.

I'm assigning to myself just so I don't forget.

**Comment by nlacasse** [comment]
I just took a look at the code, and it seems to do exactly what @tatatodd suggests it should do.

https://github.com/vanadium/go.jiri/blob/master/project/project.go#L1235

`buildToolsFromMaster` collects all projects from all tools, and then calls `applyToLocalMaster` with those projects and builds the tools.

I put a printf inside `buildToolsFromMaster`, and toolProjects contains devtools, jiri, and x.ref, as we would expect. 

```
toolProjects: project.Projects{
"release.go.x.devtools=https://vanadium.googlesource.com/release.go.x.devtools":project.Project{Name:"release.go.x.devtools", Path:"/usr/local/google/home/nlacasse/code/v/release/go/src/v.io/x/devtools", Protocol:"git", Remote:"https://vanadium.googlesource.com/release.go.x.devtools", RemoteBranch:"master", Revision:"85d3175a06a69fa9e21753a9b7f7c76b85fe18a1", GerritHost:"https://vanadium-review.googlesource.com", GitHooks:"/usr/local/google/home/nlacasse/code/v/manifest/git-hooks", RunHook:"", XMLName:struct {}{}}, 
"release.go.x.ref=https://vanadium.googlesource.com/release.go.x.ref":project.Project{Name:"release.go.x.ref", Path:"/usr/local/google/home/nlacasse/code/v/release/go/src/v.io/x/ref", Protocol:"git", Remote:"https://vanadium.googlesource.com/release.go.x.ref", RemoteBranch:"master", Revision:"adb6cdb2223c79cc6d1ae06c93c279e1398af12a", GerritHost:"https://vanadium-review.googlesource.com", GitHooks:"/usr/local/google/home/nlacasse/code/v/manifest/git-hooks", RunHook:"", XMLName:struct {}{}}, 
"release.go.jiri=https://vanadium.googlesource.com/release.go.jiri":project.Project{Name:"release.go.jiri", Path:"/usr/local/google/home/nlacasse/code/v/release/go/src/v.io/jiri", Protocol:"git", Remote:"https://vanadium.googlesource.com/release.go.jiri", RemoteBranch:"master", Revision:"31884e6cea219bc822a38b2374c22ee8b2df462b", GerritHost:"https://vanadium-review.googlesource.com", GitHooks:"/usr/local/google/home/nlacasse/code/v/manifest/git-hooks", RunHook:"", XMLName:struct {}{}}}
```

Maybe the issue is that the vdl tool lives in x.ref project, but depends on code in v23 (or some other repo), which does not get checked out from master before building the tools?

We may need to set ALL projects to master before building tools, not just the projects listed in the tools.

**Comment by nlacasse** [comment]
I think we do need to set _all_ projects to clean master before building the tools, not just the ones specified in the `<tools>` tags

Here's a CL that does that:
https://vanadium-review.googlesource.com/20752

Another idea might be to make tools specify all the projects they depend on, but this would be difficult to enforce.

**Comment by tatatodd** [comment]
Ah nice, thanks for looking Nick!

Yeah, the problem is that the vdl tool depends on the release.go.v23 project.  Ah, you just responded.  :)

I agree, let's set _all_ projects to clean master before building tools.  As you note, an alternative is to try to specify the dependencies, but we're likely to get it wrong, and it seems complicated.

**Comment by nlacasse** [comment]
https://vanadium-review.googlesource.com/20752
