### ISSUE TITLE
flaky v::io/jiri/project::TestRemoteImportCycle

### ISSUE THREAD

**Issue by cosnicolaou** [vanadium/issues#1237]
another flaky test...
v::io/jiri/project::TestRemoteImportCycle [GoRace - linux,amd64]
https://dashboard.v.io/?arch=amd64&class=v.io%2Fjiri%2Fproject&job=vanadium-go-race&n=21953&os=linux&part=6&suite=v.io%2Fjiri%2Fproject&test=TestRemoteImportCycle+%5BGoRace+-+linux%2Camd64%5D&type=presubmit

**Comment by caprita** [comment]
Are you sure this is not just flakiness in the CL being presubmit-tested?
(asking simply because I haven't seen this flake in the post-submit, and the CL seems to touch the jiri tool which is where the test is)

**Comment by nlacasse** [comment]
I've seen this flake once or twice in presubmits. I don't think it's
related to Cos's changes.

I'll investigate this week.

**Comment by caprita** [comment]
Sounds good. Moved to https://github.com/vanadium/build/issues/27
