### ISSUE TITLE
Bluetooth not working on Darwin

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#1250]
With Go 1.6, the paypal/gatt library that we use doesn't quite work on OS X. See paypal/gatt#64
For now, we've disabled the failing tests (vanadium/third_party@1835d52be3920b19d4808026231e6dac9a72bb51) as a workaround to keep the builds green but as and when we start wanting to use BLE on OS X, then we'll need to address this problem.

CC @jhahn21

**Comment by anubhav-sri** [comment]
any updates on it?

**Comment by asimshankar** [comment]
Hi @anubhav-sri - a quick fix for this hasn't been prioritized at this moment but we are working on reworking out bluetooth discovery stack to work on multiple platforms (linux with bluez, android, ios and osx).

If this is something that is of interest to you, we can consider reprioritizing. Would be curious to hear how you're using Vanadium. Thanks.

**Comment by asimshankar** [comment]
Fixed by commit vanadium/go.ref@e0b3897d08143e0718f1cd1bbbd989aec5e4a16d
