### ISSUE TITLE
RPC: Traffic goes through proxy instead of a more direct connection

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1257]
Observed with Syncbase's Ping Pong Benchmark.

On Android and syncslides-alpha network, the Ping Pong Iteration takes
- 450ms w/o proxy
- 1000ms w/ proxy (instead of the same amount)

Note that the +550ms is a common network latency increase seen when routing this test's traffic through the proxy. This is also seen on Go (same device), Go (different devices), and Mojo Syncbase.

@suharshs

**Comment by ghost** [comment]
Suharsh was going to fix this.
