### ISSUE TITLE
obtaining nodejs bin path in Makefiles broken (for me)

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#1265]
There are at least two ways in which Makefiles in Vanadium attempt to get the path to the node and npm commands:

[1] From www (https://cs.corp.google.com/vanadium/www/Makefile?l=1)

`NODE_DIR := $(shell jiri profile list --info Target.InstallationDir v23:nodejs)`

This uses jiri profile list, but only works when there is just one entry. If, as in my case, there more than one, it breaks:

```
$ jiri profile list --info Target.InstallationDir v23:nodejs
v23:nodejs amd64-linux@10.24 /usr/local/google/home/caprita/vanadium/.jiri_root/profiles/v23/cout/node-v0.10.24/amd64_linux
v23:nodejs amd64-linux@4.4.1 /usr/local/google/home/caprita/vanadium/.jiri_root/profiles/v23/nodejs/node-v4.4.1/amd64_linux
```

[2] From playground/client (https://cs.corp.google.com/vanadium/release/projects/playground/client/Makefile?l=1)

`NODE_BIN := $(shell jiri profile env --profiles=v23:base,v23:nodejs NODE_BIN=)`

This uses jiri profile env, but in my case at least, the env does not contain the NODE_BIN variable, so this fails as well.

**Comment by caprita** [comment]
@nlacasse @jxson

**Comment by nlacasse** [comment]
The second method is correct.  If it does not work for you, you may need to run `jiri profile update`.

I did not update the Makefile in the "www" repo because it has been deprecated.

**Comment by nlacasse** [comment]
Just verified that the "website" repo has the correct node path command.

Bogdan's issue was fixed by manually deleting his old nodejs profile with version bad "10.24" version, and re-installing.
