### ISSUE TITLE
Can no longer install v23:base@4

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#1269]
I think it is related to Go 1.6 changes. I needed go 1.5.1 so I tried installing base profile version 4 which has Go 1.5.1 (on a fresh JIRI_ROOT checkout) it fails trying to call `make.bash` to install Go. It is trying to call it in `go/amd_linux/560937434d5f2857bb69e0a6881a38201a197a8d/src/make.bash` but there is a `go-bootstrap` fonder between the `src` and `560937434d5f2857bb69e0a6881a38201a197a8d`.

For now I reverted v.io/c/20696 locally to get Go 1.5.1 installed

**Comment by asimshankar** [comment]
I'm going to close this out for now, with no real intention of getting things to work with Go 1.5.

Please let me know if you disagree :)
