### ISSUE TITLE
Broken link on v23 godoc

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#1270]
https://godoc.org/v.io/v23

The v23 link links to v.io/v23, which no longer has content. We should probably change it to github. Possibly:

https://github.com/vanadium/go.v23

**Comment by AsturaPhoenix** [comment]
https://github.com/vanadium/docs in release.go.v23/README.md is broken too.

**Comment by AsturaPhoenix** [comment]
https://github.com/vanadium/docs => https://vanadium.github.io ?

**Comment by asadovsky** [comment]
Yes, https://github.com/vanadium/docs => https://vanadium.github.io

I'm not sure what controls the "v23" link on https://godoc.org/v.io/v23, but having that point to GitHub seems fine if it's possible to configure that.

**Comment by AsturaPhoenix** [comment]
I haven't figured out where the "v23" link is coming from yet either. For the others,
[topic: vanadium/docs -> vanadium.github.io](https://vanadium-review.googlesource.com/#/q/topic:%22vanadium/docs+-%253E+vanadium.github.io%22)

**Comment by AsturaPhoenix** [comment]
Both [v.io/v23](https://v.io/v23) and [github.com/vanadium/go.v23](https://github.com/vanadium/go.v23) are valid import paths for Vanadium.

While the Github import path naturally links to the Github repo, since v.io/v23 also serves the package and is the canonical import path for Vanadium, by default godoc expects the project URL to be v.io/v23.

It looks like we can override this by tweaking our go-get server. The go-source meta tags include a project URL override, which we currently set to "_" (use default, which is a broken link now).

https://github.com/golang/gddo/blob/master/gosrc/gosrc.go#L286
https://github.com/golang/gddo/blob/master/gosrc/gosrc.go#L372

**Comment by asimshankar** [comment]
I see the github.com/vanadium/docs links are bad and should be replaced with https://vanadium.github.io/<something>

However, I'm confused about what's broken as far as the links to source code are concerned.
They seem to already link to the github code? For example, the links on the function names in https://godoc.org/v.io/v23#GetBackgroundContext take you to github.com/vanadium/<appropriate line in source code>

So what's broken? As in, what's pointing to v.io/v23?

**Comment by AsturaPhoenix** [comment]
The first link in div#x-projnav, i.e. the first v23 in "v23: v.io/v23          Index | Files | Directories". Likewise for https://godoc.org/v.io/jiri and all our Godocs using the canonical import path.

**Comment by asimshankar** [comment]
Ah, I see. Thanks

**Comment by AsturaPhoenix** [comment]
Closed via https://vanadium-review.googlesource.com/#/c/21348/
