### ISSUE TITLE
Regression test needs realistic credentials

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#1272]
https://vanadium-review.googlesource.com/#/c/21093/ broke backward compatibility with prod services.  This was not caught by the regression test because it only caused problems when clients had discharges, and the regression tests don't use realistic credentials.

We should have realistic credentials in the regression tests to prevent surprise failures like this.

@suharshs @rthellend

**Comment by rthellend** [comment]
When we first observed this problem, nothing was using third party caveats.
