### ISSUE TITLE
Relative paths support in v23agentd

### ISSUE THREAD

**Issue by razvanm** [vanadium/issues#1283]
v23agentd doesn't seem to like relative paths. If a valid set of credentials exist in a path, point to them using either V23_CREDENTIALS or -v23.credentials will generate a zombie process v23agentd and show an error like the following (the relative paths used in this case was `./cred/me`):

```
ERROR: failed to create new principal from dir(./cred/me): open cred/me/privatekey.pem: no such file or directory
```

**Comment by caprita** [comment]
Leftover zombie taken care of by: https://vanadium-review.googlesource.com/#/c/21679/
Relative path issue take care of by: https://vanadium-review.googlesource.com/#/c/21701/
