### ISSUE TITLE
VDL-generated Go files with errors have stray comment in godoc

### ISSUE THREAD

**Issue by jeffallen** [vanadium/issues#1288]
The generated files have this in them:

  //////////////////////////////////////////////////
  // Error definitions
  var (

That results in this line in the godoc output: "//////////////////////////////////////////////// Error definitions"

See for example https://godoc.org/v.io/x/ref/services/xproxy/xproxy

The fix is clearly just to simplify the template VDL uses for generating Go code and regen all the VDL files. But that's a bigger more delicate task than I know how to do on my own.

**Comment by tatatodd** [comment]
Thanks for reporting this.  I'll take care of it; we're making lots of vdl/vom changes at the moment, and we'll get it in at some point.

**Comment by tatatodd** [comment]
Fixed by https://vanadium-review.googlesource.com/#/c/21736
