### ISSUE TITLE
reconsider generic runtime factory

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#1289]
The generic runtime factory is currently crippled in a couple ways:
- it doesn't use the debug dispatcher
- it doesn't contain the cloud configuration logic

Would there be any practical situation where we'd want the generic profile over the roaming profile?

**Comment by asimshankar** [comment]
I don't think there is a good reason to have the generic runtime factory anymore, I will find out if there is while removing it from the codebase

For the record, my plan is the following:
- [ ] Replace all uses of the "generic" runtime factory with "roaming" in the codebase
- [ ] Renaming the roaming factory to "cmdline" or something, signaling that it is meant to be used by "command line" applications (as opposed to "android" or "ios" applications)

**Comment by caprita** [comment]
'cmdline' may be too suggestive of a command-line tool, though I am at a loss for a better name.

That said, 'roaming' and 'android' are very similar in implementation; should the factories really be about OS-es? Or more about functionality? Why shouldn't the 'roaming' profile also be used for android apps? So e.g. a given main.go can import the 'roaming' profile, but then we can build that binary for either linux_amd64 or android_arm or whatever and it would build with the right code for that platform (platform-specific code would be guarded by build directives). I guess I am not very clear where we're going with the factories, perhaps we should answer that question first before considering renaming 'roaming'.

**Comment by asimshankar** [comment]
Obsolete
