### ISSUE TITLE
TODOs: Startup time for Syncbase is too slow

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1318]
We do a lot of stuff when starting up the Syncbase Persistence, which blocks the app from starting.

@AsturaPhoenix @afandria

**Comment by AsturaPhoenix** [comment]
We should instrument this and separate out Vanadium init and Syncbase startup.

**Comment by asadovsky** [comment]
My comment in #1315 may be relevant to this as well.

**Comment by afandria** [comment]
It's much faster now and will be even faster if we stop attempting to contact the cloud during startup.

**Comment by afandria** [comment]
The rest will be handled in #1332
