### ISSUE TITLE
Java release process is very questionable

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#1319]
@sjamesr @spetrovic77 

The java release process is documented here:
https://github.com/vanadium/java/blob/master/RELEASING.md

It's unclear what permissions are required to perform some of these steps.  Specifically, I'm trying to release a new version of the vdl gradle plugin.  

```
$ cd $JIRI_ROOT/release/java/gradle-plugin
$ ./gradlew clean bintrayUpload
...
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':bintrayUpload'.
> No value has been specified for property 'user'.
> No value has been specified for property 'apiKey'.
```

James and/or Srdjan - can one of you transfer all admin rights that we might need over to one of us?  Or perhaps there's something else that's going wrong?

**Comment by yyoon** [comment]
@AsturaPhoenix might have the permissions.

**Comment by sjamesr** [comment]
The releasing instructions provide information for how to get all necessary permissions for performing a release. What's missing is probably the following one-time setup:
- Go to https://bintray.com/profile/edit (sign in if necessary)
- Generate an API key, copy it to `$HOME/.gradle/gradle.properties`. The file should look like

```
bintrayUsername=yourGithubUsername
bintrayApiKey=yourApiKey
```

**Comment by tatatodd** [comment]
Awesome, that works, thanks!

I'll update the release instructions.

**Comment by sjamesr** [comment]
Just sent you a CL to do that :)

**Comment by tatatodd** [comment]
I managed to push a new version 1.7 out to JCenter / bintray:

https://bintray.com/vanadium/io.v/gradle-plugin/1.7/view?sort=&order=#files/io/v/gradle-plugin/1.7
https://jcenter.bintray.com/io/v/gradle-plugin/

I followed the instructions to push out to Maven Central, which says it succeeded about 30 minutes ago:

https://bintray.com/vanadium/io.v/gradle-plugin/1.7/view?sort=&order=#central

But the link listed in the instructions shows that the last update was in Dec 2015:

https://repo1.maven.org/maven2/io/v/gradle-plugin/

Is the link bad?  What would be the correct one?

**Comment by AsturaPhoenix** [comment]
iirc, Maven Central can take significantly longer to be live. I'd give it a day. It's quite possible we just never published versions 1.0-1.6

If you're concerned about linking, Maven Central is [searchable](http://search.maven.org/#search%7Cga%7C1%7Cio.v%20gradle-plugin).

**Comment by spetrovic77** [comment]
We mostly didn't bother publishing to Maven, because it takes longer and our Java code depends on jcenter(), which gets data from bintray.

**Comment by sjamesr** [comment]
@spetrovic77 is right, 1.7 just appeared at http://repo2.maven.org/maven2/io/v/gradle-plugin/

Some of us weren't always publishing to Maven Central
