### ISSUE TITLE
TODOs: Userdata collections are cross-shared

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1320]
I spoke to @rdvg about this, and it might be a temporary bug caused by the migration from the old sync to new sync protocol.

Scenario:
- Email A and Email B are using this app. There is also a cloud.
- Email A creates its user data collection and creates a syncgroup pointing to the cloud.
- Email B also creates its user data collection and creates a syncgroup pointing to the cloud. The database and collection names are the same.

Expected Behavior:
- Data written by A and data written by B will remain independent.

Actual Behavior:
- Data written by A and B are mixed together, probably via the cloud instance.

Even though the collection names are the same, the blessings strings are different between A and B, so I expected that the data would not cross. Is this the right thing to expect? Is it possible that instead of using the tuple (blessing string, collection name), we are only syncing based on collection name right now?

I'll need to check in on this again to decide whether I need to do anything. A potential workaround for TODOs is to use the email address to make each userdata's collection name unique between different emails. Currently, the erroneous behavior is innocuous (extra debug logs, an error toast, and/or silently dropped errors).

@hpucha @AsturaPhoenix @rdvg

**Comment by afandria** [comment]
A slightly better workaround in the short term is to use CollectionFromId (or something similarly spelled) so that I can manually pass in the blessing portion of the collection id

**Comment by asadovsky** [comment]
In the Go API, database has a "CollectionForId" method that does exactly what you want.
Does Java not have that? It should; it's part of the low-level API.

**Comment by afandria** [comment]
We do have it. It's also on Database as `public Collection getCollection(Id collectionId)`.

**Comment by afandria** [comment]
I forgot to close this; we do distinctly identify the userdata collection by the blessing, though this will need to become automatic in the future.
