### ISSUE TITLE
Syncbase: Collection "invalid name" Error message unclear

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1322]
I attempted to use the "collectionForId" solution to #1320, but hit this error.

`Create: invalid name: v.io:a:xyz,db/dev.v.io:o:608941808256-43vtfndets79kf5hac8ieujto8837660.apps.googleusercontent.com:ttttttttttttttttttttttv@gmail.com,userdata`

The issue with the invalid name is probably that it's too long. `util/util.go` lists the allowed length at 64 (so it seems that our hack of `dev.v.io:u:sam` is able to get away with it by being a much shorter string).

Some suggestions:
- improve error message when the name is invalid (it could be due to invalid character or a length issue)
- increase the length of the allowed name size (or don't include the blessing length in the limit) since 64 is too small

@asadovsky

**Comment by ivanpi-mtv** [comment]
Solved in v.io/c/22198 and v.io/c/22200
Invalid name errors should now be more specific.
Length bumped up as per #1323
