### ISSUE TITLE
Syncbase: App-Blessing + Database-Name combination may be too long

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1323]
@ivanpi-mtv says that the combination is used to define folders on the filesystem. We may want to use a hash since the App-Blessing isn't restricted in length.

**Comment by ivanpi-mtv** [comment]
Solved in v.io/c/22198 and v.io/c/22200
Blessing limit bumped to 1024, hash used in folder name so it can be relaxed further or removed if needed.
