### ISSUE TITLE
syncgroup id hashing security vulnerability

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#1325]
@hpucha @fredquintana @rdvg 
Noticed while reviewing https://vanadium-review.googlesource.com/#/c/21843

Pasting code review comment below:

---

By the way, I think there's a security vulnerability here - a malicious user could potentially create names/blessings that result in a hash collision with some other app.

For example, consider app with dbId={name:"a", blessing:"b"}, sgId={name:"cde", blessing:"f"}

A malicious user could create app with dbId={name:"a", blessing:"bc"}, sgId={name:"d", blessing:"ef"} to create a hash collision without being in control of blessings "b" or "f".

**Comment by hpucha** [comment]
We will use separators for each of the components and hash that string
notation. So this shouldn't be a problem.

**Comment by asadovsky** [comment]
Perhaps I'm missing something, but as far as I can tell this problem still exists in the code - in which case the issue should remain open. (Issues should only be closed when the reported problems have been fixed, or when marking "wontfix".)

Re-opening the issue under the assumption that it was closed accidentally.

**Comment by asadovsky** [comment]
Chatted offline with Bindu. This issue is actually introduced by the CL (https://vanadium-review.googlesource.com/#/c/21843); it didn't exist previously (since previously we'd been using syncgroup names, which were vanadium names).

So, closing this issue, but the problem should be addressed in the CL ( @fredquintana )
