### ISSUE TITLE
TODOs: Invitation ads do not use "visibility" field

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1331]
Related: #1328

Due to the lack of crypter, I cannot put the blessing patterns into the visibility field to avoid the panic.

My workaround is to add these blessing patterns into the ad attributes and have scanners agree to filter based on that. This short-term fix should be replaced, however.

The code isn't committed yet, but the hack is inside io.v.todos.sharing's Sharing.java in the Syncbase build variant.

@afandria @AsturaPhoenix 
@asimshankar  @jhahn21

**Comment by asimshankar** [comment]
CC @mattr-google 

His plan is to hack this out at the lower level for now and I'll get IBE working at some point

**Comment by ghost** [comment]
Slightly off topic: Is the idea to replace your use of discovery with the high level syncbase Invitation API?  Or would this use still be separate?

**Comment by afandria** [comment]
I'm going to replace my use of discovery with the higher-level API, yes.

**Comment by asimshankar** [comment]
Obsolete
