### ISSUE TITLE
memory leak in `store/transaction/manager.trackBatch`

### ISSUE THREAD

**Issue by nlacasse** [vanadium/issues#1338]
The manager in `store/transaction/manager.trackBatch` keeps a queue of events `mg.events`.

Inside `manager.trackBatch` we create a new `committedTransaction` and add it to the queue.  However, we only remove this transaction from the queue on `manager.Close` which happens at shutdown.  Thus, we end up leaking an extra transaction on this queue for every `Put` and `Delete`.

There is a TODO to "do GC" inside this function.

**Comment by nlacasse** [comment]
The `manager.txTable` trie is similarly leaky.  We add keys to it in `manager.trackBatch`, but never remove them.

**Comment by asadovsky** [comment]
@nlacasse I'm pretty busy with API stuff. Do you have cycles to take a stab at fixing these?

For transaction GC, Sergey had an implementation in this CL that we can probably adapt:
https://vanadium-review.googlesource.com/#/c/11967/

(IIRC he did something somewhat fancy, and I think we can get by with something much dumber/simpler to start, but figured it's worth sending the pointer in any case.)

**Comment by nlacasse** [comment]
The implementation in that CL is checked in, and contains the leaks mentioned in this CL, as well as the TODO to fix them.

@asadovsky I'm going to be gone for the next week, but I'm happy to take a look when I get back.

**Comment by asadovsky** [comment]
See intermediate patchsets in the CL. Sergey implemented a somewhat non-trivial GC, I asked for something simpler, he dropped GC entirely and added the TODO.

How big of a problem is this leak? If it's important/critical, I can prioritize fixing it; otherwise perhaps best to save for when you're back.

**Comment by nlacasse** [comment]
Ah, I see.

Not sure of the priority.  It won't block the demo.  The leaks are fairly small, just a few bytes each transaction.

**Comment by nlacasse** [comment]
v.io/c/22797

**Comment by asadovsky** [comment]
Wrong CL number :)

Looks like it should be v.io/c/22780

--Adam

**Comment by nlacasse** [comment]
Yeah.. I got my issues confused.  CL v.io/c/22780 is not yet ready so please hold off on the review.

**Comment by nlacasse** [comment]
v.io/c/22780 has been submitted.
