### ISSUE TITLE
Permission revocation tutorial: revoking doesn't work

### ISSUE THREAD

**Issue by zanesterling** [vanadium/issues#1349]
In the [https://vanadium.github.io/tutorials/security/third-party-caveats.html](Third-party Caveats tutorial) you set up permissions for a user using a third-party caveat. This works fine.
Then at the end of the tutorial, you revoke the user's permissions by configuring the third-party to always reject them.
The revoke step doesn't work: the user permanently has permission-to-access.

**Comment by asimshankar** [comment]
Closing as duplicate of #734 
We've set discharge interval to 24 hours so that the credentials work offline for up to 1 day.

Not sure how to fix the tutorial, but at least I know what the problem is :)

**Comment by caprita** [comment]
For now, may I suggest we just add a disclaimer in the tutorial, explaining exactly what @asimshankar said (that the revocation works, but it takes a day to take effect)? This will prevent confusion among those doing the tutorial.
