### ISSUE TITLE
Vanadium & Syncbase Swift Demos: setup instructions fail (build-cgo)

### ISSUE THREAD

**Issue by ultrasaurus** [vanadium/issues#1352]
https://github.com/vanadium/swift

```
jiri-swift build -project SyncbaseCore build-cgo
```

results in:

```
jiri-swift: command not found
```

I think, perhaps it should be:

```
jiri swift build -project SyncbaseCore build-cgo
```

but that also doesn't work:

```
ERROR: Invalid build stage: build-cgo
```

**Comment by azinman** [comment]
jiri swift build -project SyncbaseCore cgo

:)

I'll fix the docs.

**Comment by azinman** [comment]
You can always do a jiri swift help to learn more.

**Comment by ultrasaurus** [comment]
Thanks.  I actually tried `jiri swift help` but it wasn't actually that helpful...

```
$ jiri swift build help
ERROR: You must set a project -- one of the following (case-insensitive): [VanadiumCore SyncbaseCore]
$ jiri swift build -project SyncbaseCore 
ERROR: -out-dir-swift must be defined if building the framework
```

I didn't know how to figure out that the target (or whatever the last argument is) should be `cgo`

**Comment by azinman** [comment]
Fixed in: https://vanadium-review.googlesource.com/#/c/23035/

**Comment by ultrasaurus** [comment]
confirmed
