### ISSUE TITLE
Unexpected error in VDL Java generation

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#1356]
Attempting to generate Java from VDL with a clean project and clean Vanadium installation using the VDL gradle plugin fails with:

```
13:22:16.269980 util_type.go:178: vdl: javaType unhandled type enum enum{NoRetry;RetryConnection;RetryRefetch;RetryBackoff}
```

Error raised at [util_type.go:178](https://github.com/vanadium/go.ref/blob/master/lib/vdl/codegen/java/util_type.go#L178).
Error raised in response to [builtin.vdl:18-26](https://github.com/vanadium/go.v23/blob/master/vdl/builtin.vdl#L18-L26).

**Comment by tatatodd** [comment]
What command are you actually running?  I don't see any failures on https://veyron.corp.google.com/jenkins/

**Comment by AsturaPhoenix** [comment]
./gradlew vdl, which translates to something like:

```
build/vdltool/vdl-linux generate
    --lang=java
    --java-out-dir=generated-src/transitive-vdl->generated-src/transitive-vdl
    --java-out-pkg=v.io->io/v all
```

with a VDLPATH built from the buildscript classpath.

**Comment by AsturaPhoenix** [comment]
This is using:

```
Gradle: 2.13
com.android.tools.build:gradle:2.1.0
io.v:gradle-plugin:1.7
io.v:vanadium-android:2.1.9
```

**Comment by AsturaPhoenix** [comment]
Upgraded to io.v:vanadium-android:2.2.1; issue is still present.

**Comment by AsturaPhoenix** [comment]
An example repro run in a project where the gradle plug-in has extracted transitive VDL to `app/generated-src/transitive-vdl` and the VDL tool to `app/build/vdltool/vdl-linux`:

```
VDLROOT=app/generated-src/transitive-vdl/v.io/v23/vdlroot \
VDLPATH=app/generated-src/transitive-vdl \
    app/build/vdltool/vdl-linux generate \
        --lang java \
        --java-out-dir=test \
        all
```

Replacing the `all` target with `v.io/v23/vdl` is fine, so that's not the culprit; working on narrowing that down now.

**Comment by AsturaPhoenix** [comment]
The failure is on v.io/v23/vdl/vdltest. Working on further narrowing it down...

**Comment by AsturaPhoenix** [comment]
On the other hand rebuilding the gradle plugin seems to work just fine. I'll just push an update.

**Comment by AsturaPhoenix** [comment]
https://jcenter.bintray.com/io/v/gradle-plugin/1.8/
