### ISSUE TITLE
syncbase: CreateSyncgroup / PublishSyncgroup fails due to canceled context

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1357]
With some help from @suharshs, we have determined that CreateSyncgroup is canceling the context of PublishSyncgroup after it completes.

```
    if spec.PublishSyncbaseName != "" {
        go func() {
            if err := sd.publishSyncgroup(ctx, call, sgId, spec.PublishSyncbaseName); err != nil {
                ss.enqueuePublishSyncgroup(sgId, dbId, true)
            }
        }()
    }
```

It looks like we aren't allowed to do async work with the context of a server call since the contexts aren't meant to live beyond the duration of that call.

We used the "forbidden" `context.WithRootCancel(ctx)` to show that this is indeed the case; publish will succeed with this kind of hack. (The function re-roots any child contexts whose parents have been canceled, thus allowing them to ignore parent cancellations.)

Chatted with @hpucha about the bug and issue created.

Side Note: It's important that syncgroup create publishes the syncgroup because we currently don't act upon the queued up syncgroup publishes.

**Comment by asadovsky** [comment]
Would it be hard to add the code to act upon queued up publishes? If not, perhaps we should just do that, and simply queue up the publish in CreateSyncgroup?
