### ISSUE TITLE
v.io should redirect to vanadium.github.io

### ISSUE THREAD

**Issue by danafergan** [vanadium/issues#1362]
-The v.io website still exists and is out of date. 
-The "Sign in with your Google Account." link from the v.io landing page links to the old site.

I'm not sure where the old landing page code lives, doesn't seem to be in the www or website repos.

**Comment by ultrasaurus** [comment]
would be nice to have v.io just be the new website.  Github pages supports custom domains: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by aghassemi** [comment]
Thanks to @rthellend v.io and staging.v.io now redirect to Github pages. 

@ultrasaurus We looked into custom domains for Github pages, @rthellend pointed out correctly that it does not support HTTPS for custom domains ( https://github.com/isaacs/github/issues/156 ). We can setup our own hosting mirror to host the same content on v.io as well, if redirect is not good enough.

**Comment by ultrasaurus** [comment]
@aghassemi v.io redirects to https://vanadium.github.io/ and @yyoon reports that #1363 is fixed.  Is there more to do here?  or can we close this?

**Comment by aghassemi** [comment]
nope, we can close it.
