### ISSUE TITLE
go get <v.io package> failing

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#1363]
I noticed that madb build is failing on Travic because `go get v.io/x/lib/cmdline` is failing.
https://travis-ci.org/vanadium/madb/builds/138138763

Also, the godoc entry of the same library is not showing up.
https://godoc.org/v.io/x/lib/cmdline

This seems like an unexpected side effect of #1362.
Could we somehow continue to serve go packages under v.io and only redirect the webpage accesses?

@aghassemi @rthellend @nlacasse

**Comment by rthellend** [comment]
I'm going to point v.io back to 104.154.74.157 for now.

**Comment by yyoon** [comment]
Thanks. I can confirm that `go get` is working well now.
