### ISSUE TITLE
Hide "root" WatchChange

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#1373]
As @azinman pointed out, we don't actually need the root WatchChange to be exposed to end users. We use it to guarantee that onInitialState will be called with something. However, we don't actually need to forward this particular watch change to the end user.

That is one way that we can call onInitialState with an empty iterator.

@razvanm

**Comment by azinman** [comment]
Fixed for Swift in [CL 23660](https://vanadium-review.googlesource.com/#/c/23660/), along with a bug that prevented userdata from being observed for watches internally
