### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ethanfrey** [vanadium/issues#1416]
I came across the vanadium project a few months ago and was very impressed with the design and the work that went in. I was playing with some of these concepts before for an app, but this does it in a much more powerful, general way.

However, took a deeper look recently, and saw basically no commits since August 2016.  Is this project on ice?  Or is work continuing, with all the commits somewhere else, waiting to be pushed to github with the next release?

I would just like to know if the project is in active development, before using it for (alpha) software.

**Comment by jeffallen** [comment]
See this email: https://groups.google.com/a/v.io/forum/#!topic/vanadium-discuss/bN3YItlsQ5A
