### ISSUE TITLE
bookmarks widget freeze

### ISSUE THREAD

**Issue by ericJrdn** [vanadium/issues#1422]
When the bookmarks widget of Vanadium is used on the android screen:
- In Vanadium, move a bookmark from a folder to another folder

Result:
- It is not possible to browse bookmarks folders anymore in the widget
- it is not possible to open the bookmarks anymore within Vanadium

**Comment by kevinGC** [comment]
I think you're looking for a different Vanadium, possibly [this one](https://github.com/GrapheneOS/Vanadium).

**Comment by ericJrdn** [comment]
Sorry
Thank you
