### ISSUE TITLE
Completer Scripts: Proposed modifications

### ISSUE THREAD

**Issue by jxson** [vanadium/issues#185]
Based on the feedback we got from @asadovsky, here are a list of potential improvements we can make to the completer scripts moving forward. Let me know what you think.

Short-term
- Exit early if setup fails (usually due to a missing installation); right now, only a printout occurs, which gets buried by the other console output.
- Move to a different directory like $HOME. The completer scripts delete and recreate $TUTDIR ($TMPDIR/vanadium_tutorial); you will get a cryptic error when running a completer script from inside the old $TUTDIR
- Hide stdout from the completer scripts
- Use a better temp directory for Macs.

Long-term
- Add more detailed description about what each completer script does
- split testing scripts and completer scripts; it would be nice if the completer scripts didn't do anything extra like startup/kill Go servers. The testing scripts _should_ still do that though. (I suggest having mdrip parse out an optional flag in the HTML comment to set whether the command should also be part of the completer script)
- potentially make completer scripts download all the code needed for the tutorial. The originally copy-to-clipboard code blocks would become normal code blocks. Copy-to-clipboard would only remain for commands like `browserify`, `principal`, and `vdl`

@afandria @bprosnitz @jxson @monopole

**Comment by monopole** [comment]
project on hiatus
