### ISSUE TITLE
glob no longer prints endpoints

### ISSUE THREAD

**Issue by nlacasse** [vanadium/issues#265]
Now that #1804 is fixed, the corresponding sentence in the tutorial needs to be updated. 'glob' no longer prints endpoints.

https://staging.v.io/tutorials/naming/namespace.html#namespace-construction
"This shows television, meters, meters/gas and meters/electric along with endpoints."

I'm not sure if there are other places affected by this.

**Comment by monopole** [comment]
project on hiatus
