### ISSUE TITLE
Clear up tutorial's comments on how 'principal' creates 1stparty caveats

### ISSUE THREAD

**Issue by nlacasse** [vanadium/issues#276]
See text at "Currently, the principal command-line tool only supports creation of

At one point the api required at least one caveat, and the only cav the principal program could make was a duration caveat - which influenced the description referred to above.

@asimshankar claims arb caveats can be specified via the principal tool.

Probably just want to remove words at this point.

The API still does require one caveat (or an explicit --require_caveats=false flag), and duration is still special cased with the --for flag, but yeah, the tool does support arbitrary ones

**Comment by monopole** [comment]
project on hiatus
