### ISSUE TITLE
Have a single function that grabs the info from the context that needs to be passed to other address spaces

### ISSUE THREAD

**Issue by bjornick** [vanadium/issues#366]
Right now, there is only one (?) item from the context that the rpc system passes on the wire as part of the rpc protocol.  Other language bindings (i.e JS) need to pass this information to/from the go address space as well.  To avoid skews in the future, we should consolidate this logic in one place, so we can share it between the rpc system and the language bindings.

**Comment by ghost** [comment]
This has not been a real problem in practice.  I'm closing.
