### ISSUE TITLE
Use bidirectional RPC instead of a proxy in the `install-local` command

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#387]
As a fix for #33, https://vanadium-review.googlesource.com/#/c/10622/ added access control to the proxy.

During that, I realized that the device manager starts up a proxy for bootstrapping in `startClaimedDevice`. Revisit that choice.

FYI @caprita

**Comment by asimshankar** [comment]
This original concern is no longer valid given the RPC2 rollout which had bidi. Changing the title and reassigning to @suharshs so that he can change the device manager code to use bidi with the new RPC system.

**Comment by suharshs** [comment]
https://vanadium-review.googlesource.com/#/c/18140/2

**Comment by suharshs** [comment]
This has been submitted.
