### ISSUE TITLE
Steps of third party caveats tutorial could be more clearly connected to the scenario it demonstrates

### ISSUE THREAD

**Issue by lnizix** [vanadium/issues#406]
Two suggested places where you can remind the reader how the steps relate to the larger scenario:
1. Where it says: "As mentioned above, CheapDrive is going to run a server, and various clients will try to use it" -- Rather than various clients, perhaps it's more useful to say that Alice is going to use it to become authenticated so that she can see your documents (tying it back to the whole scenario).
2. Where it says: "Instead, CheapDrive will configure, via a command line flag, a Permissions Authorizer that allows a specific Google user (you) to securely access CheapDrive's service." -- Again, you might complete the thought about why you're doing this in service of giving Alice access to your documents.

**Comment by monopole** [comment]
project on hiatus
