### ISSUE TITLE
VDL tool: user-defined arg named "opts" conflicts with auto-generated opts ...rpc.CallOpt

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#420]
We should probably reserve a less commonly used word than opts for the auto-generated `opts ...rpc.CallOpt` but at least we should have the VDL tool error if user defines an argument named `args` (Currently VDL tool succeeds and the Go compiler complains about duplicate args in the generated code)

**Comment by tatatodd** [comment]
I just noticed this bug, and I'm fixing the same issue reported in #912

**Comment by aghassemi** [comment]
Cool. Thanks
