### ISSUE TITLE
Each vc message is sent as multiple websocket messages

### ISSUE THREAD

**Issue by bjornick** [vanadium/issues#453]
Right now, it looks like for each message we send on a stream at the vc layer is done with multiple writes.  This is fine when the stream is a tcp stream.  When the underlying stream is backed by websocket, this results in creating a websocket message for each write.  This results in extra framing, and it shows up in the performance trace in chrome.  It looks like each websocket message from the extension results in a separate message to chrome browser process.  The net result is that writing a 1K message takes 2ms to get out of chrome.  This is about 10% of the latency of an rpc in javascript.

There are two ways to fix this.  The long term solution seems to be have the abstraction layer for protocol be at the message level instead of the stream level.  A short term solution would be to try to batch small writes in the websocket writer.  

@tatatodd @jhahn21

**Comment by suharshs** [comment]
This has been fixed in RPC2.
