### ISSUE TITLE
www test failures may not cleanup background processes

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#466]
When one step in a www test fails, the test stops running immediately. This is usually good, but it also means that some background processes may not be cleaned up. We should add this capability.

Examples of possible background processes
- Go Fortune server
- node static web server

Fixing this may require modifying `mdrip`. For example, an "always" tag could be used to mark commands that should always be run. This tag would then be used to allow cleanup steps to always complete.

@afandria @bprosnitz

**Comment by monopole** [comment]
project on hiatus
