### ISSUE TITLE
Change the namespace timeout to be configurable and attached to the context

### ISSUE THREAD

**Issue by mattr-google** [vanadium/issues#472]
Right now the namespace library has a fixed 30 second timeout if the user doesn't specify a timeout and no timeout otherwise.

We would like more flexibility.  One way to achieve this is to add:

func naming.WithNamespaceTimeout(ctx *context.T, time.Duration) *context.T

If the user has this set the namespace routines will (if there is no deadline) do:

ctx, cancel = context.WithTimeout(ctx, naming.GetNamespaceTimeout(ctx))
defer cancel()

// Do naming operation here.

I'm planning to make this change.

@presotto @cosnicolaou

**Comment by ghost** [comment]
This never came up again.  For now if someone wants this level of control, they can resolve a name manually before making an RPC call.
