### ISSUE TITLE
Sign the public key along with the channel-binding during authentication

### ISSUE THREAD

**Issue by ankurtaly** [vanadium/issues#542]
Dan Boneh (crypto expert, Professor at Stanford) suggested changing our authentication protocol so that each end also signs the public key along with the channel-binding. In general, it is considered good crypto hygiene to always include the public key in the signature. At the least, it strengthens the non-repudiation properties of the signature as the signature commits to a public key.

**Comment by asimshankar** [comment]
Duplicate of #619
