### ISSUE TITLE
Use vbecome everywhere, remove vrun

### ISSUE THREAD

**Issue by tatatodd** [vanadium/issues#566]
@mattr-google @caprita @asimshankar @suharshs 

Matt showed me how to enable vtrace when running commands, and it's really useful.  But there's some issue where vtrace isn't useful when using vrun, and vbecome solves that problem.  I don't know the details.

Either way, we should probably get rid of vrun, and use vbecome everywhere.

**Comment by ghost** [comment]
Vrun is gone.
