### ISSUE TITLE
publisher.Status blocks

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#568]
Summary of discussion with @tatatodd 

Currently, the way the publisher's runLoop is written, all commands that come on cmdChan are serialized. Since some of these commands can block (e.g. mount), the status command may be backlogged behind such commands and hang.

We probably want to preserve the serial nature of mount/unmount operations (at least against the same mounttable), but perhaps these could be done asynchronously s.t. the respective AddServer/AddName/RemoveServer/RemoveName API calls return right away. More to the point, Status should never block and return the current state of the publisher.

We should strongly consider rewriting the publisher to use locks rather than the more restrictive goroutine/channel approach.

**Comment by tatatodd** [comment]
@suharshs fixed this with https://vanadium-review.googlesource.com/#/q/topic:suharshs-publisher
