### ISSUE TITLE
Race in TestDeviceManagerClaim

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#593]
@rjkroege @caprita @rthellend 

vanadium-go-race is failing:

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/14/console
https://veyron.corp.google.com/jenkins/job/vanadium-go-race/OS=linux,P=2/18/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_perms/TestDeviceManagerClaim_4__GoRace___linux_amd64_/

This suggests a race somewhere in device manager:

        ---- Shell Cleanup ----
---- Cleanup calling Shutdown on program "impl/utiltest/modules.go:56 DeviceManager"
dm terminated
I0708 18:20:28.253224   27517 starter.go:193] Unclaimed device manager (/@5@tcp@127.0.0.1:57357@074b8a2c3c8dbb92130ac983a414b4fb@s@root/ctx/child@@) with public_key: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjPpXOLP2TD2DWDjU_99OoFANwSQr4AhhyUvpmZWrP9mYHhTX6rpBZiBkTR4yeSGbv9zBOkWy6OfxkX0lfkYLyw==
I0708 18:20:28.274735   27517 helpers.go:740] Changing namespace roots from [/@5@wsh@127.0.0.1:45692@234e5ada2a2ca29d93639decf7b89d54@m@root/ctx/child@@] to [/@5@wsh@127.0.0.1:45692@234e5ada2a2ca29d93639decf7b89d54@m@@@]
I0708 18:20:36.780835   27517 claim.go:92] Device claimed and Permissions set to: map[Debug:{[root/$ root/claimant/$ root/claimant/mydevice/$] []} Resolve:{[root/$ root/claimant/$ root/claimant/mydevice/$] []} Admin:{[root/$ root/claimant/$ root/claimant/mydevice/$] []} Read:{[root/$ root/claimant/$ root/claimant/mydevice/$] []} Write:{[root/$ root/claimant/$ root/claimant/mydevice/$] []}]
I0708 18:20:36.782290   27517 starter.go:163] Stopping claimable server...
I0708 18:20:36.790591   27517 starter.go:165] Stopped claimable server.
I0708 18:20:36.793823   27517 servers.go:41] Mount table service at: "" endpoint: /@5@tcp@127.0.0.1:59363@16b704468fbae8cf9929f4dfe1d4cd68@m@root/claimant/mydevice@@
I0708 18:20:36.793907   27517 starter.go:299] Local mounttable (/@5@tcp@127.0.0.1:59363@16b704468fbae8cf9929f4dfe1d4cd68@m@root/claimant/mydevice@@) published as ""
I0708 18:20:36.796311   27517 starter.go:351] Device manager (/@5@tcp@127.0.0.1:34934@42edabd79f2c75b6dee31f86c31f444a@s@root/claimant/mydevice@@) published as dm
E0708 18:20:51.648128   27517 helper_manager.go:136] failed calling helper with args ([--chown --username veyron /home/veyron/tmp/vanadium-go-race/270856886/devicemanager487496919/app-mOhoGvjp1lPhISJUM1OyUQ/installation-20150709-01:20:40.5042/instances/instance-20150709-01:20:49.3616]):exit status 255
E0708 18:20:55.283821   27517 app_starting_util.go:65] AppWatcher was stopped
I0708 18:20:57.970568   27517 starter.go:342] Stopping device server...
I0708 18:20:57.995440   27517 starter.go:345] Stopped device.
I0708 18:20:57.995513   27517 starter.go:302] Stopping mounttable...
I0708 18:20:57.996531   27517 starter.go:304] Stopped mounttable.
---- Shutdown on program "impl/utiltest/modules.go:56 DeviceManager": done
---- Cleanup calling Shutdown on program "internal/servicetest/modules.go:53 rootMT"
MT_NAME=/@5@tcp@127.0.0.1:60202@234e5ada2a2ca29d93639decf7b89d54@m@root/ctx/child@@
---- Shutdown on program "internal/servicetest/modules.go:53 rootMT": done
---- Cleanup calling cancelCtx ----
---- Shell Cleanup Complete ----
	<autogenerated>:29: <autogenerated>:7: ExpectVar: PID=27330
	<autogenerated>:28: <autogenerated>:7 ExpectVar: PID=27330
	<autogenerated>:29: <autogenerated>:7: ExpectVar: MT_NAME=/@5@wsh@127.0.0.1:45692@234e5ada2a2ca29d93639decf7b89d54@m@root/ctx/child@@
	<autogenerated>:28: <autogenerated>:7 ExpectVar: MT_NAME=/@5@wsh@127.0.0.1:45692@234e5ada2a2ca29d93639decf7b89d54@m@root/ctx/child@@
	<autogenerated>:29: <autogenerated>:4: ExpectRE: ready:27517
	<autogenerated>:28: <autogenerated>:4 ExpectRE: ready:27517
	helpers.go:160: Resolve(trapp) expected 1 result(s), got 0 instead
	modules.go:184: You can examine the devicemanager workspace at /home/veyron/tmp/vanadium-go-race/270856886/devicemanager487496919

**Comment by ghost** [comment]
I'm assuming this is no longer relevant?

**Comment by caprita** [comment]
I haven't seen this particular failure in a while. I'm going to optimistically assume that https://vanadium-review.googlesource.com/#/c/16313/ fixed this as well.
