### ISSUE TITLE
Inconsistent vrun role blessings

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#597]
@asimshankar @caprita @rthellend @jinjingforever 
(assigned to Asim for triage)

I was somewhat surprised to see that the structure of the blessing obtained via vrun depends on the role requested:

sadovsky@eve4 (dev.v.io/u/sadovsky@google.com):~ $ ${V23_ROOT}/release/go/bin/vrun --role=**identity/role/vprod/publisher**
sadovsky@eve4 (**dev.v.io/role/vprod/publisher**):~ $ exit
sadovsky@eve4 (dev.v.io/u/sadovsky@google.com):~ $ ${V23_ROOT}/release/go/bin/vrun --role=**identity/role/vprod/admin**
sadovsky@eve4 (**dev.v.io/role/vprod/admin/dev.v.io/u/sadovsky@google.com**):~ $ exit
sadovsky@eve4 (dev.v.io/u/sadovsky@google.com):~ $ 

I assume this is expected and by design, but it violates the principle of least surprise.
Is there a good reason not to have the granted publisher blessing be

**dev.v.io/role/vprod/publisher/dev.v.io/u/sadovsky@google.com**

thus making it consistent with the admin blessing, and providing a stronger audit trail?

**Comment by asimshankar** [comment]
Closing this out as no further action is intended
