### ISSUE TITLE
Tutorial script truncates pids - kill_tut_process()

### ISSUE THREAD

**Issue by jlizakowski** [vanadium/issues#598]
##### Minor issue:

The Hello World kill_tut_process() function doesn't work on Mac OSX 10.9.5 / Bash 3.2.  It truncates the PID.  
##### Symptom

```
bash-3.2$ kill_tut_process $TUT_PID_SERVER 
bash: kill: (6363) - No such process
bash: unset: `56363': not a valid identifier
```
##### Cause:

\$$1 eats the first digit of the pid, and replaces it with another parameter

Example:  $1 is 34567, and $3 is empty.
\$$1 evaluates to ($3)4567, which evaluates to 4567, resulting in truncation. 

```
function kill_tut_process() {
  eval local pid=\$$1
  if [ -n "$pid" ]; then
    kill $pid || true;
    eval unset $1
  fi
}
```
##### Test

```
bash-3.2$ kill_tut_process 34567 foo bar
bash: kill: bar4567: arguments must be process or job IDs
bash: unset: `34567': not a valid identifier
```
##### Diff

https://v.io/tutorials/hello-world.html

```
39c39
<   eval local pid=\$$1

---
>   eval local pid=$1
```

Similar but different than: #351

**Comment by monopole** [comment]
project on hiatus
