### ISSUE TITLE
TestV23DeviceManagerMultiUser test flaky

### ISSUE THREAD

**Issue by rthellend** [vanadium/issues#608]
https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Fservices%2Fdevice&job=vanadium-integration-test&n=8758&os=linux&part=0&suite=v.io%2Fx%2Fref%2Fservices%2Fdevice&test=TestV23DeviceManagerMultiUser-4+%5BV23Test+-+linux%2Camd64%5D&type=presubmit

Presubmit #8758 Test Details

OS	linux
Arch	amd64
Job	vanadium-integration-test
Suite	v.io/x/ref/services/device
Test	TestV23DeviceManagerMultiUser-4 [V23Test - linux,amd64]

Back to Summary 
Console Log
FAIL

Failures:

error: 
        I0713 10:44:35.985345   11540 v23tests.go:537] created root principal: &{0xc2093c5100 0xc20a439f80 0xc20a014bd0}
I0713 10:44:35.985967   11540 v23tests.go:507] mgmt_v23_test.go:119: created temporary directory at /tmp/879324958
I0713 10:44:36.027945   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/cmd/namespace []
I0713 10:44:36.027982   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/cmd/namespace, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace in 43.039µs.
I0713 10:44:36.028023   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/device/device []
I0713 10:44:36.028049   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/device/device, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/device in 44.452µs.
I0713 10:44:36.028072   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/binary/binaryd []
I0713 10:44:36.028096   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/binary/binaryd, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/binaryd in 27.948µs.
I0713 10:44:36.028119   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/application/applicationd []
I0713 10:44:36.028157   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/application/applicationd, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/applicationd in 42.4µs.
I0713 10:44:36.069387   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/debug/debug []
I0713 10:44:36.069421   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/debug/debug, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/debug in 42.523µs.
I0713 10:44:36.192086   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/application/application []
I0713 10:44:36.192130   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/application/application, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/application in 62.742µs.
I0713 10:44:36.192168   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/binary/binary []
I0713 10:44:36.192188   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/binary/binary, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/binary in 39.172µs.
I0713 10:44:36.192227   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/mounttable/mounttabled []
I0713 10:44:36.192247   11540 v23tests.go:472] v23tests.go:454: using v.io/x/ref/services/mounttable/mounttabled, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/mounttabled in 27.074µs.
I0713 10:44:36.192264   11540 binary.go:60] mgmt_v23_test.go:196: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/mounttabled --v23.tcp.address=127.0.0.1:0
I0713 10:44:36.330769   11540 binary.go:78] started PID 16599
I0713 10:44:36.350422   11540 v23tests.go:646] Running root mount table: "/@5@wsh@127.0.0.1:49661@0a9f5db147b5bb329c35e25b24bc1ce6@m@root/child@@"
I0713 10:44:36.350456   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/device/deviced []
I0713 10:44:36.350482   11540 v23tests.go:472] v23tests.go:441: using v.io/x/ref/services/device/deviced, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/deviced in 35.172µs.
I0713 10:44:36.350510   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/agent/agentd []
I0713 10:44:36.350527   11540 v23tests.go:472] v23tests.go:441: using v.io/x/ref/services/agent/agentd, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/agentd in 23.445µs.
I0713 10:44:36.350543   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/device/suidhelper []
I0713 10:44:36.350560   11540 v23tests.go:472] v23tests.go:441: using v.io/x/ref/services/device/suidhelper, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/suidhelper in 20.957µs.
I0713 10:44:36.350575   11540 v23tests.go:591] buildPkg: /home/veyron/tmp/vanadium-integration-test/366104174/bin .. v.io/x/ref/services/device/inithelper []
I0713 10:44:36.350590   11540 v23tests.go:472] v23tests.go:441: using v.io/x/ref/services/device/inithelper, from /home/veyron/tmp/vanadium-integration-test/366104174/bin/inithelper in 19.254µs.
I0713 10:44:36.350609   11540 binary.go:60] mgmt_v23_test.go:543: starting /bin/cp /home/veyron/tmp/vanadium-integration-test/366104174/bin/deviced /home/veyron/tmp/vanadium-integration-test/366104174/bin/agentd /home/veyron/tmp/vanadium-integration-test/366104174/bin/suidhelper /home/veyron/tmp/vanadium-integration-test/366104174/bin/inithelper /tmp/879324958/bin
I0713 10:44:36.357047   11540 binary.go:78] started PID 16606
I0713 10:44:36.413715   11540 binary.go:60] mgmt_v23_test.go:226: starting ./devicex install /tmp/879324958/bin --devuser=devicemanager --origin=applications/deviced/test -- --v23.tcp.address=127.0.0.1:0 --neighborhood-name=jenkins-node11-11540-5836132028126406468
I0713 10:44:36.417992   11540 binary.go:78] started PID 16627
Fetching binaries: deviced suidhelper agentd inithelper locally from: /tmp/879324958/bin ...
Binaries are in /tmp/879324958/dm/bin.
Configuring helpers ...
Helpers configured.
Installing device manager under /tmp/879324958/dm ...
V23_DEVICE_DIR=/tmp/879324958/dm
Device manager installed.
I0713 10:44:36.939222   11540 binary.go:60] mgmt_v23_test.go:227: starting ./devicex start
I0713 10:44:36.943515   11540 binary.go:78] started PID 16697
I0713 10:44:38.010037   11540 binary.go:60] mgmt_v23_test.go:257: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/device claim /@5@wsh@127.0.0.1:39417@7cbc6ff16763d6eab294137281201631@s@agent_principal@@ myworkstation
I0713 10:44:38.057201   11540 binary.go:78] started PID 16736
I0713 10:44:38.057267   11540 binary.go:60] mgmt_v23_test.go:263: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace resolve devices/jenkins-node11
I0713 10:44:38.129215   11540 binary.go:78] started PID 16741
I0713 10:44:38.239027   11540 listener.go:53] Listener being closed: 0xc2081ae098, 0xc2081e9bd0
I0713 10:44:38.235815   16741 impl.go:217] ns.Resolve("devices/jenkins-node11") failed: mounttabled "devices/jenkins-node11".ResolveStep Name devices/jenkins-node11 doesn't exist 
ERROR: mounttabled "devices/jenkins-node11".ResolveStep Name devices/jenkins-node11 doesn't exist 
I0713 10:44:38.344990   11540 binary.go:60] mgmt_v23_test.go:263: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace resolve devices/jenkins-node11
I0713 10:44:38.359734   11540 listener.go:53] Listener being closed: 0xc2099ea2e8, 0xc20819a410
I0713 10:44:38.420357   11540 binary.go:78] started PID 16747
I0713 10:44:38.524101   11540 listener.go:53] Listener being closed: 0xc20810a470, 0xc208202a00
I0713 10:44:38.521506   16747 impl.go:217] ns.Resolve("devices/jenkins-node11") failed: mounttabled "devices/jenkins-node11".ResolveStep Name devices/jenkins-node11 doesn't exist 
ERROR: mounttabled "devices/jenkins-node11".ResolveStep Name devices/jenkins-node11 doesn't exist 
I0713 10:44:38.632979   11540 binary.go:60] mgmt_v23_test.go:263: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace resolve devices/jenkins-node11
I0713 10:44:38.693842   11540 binary.go:78] started PID 16757
I0713 10:44:38.821507   11540 listener.go:53] Listener being closed: 0xc2099ea380, 0xc20a4826e0
I0713 10:44:38.822797   11540 binary.go:60] mgmt_v23_test.go:277: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/device acl set devices/jenkins-node11/devmgr/device root/u/alice Read,Resolve,Write
I0713 10:44:38.867945   11540 binary.go:78] started PID 16762
I0713 10:44:39.292094   11540 listener.go:53] Listener being closed: 0xc208036980, 0xc20a272140
I0713 10:44:39.293678   11540 binary.go:60] mgmt_v23_test.go:280: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/device associate add devices/jenkins-node11/devmgr/device vana root/u/alice
I0713 10:44:39.346849   11540 binary.go:78] started PID 16791
I0713 10:44:39.346909   11540 binary.go:60] mgmt_v23_test.go:282: starting /home/veyron/tmp/vanadium-integration-test/366104174/bin/device associate list devices/jenkins-node11/devmgr/device
I0713 10:44:39.395641   11540 binary.go:78] started PID 16796
I0713 10:44:39.877860   11540 listener.go:53] Listener being closed: 0xc2099ea1e8, 0xc20a7d7180
--------------- SHUTDOWN ---------------
I0713 10:44:39.881909   11540 listener.go:53] Listener being closed: 0xc2081ae838, 0xc2083be7d0
Successfully claimed.
I0713 10:44:39.884423   11540 listener.go:53] Listener being closed: 0xc20810a2b0, 0xc20a60aa00
I0713 10:44:36.348853   16599 servers.go:41] Mount table service at: "" endpoint: /@5@wsh@127.0.0.1:49661@0a9f5db147b5bb329c35e25b24bc1ce6@m@root/child@@
I0713 10:44:38.240696   16599 listener.go:53] Listener being closed: 0xc2080504e8, 0xc2080b2730
I0713 10:44:38.523388   16599 listener.go:53] Listener being closed: 0xc2080504a8, 0xc208232d70
I0713 10:44:38.820695   16599 listener.go:53] Listener being closed: 0xc2080505b0, 0xc20815abe0
I0713 10:44:39.290310   16599 listener.go:53] Listener being closed: 0xc208050688, 0xc2082161e0
I0713 10:44:39.866597   16599 listener.go:53] Listener being closed: 0xc208050358, 0xc208200870
I0713 10:44:39.881367   16599 listener.go:53] Listener being closed: 0xc2080507a8, 0xc208279270
I0713 10:44:39.882762   16599 mounttable.go:56] Received signal terminated
I0713 10:44:39.883256   16599 listener.go:53] Listener being closed: 0xc208050670, 0xc208216370
---- Shell Cleanup ----
---- Cleanup calling cancelCtx ----
---- Shell Cleanup Complete ----
I0713 10:44:39.890839   11540 v23tests.go:294] V23Test.Cleanup: cleaning up /tmp/879324958
I0713 10:44:39.891406   11540 listener.go:53] Listener being closed: 0xc2099eba28, 0xc20a3af9f0
I0713 10:44:39.895768   11540 listener.go:53] Listener being closed: 0xc2080362c8, 0xc20a66b090
I0713 10:44:39.896253   11540 listener.go:53] Listener being closed: 0xc208036440, 0xc20a56e690
I0713 10:44:39.896782   11540 listener.go:53] Listener being closed: 0xc2099ebf78, 0xc20a595180
E0713 10:44:39.904451   11540 v23tests.go:296] WARNING: RemoveAll("/tmp/879324958") failed: open /tmp/879324958/dm: permission denied
	expect.go:122: v23tests.go:644: ExpectVar: NAME=/@5@wsh@127.0.0.1:49661@0a9f5db147b5bb329c35e25b24bc1ce6@m@root/child@@
	expect.go:123: v23tests.go:644 ExpectVar: NAME=/@5@wsh@127.0.0.1:49661@0a9f5db147b5bb329c35e25b24bc1ce6@m@root/child@@
	mgmt_v23_test.go:239: Couldn't read log /tmp/879324958/dm/dmroot/device-manager/logs/deviced.INFO: open /tmp/879324958/dm/dmroot/device-manager/logs/deviced.INFO: no such file or directory
	mgmt_v23_test.go:284: association test, got , expected root/u/alice vana
	v23tests.go:252: 0: /home/veyron/tmp/vanadium-integration-test/366104174/bin/mounttabled: shutdown status: has not been shutdown
	v23tests.go:252: 4: /home/veyron/tmp/vanadium-integration-test/366104174/bin/device: shutdown status: has not been shutdown
	v23tests.go:252: 5: /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace: shutdown status: exit status 1
	v23tests.go:252: 6: /home/veyron/tmp/vanadium-integration-test/366104174/bin/namespace: shutdown status: exit status 1
	v23tests.go:252: 9: /home/veyron/tmp/vanadium-integration-test/366104174/bin/device: shutdown status: has not been shutdown
	v23tests.go:252: 10: /home/veyron/tmp/vanadium-integration-test/366104174/bin/device: shutdown status: has not been shutdown

**Comment by caprita** [comment]
(Hopefully) fixed by https://vanadium-review.googlesource.com/#/c/17002/
