### ISSUE TITLE
v.io/x/ref/runtime/internal/rpc/test failure

### ISSUE THREAD

**Issue by jsimsa** [vanadium/issues#637]
I have seen the TestStreamAbort test fail with the following stack trace:

=== RUN TestStreamAbort-6
panic: Calling v23 method during runtime initialization.  You cannot
call v23 methods until after the runtime has been constructed.  You may
be able to move the offending caller to the Runtime.Init() method of your
runtime implementation.

goroutine 2636 [running]:
v.io/v23.(*initStateData).currentRuntime(0x1c36ce0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/model.go:320 +0x153
v.io/v23.GetPrincipal(0xc2084f8a80, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/model.go:232 +0x5a
v.io/x/ref/runtime/internal/rpc/stream.GetPrincipalVCOpts(0xc2084f8a80, 0xc208361fb0, 0x3, 0x3, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/util.go:28 +0x1b9
v.io/x/ref/runtime/internal/rpc/stream/vif.(*VIF).Dial(0xc2086e4000, 0xc2084f8a80, 0x7f1f0e8c6008, 0xc2086da5f0, 0xc208361fb0, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:331 +0x1f4
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).Dial(0xc20810ccd0, 0xc2084f8a80, 0x7f1f0e8c6008, 0xc2086da5f0, 0xc208361fb0, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:173 +0x394
v.io/x/ref/runtime/internal/rpc.(*client).createFlow(0xc20822a900, 0xc2084f8a80, 0x7f1f0e8be5a0, 0xc208711d70, 0x7f1f0e8c6008, 0xc2086da5f0, 0xc2087333a0, 0x2, 0x2, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:152 +0x470
v.io/x/ref/runtime/internal/rpc.(*client).tryCreateFlow(0xc20822a900, 0xc2084f8a80, 0x7f1f0e8be5a0, 0xc208711d70, 0x0, 0xc2089be820, 0x4a, 0xc2089be9b0, 0x4a, 0xcd3b10, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:378 +0xad8
created by v.io/x/ref/runtime/internal/rpc.(*client).tryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:488 +0x12ef

goroutine 1 [chan receive]:
testing.RunTests(0xe6e4a0, 0x1295ec0, 0x1d, 0x1d, 0x51ab01)
	/usr/local/google/home/veyron/go/src/testing/testing.go:556 +0xdc3
testing.(*M).Run(0xc208059310, 0xc208059310)
	/usr/local/google/home/veyron/go/src/testing/testing.go:485 +0xe1
v.io/x/ref/runtime/internal/rpc/test.TestMain(0xc208059310)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/test/v23_internal_test.go:21 +0x40
main.main()
	v.io/x/ref/runtime/internal/rpc/test/_test/_testmain.go:106 +0x28d

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/google/home/veyron/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/cosnicolaou/llog.(*Log).flushDaemon(0xc20807a000)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:1027 +0x99
created by github.com/cosnicolaou/llog.NewLogger
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/third_party/go/src/github.com/cosnicolaou/llog/glog.go:546 +0x510

goroutine 7 [sleep]:
v.io/x/ref/lib/stats/sysstats.func��005()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/lib/stats/sysstats/sysstats.go:77 +0x44
created by v.io/x/ref/lib/stats/sysstats.exportMemStats
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/lib/stats/sysstats/sysstats.go:80 +0x449

goroutine 8 [syscall, 1 minutes]:
os/signal.loop()
	/usr/local/google/home/veyron/go/src/os/signal/signal_unix.go:21 +0x2d
created by os/signal.init��1
	/usr/local/google/home/veyron/go/src/os/signal/signal_unix.go:27 +0x43

goroutine 1373 [semacquire]:
sync.(*Cond).Wait(0xc2083657c0)
	/usr/local/google/home/veyron/go/src/sync/cond.go:62 +0xb6
v.io/x/ref/runtime/internal/rpc/stream/vif.(*Set).BlockingFind(0xc208365740, 0xce10f0, 0x3, 0xc20839a540, 0x11, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/set.go:56 +0x493
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).FindOrDialVIF(0xc2088fd6d0, 0xc208860a00, 0x7f1f0e8c6008, 0xc20884e1e0, 0xc20839a140, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:141 +0x378
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).Dial(0xc2088fd6d0, 0xc208860a00, 0x7f1f0e8c6008, 0xc20884e1e0, 0xc20839a140, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:168 +0xc7
v.io/x/ref/runtime/internal/rpc.(*client).createFlow(0xc208516d80, 0xc208860a00, 0x7f1f0e8be5a0, 0xc2086f7ad0, 0x7f1f0e8c6008, 0xc20884e1e0, 0xc20839a140, 0x2, 0x2, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:152 +0x470
v.io/x/ref/runtime/internal/rpc.(*client).tryCreateFlow(0xc208516d80, 0xc208860a00, 0x7f1f0e8be5a0, 0xc2086f7ad0, 0x0, 0xc2089fbf20, 0x1e, 0xc20839a0e0, 0x1e, 0xcdd550, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:378 +0xad8
created by v.io/x/ref/runtime/internal/rpc.(*client).tryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:488 +0x12ef

goroutine 2599 [runnable]:
v.io/x/ref/runtime/internal/rt.(*Runtime).WithNewStreamManager(0xc2088045b0, 0xc208425040, 0x7f1f0e8be5a0, 0xc20880ade0, 0xe6f0d8)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:310
v.io/x/ref/runtime/internal/rt.Init(0xc208424780, 0x7f1f0e8be108, 0xc208678d20, 0x0, 0x0, 0x0, 0xc2084247c0, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:168 +0x16fa
v.io/x/ref/runtime/factories/generic.Init(0xc208424780, 0x0, 0x0, 0x4382bb, 0xc20818c940, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/factories/generic/generic.go:56 +0x47c
v.io/v23.Init(0x68f2c7, 0x2)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/model.go:437 +0x57f
v.io/x/ref/test.initWithParams(0xd70101, 0x24, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/test/init.go:91 +0x3b
v.io/x/ref/test.V23Init(0x48c2b4, 0x464d1b)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/test/init.go:78 +0x77
v.io/x/ref/runtime/internal/rpc/test.TestStreamAbort(0xc2087e6000)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/test/client_test.go:716 +0x3b
testing.tRunner(0xc2087e6000, 0x1295ff8)
	/usr/local/google/home/veyron/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/google/home/veyron/go/src/testing/testing.go:555 +0xd4e

goroutine 2614 [runnable]:
v.io/v23/vom.hasBinaryMsgLen(0xc2081789a0, 0xc2086812c0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/vom/binary_util.go:41
v.io/v23/vom.(*Decoder).decodeValueMsg(0xc2088b0fa0, 0xc2081789a0, 0xc394c0, 0xc2086812c0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/vom/decoder.go:241 +0x10b
v.io/v23/vom.(*Decoder).Decode(0xc2088b0fa0, 0xc394c0, 0xc2086812c0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/vom/decoder.go:102 +0x36f
v.io/x/ref/runtime/internal/rpc/stream/vc.readBlessings(0x7f1f0e8d1c70, 0xc2084f8d00, 0x1298418, 0x8, 0x8, 0x7f1f0e8c7fd8, 0xc208733fc0, 0x7f1f0000000b, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vc/auth.go:145 +0x70b
v.io/x/ref/runtime/internal/rpc/stream/vc.AuthenticateAsServer(0x7f1f0e8d1c38, 0xc2084f8d00, 0x7f1f0e8c7fd8, 0xc208733fc0, 0x7f1f0000000b, 0x7f1f0e8be5a0, 0xc208711d70, 0xc2089c44e0, 0x1, 0x1, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vc/auth.go:58 +0x59d
v.io/x/ref/runtime/internal/rpc/stream/vif.AuthenticateAsServer(0x7f1f0e8d1bc0, 0xc2081520d0, 0xc208198b10, 0x7f1f0e8c6008, 0xc2086da780, 0x1298420, 0x7f1f0e8be5a0, 0xc208711d70, 0xc2089c44e0, 0x1, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/auth.go:238 +0x1115
v.io/x/ref/runtime/internal/rpc/stream/vif.InternalNewAcceptedVIF(0xc208861b00, 0x7f1f0e8d1ac0, 0xc2081520d0, 0xf46515c14868629e, 0xfc1989543c263b1d, 0xc2089c44e0, 0x1, 0x1, 0x7f1f0e8be480, 0xc20876a7a0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:235 +0x38b
v.io/x/ref/runtime/internal/rpc/stream/manager.func��003()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/listener.go:210 +0x22c
created by v.io/x/ref/runtime/internal/rpc/stream/manager.(*netListener).netAcceptLoop
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/listener.go:225 +0xfba

goroutine 2637 [runnable]:
v.io/x/ref/runtime/internal/rpc.cleanupTryCall(0x0, 0xc20876a468, 0x1, 0x1, 0xc208598960)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:612 +0x10a
created by v.io/x/ref/runtime/internal/rpc.(*client).failedTryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:622 +0xc0

goroutine 1374 [chan receive]:
v.io/x/ref/runtime/internal/rpc.cleanupTryCall(0x0, 0xc20818c078, 0x1, 0x1, 0xc2085c07e0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:612 +0x10a
created by v.io/x/ref/runtime/internal/rpc.(*client).failedTryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:622 +0xc0

goroutine 2574 [runnable]:
v.io/x/ref/runtime/internal/rpc/stream/vif.(*VIF).readLoop(0xc2086e4000)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:631
created by v.io/x/ref/runtime/internal/rpc/stream/vif.internalNew
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:316 +0x1653

goroutine 2601 [chan receive]:
v.io/x/ref/runtime/internal/rt.func��003()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:213 +0x8c
created by v.io/x/ref/runtime/internal/rt.(*Runtime).initSignalHandling
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:219 +0x291

goroutine 2602 [chan receive]:
v.io/x/ref/runtime/internal/rt.func��002()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:182 +0x7b
created by v.io/x/ref/runtime/internal/rt.(*Runtime).addChild
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:186 +0x32f

goroutine 1255 [chan receive]:
v.io/x/ref/runtime/internal/rpc.cleanupTryCall(0x0, 0xc20818c7f0, 0x1, 0x1, 0xc20851d380)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:612 +0x10a
created by v.io/x/ref/runtime/internal/rpc.(*client).failedTryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:622 +0xc0

goroutine 1372 [chan receive]:
v.io/x/ref/runtime/internal/rpc.cleanupTryCall(0x0, 0xc208056470, 0x1, 0x1, 0xc20853f560)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:612 +0x10a
created by v.io/x/ref/runtime/internal/rpc.(*client).failedTryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:622 +0xc0

goroutine 1301 [IO wait]:
net.(*pollDesc).Wait(0xc20834ea70, 0x77, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_poll_runtime.go:84 +0x63
net.(*pollDesc).WaitWrite(0xc20834ea70, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_poll_runtime.go:93 +0x51
net.(*netFD).connect(0xc20834ea10, 0x0, 0x0, 0x7f1f0e8c4f30, 0xc208768a80, 0xecd486713, 0xc22f76bf57, 0x1c36d40, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_unix.go:114 +0x294
net.(*netFD).dial(0xc20834ea10, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc20876d800, 0xecd486713, 0x2f76bf57, 0x1c36d40, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/sock_posix.go:139 +0x440
net.socket(0xce10f0, 0x3, 0x2, 0x1, 0x0, 0xc20876d800, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc20876d800, ...)
	/usr/local/google/home/veyron/go/src/net/sock_posix.go:91 +0x4d2
net.internetSocket(0xce10f0, 0x3, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc20876d800, 0xecd486713, 0x2f76bf57, 0x1c36d40, 0x1, ...)
	/usr/local/google/home/veyron/go/src/net/ipsock_posix.go:137 +0x15e
net.dialTCP(0xce10f0, 0x3, 0x0, 0xc20876d800, 0xecd486713, 0x2f76bf57, 0x1c36d40, 0x710a00005a80c7, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/tcpsock_posix.go:156 +0x136
net.dialSingle(0xce10f0, 0x3, 0xc2087fbf00, 0x10, 0x0, 0x0, 0x7f1f0e8c4e78, 0xc20876d800, 0xecd486713, 0x2f76bf57, ...)
	/usr/local/google/home/veyron/go/src/net/dial.go:235 +0x410
net.func��016(0xecd486713, 0x2f76bf57, 0x1c36d40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:163 +0x1b2
net.dial(0xce10f0, 0x3, 0x7f1f0e8c4e78, 0xc20876d800, 0xc2087eb5d8, 0xecd486713, 0xe2f76bf57, 0x1c36d40, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/go/src/net/fd_unix.go:40 +0x89
net.(*Dialer).Dial(0xc208505a40, 0xce10f0, 0x3, 0xc2087fbf00, 0x10, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:170 +0x620
net.DialTimeout(0xce10f0, 0x3, 0xc2087fbf00, 0x10, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:150 +0x10e
v.io/x/ref/runtime/internal/rpc/protocols/tcp.tcpDial(0xce10f0, 0x3, 0xc2087fbf00, 0x10, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/protocols/tcp/init.go:24 +0x9d
v.io/x/ref/runtime/internal/rpc/stream/manager.dial(0xe6eea0, 0xce10f0, 0x3, 0xc2087fbf00, 0x10, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:96 +0xbb
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).FindOrDialVIF(0xc2088d2f50, 0xc208505980, 0x7f1f0e8c6008, 0xc20820c230, 0xc208768600, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:149 +0x993
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).Dial(0xc2088d2f50, 0xc208505980, 0x7f1f0e8c6008, 0xc20820c230, 0xc208768600, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:168 +0xc7
v.io/x/ref/runtime/internal/rpc.(*client).createFlow(0xc20822b080, 0xc208505980, 0x7f1f0e8be5a0, 0xc208555590, 0x7f1f0e8c6008, 0xc20820c230, 0xc208768600, 0x2, 0x2, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:152 +0x470
v.io/x/ref/runtime/internal/rpc.(*client).tryCreateFlow(0xc20822b080, 0xc208505980, 0x7f1f0e8be5a0, 0xc208555590, 0x0, 0xc20873e860, 0x1d, 0xc20873ea20, 0x1d, 0xcd8d30, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:378 +0xad8
created by v.io/x/ref/runtime/internal/rpc.(*client).tryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:488 +0x12ef

goroutine 1430 [IO wait]:
net.(*pollDesc).Wait(0xc208a0f250, 0x77, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_poll_runtime.go:84 +0x63
net.(*pollDesc).WaitWrite(0xc208a0f250, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_poll_runtime.go:93 +0x51
net.(*netFD).connect(0xc208a0f1f0, 0x0, 0x0, 0x7f1f0e8c4f30, 0xc2089fbae0, 0xecd486717, 0xc21ee77355, 0x1c36d40, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/fd_unix.go:114 +0x294
net.(*netFD).dial(0xc208a0f1f0, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc208626420, 0xecd486717, 0x1ee77355, 0x1c36d40, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/sock_posix.go:139 +0x440
net.socket(0xce10f0, 0x3, 0x2, 0x1, 0x0, 0xc208626400, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc208626420, ...)
	/usr/local/google/home/veyron/go/src/net/sock_posix.go:91 +0x4d2
net.internetSocket(0xce10f0, 0x3, 0x7f1f0e8c4ee0, 0x0, 0x7f1f0e8c4ee0, 0xc208626420, 0xecd486717, 0x1ee77355, 0x1c36d40, 0x1, ...)
	/usr/local/google/home/veyron/go/src/net/ipsock_posix.go:137 +0x15e
net.dialTCP(0xce10f0, 0x3, 0x0, 0xc208626420, 0xecd486717, 0x1ee77355, 0x1c36d40, 0x710a00005a80c7, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/tcpsock_posix.go:156 +0x136
net.dialSingle(0xce10f0, 0x3, 0xc2089fba20, 0x11, 0x0, 0x0, 0x7f1f0e8c4e78, 0xc208626420, 0xecd486717, 0x1ee77355, ...)
	/usr/local/google/home/veyron/go/src/net/dial.go:235 +0x410
net.func��016(0xecd486717, 0x1ee77355, 0x1c36d40, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:163 +0x1b2
net.dial(0xce10f0, 0x3, 0x7f1f0e8c4e78, 0xc208626420, 0xc2086fd530, 0xecd486717, 0xe1ee77355, 0x1c36d40, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/go/src/net/fd_unix.go:40 +0x89
net.(*Dialer).Dial(0xc208860340, 0xce10f0, 0x3, 0xc2089fba20, 0x11, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:170 +0x620
net.DialTimeout(0xce10f0, 0x3, 0xc2089fba20, 0x11, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/go/src/net/dial.go:150 +0x10e
v.io/x/ref/runtime/internal/lib/websocket.HybridDial(0xce2990, 0x3, 0xc2089fba20, 0x11, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/lib/websocket/hybrid.go:23 +0x13b
v.io/v23/rpc.func��003(0xce10f0, 0x3, 0xc2089fba20, 0x11, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/v23/rpc/registry.go:69 +0xc5
v.io/x/ref/runtime/internal/rpc/stream/manager.dial(0xc20801e940, 0xce10f0, 0x3, 0xc2089fba20, 0x11, 0x45d964b800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:96 +0xbb
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).FindOrDialVIF(0xc2088fd6d0, 0xc208860280, 0x7f1f0e8c6008, 0xc20884e000, 0xc2089fb6a0, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:149 +0x993
v.io/x/ref/runtime/internal/rpc/stream/manager.(*manager).Dial(0xc2088fd6d0, 0xc208860280, 0x7f1f0e8c6008, 0xc20884e000, 0xc2089fb6a0, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/manager/manager.go:168 +0xc7
v.io/x/ref/runtime/internal/rpc.(*client).createFlow(0xc208516d80, 0xc208860280, 0x7f1f0e8be5a0, 0xc2086f7ad0, 0x7f1f0e8c6008, 0xc20884e000, 0xc2089fb6a0, 0x2, 0x2, 0x0, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:152 +0x470
v.io/x/ref/runtime/internal/rpc.(*client).tryCreateFlow(0xc208516d80, 0xc208860280, 0x7f1f0e8be5a0, 0xc2086f7ad0, 0x0, 0xc208401ba0, 0x17, 0xc208401da0, 0x17, 0xcf3a70, ...)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:378 +0xad8
created by v.io/x/ref/runtime/internal/rpc.(*client).tryCall
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:488 +0x12ef

goroutine 2603 [chan receive]:
v.io/x/ref/runtime/internal/rt.func��002()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:182 +0x7b
created by v.io/x/ref/runtime/internal/rt.(*Runtime).addChild
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:186 +0x32f

goroutine 2575 [runnable]:
v.io/x/ref/runtime/internal/rpc/stream/vif.(*VIF).writeLoop(0xc2086e4000)
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:821
created by v.io/x/ref/runtime/internal/rpc/stream/vif.internalNew
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rpc/stream/vif/vif.go:317 +0x1684

goroutine 2600 [chan receive]:
v.io/x/ref/runtime/internal/rt.func��002()
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:182 +0x7b
created by v.io/x/ref/runtime/internal/rt.(*Runtime).addChild
	/usr/local/google/home/veyron/.jenkins/jobs/vanadium-go-snapshot/workspace/root/release/go/src/v.io/x/ref/runtime/internal/rt/runtime.go:186 +0x32f
exit status 2
FAIL	v.io/x/ref/runtime/internal/rpc/test	76.113s

**Comment by suharshs** [comment]
This has been resolved.
