### ISSUE TITLE
Surface "disconnected" notifications

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#643]
Assigning to @cosnicolaou per offline discussion.
Also +cc @hpucha @kenashcraft @nadava

For the Syncbase demo, we wanted to demonstrate having two devices sync, then go completely offline, perform offline ops on each device, then reconnect and see everything sync. Currently, this works if you wait for some number of minutes, but it's nowhere near real-time, and not compelling for a demo.

I think the basic mechanism we need to improve this is a "disconnect" notification (or perhaps more accurately, an "IP change" notification), so that we can trigger immediate cancellation of outstanding RPCs, wipe any endpoint caches, etc. such that subsequent RPCs start from a clean slate.

In this particular case, RPCs from the app code all talk to local Syncbase, so it seems possible for the app to be completely oblivious to the connection state. That said, it'd be nice if we could also surface connection state info in the API, to provide apps with a direct mechanism to monitor network state.

**Comment by asadovsky** [comment]
+cc @mattr-google and @suharshs 

I think this is relevant to the syncslides demo as well.

Can Matt, Suharsh, Cos, or anyone else describe the current state of affairs and what might still need to be done for this to work?

**Comment by ghost** [comment]
We on the RPC side have been talking about this issue quite a bit.  In some other systems like stubby the channel is an object that users interact with, and therefore can monitor and configure.  In our system we try to hide the channels and the stream/flow manager just tries to do the right thing with calls.  Syncbase basically hates this abstraction and so you guys keep fighting against the interfaces.

I think we'll need to make adjustments, but I really don't think this is the kind of thing  we should try to hack into our APIs in the next three days.  I think it's going to be a longer more reflective discussion about how to satisfy the needs of syncbase and simpler users too.  If you need this functionality in your demo then we can talk about how to hack some short term thing with the intention of throwing it all away later.

**Comment by asadovsky** [comment]
This isn't urgent or necessary for our demos, so I wouldn't rush any hacks - I just wanted to get a better understanding of the status quo and make sure that someone's actually thinking about what we ought to do.

As an aside, it's not entirely clear to me why we'd need any API changes here - wouldn't all clients want their RPCs to be cancelled (with a sufficiently specific error message) under these particular circumstances?

**Comment by ghost** [comment]
Sorry we're talking about two separate issues.

Your post says "to provide apps with a direct mechanism to monitor network state".  There is currently no API which says "Hey, I want to try to maintain a connection to Foo, and I want to be able to ask at any moment if Foo is currently accessible and get an update on the performance characteristics of that channel".  I think we want to support that use case, but not in the near term.

Yes if the server become inaccessible we should cancel RPCs.  A few days ago I added new features to hopefully make that work in most cases.  You should try again now, I suspect it will work with only a couple of seconds of delay.  Of course we should go even faster, and some of that work will happen this quarter.

**Comment by asadovsky** [comment]
Thanks, makes sense. I'll try it out sometime and report back.

**Comment by asadovsky** [comment]
Also just reassigned this issue to you. Feel free to close it, split it into multiple issues, or otherwise have your way with it. :)
