### ISSUE TITLE
Failure in target vanadium-www-tutorials-external

### ISSUE THREAD

**Issue by hpucha** [vanadium/issues#656]
Occasionally seeing this

The file $V23_RELEASE/bin/principal does not exist or is not executable.

https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-external/131/OS=darwin/console
https://veyron.corp.google.com/jenkins/job/vanadium-www-tutorials-external/146/OS=linux/console

**Comment by monopole** [comment]
project on hiatus
