### ISSUE TITLE
Make URLs prettier by eliminating need for .html suffix

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#660]
This works:  https://v.io/tutorials/faq.html

This 404's:  https://v.io/tutorials/faq

Allow the latter form to work.

**Comment by aghassemi** [comment]
Just assigning issues so everything has an owner.

**Comment by asadovsky** [comment]
Don't think we can do this with GitHub pages unless we made everything a directory with an index.html.
I'll go ahead and close this since it doesn't seem like a big deal and there's not much we can do with the current setup.
