### ISSUE TITLE
Chat: Better way of cleaning up names

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#665]
The Chat UI test visits the chat app website and creates a new name each time. Unfortunately, this led the webdriver account to be the first to hit 1000 names in the mount table, and subsequently fail to mount (See: #664). There needs to be a way to clean up these old/unused chat names. (I deleted them with a namespace delete as the admin, but there must be a better way.)

@afandria @caprita

**Comment by nlacasse** [comment]
This test has been disabled.
