### ISSUE TITLE
ResumeMarker in JS Watch API is not optional

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#693]
In the Syncbase's Watch API, ResumeMarker is meant to be optional - if you pass null, '' or undefined watch API is supposed to return the initial state first and then all the updates afterwards (according to v23/services/watch)

In JavaScript passing 'null' as the value of the resumeMarker to the `watch(ctx, table, prefix, resumeMarker, cb)` method results in the following error:
`Uncaught TypeError: Value: null, Type: v.io/v23/services/watch.ResumeMarker []byte - value is null for non-optional type`

We should ensure resumeMarker can be optional in JS (should work if null, '' or if not specified) and that the behaviour is as per the watch API spec.

@asadovsky @nlacasse

**Comment by ivanpi-mtv** [comment]
This is not JS-specific, but needs backend implementation (#917).

**Comment by ivanpi-mtv** [comment]
Fixed by v.io/c/19952
