### ISSUE TITLE
Cleanup: Revisit API comments

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#694]
We should do a sweep of API comments across all languages to ensure they are consistent and correct.

**Comment by asadovsky** [comment]
Covered by documentation deliverables doc. Closing this issue. We may end up filing new issues for specific deliverables from the doc.
https://docs.google.com/document/d/1l3_NqBdnQ_miVaOOCsw5CkcdvdTxC-AImmqhdY7MNOg/edit#
