### ISSUE TITLE
Add Syncbase Mojo/Dart test to Jenkins

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#709]
Also the test should be a presubmit for the following repos:
release.mojo.syncbase (itself, of course)
release.mojo.shared
release.go.x.ref

@asadovsky

**Comment by aghassemi** [comment]
@asadovsky:

as for general strategy, we're thinking to set up a package (profile or container) for Mojo+Flutter, pinned at versions for which the two are compatible, and have all Jenkins nodes (as well as Vanadium developers) install that package.

To avoid the package become stale (a problem we already have, e.g. for NodeJS), we can add a test that turns red if the package is > N days old for some N.

**Comment by asadovsky** [comment]
Done by @nlacasse
