### ISSUE TITLE
Fill out index page of syncbase jsdoc

### ISSUE THREAD

**Issue by jinjingforever** [vanadium/issues#714]
I left a TODO here: https://jsdoc-syncbase.v.io

Please create an index page like the one at https://jsdoc.v.io/. The file is located at: $V23_ROOT/release/javascript/syncbase/jsdocs/index.md

Assigned to Adam for now. Feel free to re-assign.

@nlacasse @aghassemi

**Comment by asadovsky** [comment]
Covered by documentation deliverables doc. Closing this issue. We may end up filing new issues for specific deliverables from the doc.
https://docs.google.com/document/d/1l3_NqBdnQ_miVaOOCsw5CkcdvdTxC-AImmqhdY7MNOg/edit#
