### ISSUE TITLE
Syncbase should sync non-VDL values

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#728]
Currently getDBDeltas() fails to receive a response if the delta contains a row with a non-VDL value. This happens because getDBDeltas()  tries to process BlobRefs from values, assuming they are VDL-encoded. VDL-decoding a non-VDL value generates an error and the sync gets stuck because it tries to process the same value over and over again, but gets the VDL-decoding error.

**Comment by hpucha** [comment]
This is now fixed and suitable tests added.
