### ISSUE TITLE
security: Use ":" instead of "/" for separating components of blessing names

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#739]
As discussed with various other folks, particularly @asadovsky @m3bm3b @ankurtaly - the plan is to change the blessing separator from `/` to `:`. (See https://groups.google.com/a/v.io/d/msg/vanadium-discuss/AIN6GZuZP5s/sYgV-X3gBQAJ)

The main motivation is to be "easy on the eyes". In particular:

- When a string is presented in documentation or configuration files. it is easier to determine whether the string refers to an object name or a blessing name (e.g., `dev.v.io/u/foo@bar.com` will more often than not mean an object name while `dev.v.io:u:foo@bar.com` will mean a blessing name)

- Suffixes hosted by a syncbase service are of the form `<db>/<app>/<table>/<key>`, where `<app>` is commonly going to be the blessing name of the application. Allowing slashes in `<db>`, `<app>` and `<table name>` complicates semantics (does `foo/bar/baz` refer to the table `baz` of the application `bar` in the database `foo`, or the application `bar/baz` in the database `foo`?). Thus, user-provided slashes in these component names will be escaped. User provide slashes are likely to be rare, but since `<app>` will be a blessing name, the separator will appear often in it. Using `:` instead of `/` as the separator will reduce the number of times developers are exposed to escaped strings, improving general prettiness.

**Comment by asimshankar** [comment]
@rthellend : There is no intention to ensure that "blessing names are always valid object names without further encoding". This is more of a cosmetic change that uses a separate delimiter so that in practice the number of times the escaping/encoding is needed is reduced.

Now that the syncslides demo is done with, I'm going to pick up on this.

**Comment by asadovsky** [comment]
Sorry not to chime in earlier - I had misconfigured my GitHub notifications. In any case, I agree with everything @asimshankar, @m3bm3b, and @presotto have said - which is not surprising since we discussed this at length a while back. :)

**Comment by rthellend** [comment]
@ashankar : For those who want to use blessing names as object names, will you provide a library function to encode them into valid object names, and also decode object names back to blessing names?

For what it's worth, I really don't care what separator is used in blessing names :) Something that can be copy&pasted easily is nice.

**Comment by asadovsky** [comment]
@rthellend naming.EncodeAsNameElement and naming.DecodeFromNameElement

**Comment by AsturaPhoenix** [comment]
Monitoring failure due seemingly to stage 3 rollout:
https://github.com/vanadium/issues/issues/963
