### ISSUE TITLE
device Kill flakiness

### ISSUE THREAD

**Issue by ivanpi-mtv** [vanadium/issues#741]
https://veyron.corp.google.com/jenkins/job/vanadium-go-cover/615/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_daemonreap/TestReapReconciliationViaKill/
https://veyron.corp.google.com/jenkins/job/vanadium-go-cover/606/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_daemonreap/TestDaemonRestart/

```
helpers.go:357: instance_reaping_kill_test.go:98: Kill(google naps/20150929-21:07:02.4716/20150929-21:07:05.0624) failed: v.io/x/ref/services/device/internal/impl.OperationFailed [daemonreap.test:"apps/google naps/20150929-21:07:02.4716/20150929-21:07:05.0624".Kill: operation failed: Advance() failed: daemonreap.test:<rpc.Client>"/@6@tcp@127.0.0.1:51277@@5480f62746686fe637f20fff0a89d522@l@root/self/forapp,root/self/mydevice/callback@@".Stop: error reading version byte failed to decode response: daemonreap.test: error reading version byte EOF]
```

Also happened during production deploy Sep 29 for one service (mounttabled). Succeeded on retry.

@rthellend @caprita

**Comment by caprita** [comment]
I think that https://vanadium-review.googlesource.com/#/c/16315/ should solve these races. I examined the logs from both failures mentioned in this bug, and they look similar to what cl 16315 was meant to fix.
