### ISSUE TITLE
Croupier: Syncgroup setup

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#750]
Mojo + Syncbase has been adding syncgroup support. Once multiple instances can create and join a sync group, this needs to be added to Croupier. This is vital for supporting multiplayer games.

**Comment by afandria** [comment]
@nlacasse 

We've gotten closer. 2 connected Android devices can startup a syncgroup, connect, and share settings data.

Note that the first device must be started up well in advance of the second, since we aren't signalling _who_ should start the syncgroup. This is meant for syncing settings information on a known mount table. We may be better off using a cloud instance of the "global" syncgroup.

**Comment by kenashcraft** [comment]
Why aren't you signalling who starts the syncgroup?  I imagine the player interaction is:
Player1: "Hey, let's play a game!"
Player2: "That sounds like fun."
Player1: "I've started the game (syncgroup).  The app should discover it automatically via BLE/Mounttable/etc."

**Comment by afandria** [comment]
Currently, when the program starts up, it attempts to join a predefined syncgroup. If it isn't found, then it attempts to create that predefined syncgroup.

Unfortunately, creation is not instantaneous, so it's possible that two devices create the syncgroup simultaneously. We need a way to avoid that.

I agree that the signal is a lot more clear when creating a game. However, there is also a stage where people are attempting to discover each other. During this discovery process, I want to share player setting data via syncbase, even though they are not part of the same game. That requires another syncgroup without significant clarity over which device should create it. This syncgroup can also be leveraged to invite players into the subsequent game-specific syncgroup.

**Comment by kenashcraft** [comment]
So you have a problem with a race condition on a predefined syncgroup.  I
assume that is only for testing purposes until you have discovery.

For discovery, you should use the Discovery code Jungho, Shyam, and Asim
are working on.  Don't create a syncgroup for discovery.

**Comment by afandria** [comment]
I have syncgroups running.
