### ISSUE TITLE
device TestLifeOfAnApp flaky

### ISSUE THREAD

**Issue by ivanpi-mtv** [vanadium/issues#754]
https://veyron.corp.google.com/jenkins/job/vanadium-go-cover/643/testReport/junit/v/io_x_ref_services_device_deviced_internal_impl_applife/TestLifeOfAnApp/

```
E1002 13:38:24.520266   26581 dispatcher.go:198] Invoke(method:Instantiate argptrs:[]) returned error: applife.test:"apps/google naps/20151002-20:38:23.1219".Instantiate: invalid blessing: no blessings on stream: <nil>
```
```
Shutdown on program "impl/utiltest/modules.go:56 DeviceManager": error: applife.test: timeout waiting for child
```
```
helpers.go:159: Resolve(appV1) expected 2 result(s), got 1 instead
```

@rthellend @caprita

**Comment by caprita** [comment]
Just submitted https://vanadium-review.googlesource.com/#/c/16313/, which removes a source of flakiness in publishing the app server used by device manager tests. This should fix https://veyron.corp.google.com/jenkins/job/vanadium-go-test/756/ARCH=amd64,OS=linux/console ( @rogulenko ), which I think is the same the issue originally reported by @ivanpi-mtv
