### ISSUE TITLE
Flaky discovery tests

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#759]
There are two flaky tests:

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/12781/ARCH=amd64,OS=darwin,TEST=vanadium-go-test/testReport/junit/v/io_x_ref_lib_discovery/TestBasic__GoTest___darwin_amd64_/

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/12786/ARCH=amd64,OS=darwin,TEST=vanadium-go-test/testReport/junit/v/io_x_ref_lib_discovery_plugins_mdns/TestBasic__GoTest___darwin_amd64_/

**Comment by jhahn21** [comment]
should be fixed by vcl/16358.
