### ISSUE TITLE
Publish Syncbase on Darts pub system

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#760]
Ideally one can use Syncbase simply by adding `syncbase` as a dependency to the `pubspec.yaml` file and doing a `pub get`

That should be all that's necessary to use Syncbase in a Mojo/Flutter app on Linux or Android. Initially we can target Flutter/Android.

We should version Syncbase based on the the pub system's [versioning scheme](https://www.dartlang.org/tools/pub/versioning.html)

*assuming we want to switch package name to syncbase from ether.

@nlacasse @asadovsky

**Comment by nlacasse** [comment]
We build two different syncbase mojo binaries. One for Android/arm and one
for Linux/amd64.

I'm not sure how this will work with pub get.  Do pub or dart have a way to
include different files based on the target architecture?

Also, +1 for changing the name.

**Comment by aghassemi** [comment]
It probably needs to get both since it doesn't even know the true target architecture (pub get happening on Linux but the app being deployed on Android or iOS). Probably we should just start with Flutter/Android setup and take it from there.

**Comment by aghassemi** [comment]
Also to make initial developer experience better, we should have a pub tool to scaffold a flutter+syncbase app. Either by integrating with existing Flutter tool or a separate one. Flutter for example already has `flutter init -o my_app` so maybe we can do

`flutter syncbase init -o my_app`
or
`syncbase init -o my_app`

**Comment by aghassemi** [comment]
This was brought up in the meeting today. They currently don't have a nice of way of depending on Syncbase. They have a separate V23 environment where they build the syncbase.mojom manually, then they copy that into their third party along with the client Dart code. 

I am going to start looking at this since it is a pain point for them. @kenashcraft

**Comment by kenashcraft** [comment]
I think James Robinson and @tatatodd were going to figure this out.

**Comment by aghassemi** [comment]
ok I will chat with them. This one is a slightly different problem than jiri profile for mojo, but I was planning to check with James to see what the longterm plan is for developers to publish their mojo code as a bundle.

**Comment by aghassemi** [comment]
This is done. There is `publish` target in the makefile that anyone should be able to use to publish.
Couple of examples using Syncbase as a pub packages as well:

https://github.com/aghassemi/syncbase-sample
https://github.com/aghassemi/syncbase-flutter-sample
