### ISSUE TITLE
Presubmit test failures

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#762]
These two happened a couple of times:

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-www-tutorials-core/12803/console

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-go-depcop/12805/console

**Comment by nlacasse** [comment]
Closing: OBSOLETE

Unfortunately those links don't work any more.

The www-tutorials core task no longer exists, and I haven't seen any flakes in go-depcop in a while, so that issue should be resolved.
