### ISSUE TITLE
Git-mirror is rate limited

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#763]
Happens every day from ~11am to 1pm.

https://veyron.corp.google.com/jenkins/job/git-mirror/lastFailedBuild/console

**Comment by nlacasse** [comment]
I bumped the git-mirror task to run every hour instead of every minute.

That should fix this task, but it will probably cause other issues...

**Comment by nlacasse** [comment]
Bumped again to run every 5 min.  We should still be well under quota.

Please re-open if this error occurs again.
