### ISSUE TITLE
Various JS tests fail with timeout

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#767]
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-js-vdl/12884/

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-browser-test/12887/

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-browser-test/12808/

https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-js-browser-integration/12847/

**Comment by afandria** [comment]
Looks like prova fails to start/exit.

See bottom of the console output:
https://veyron.corp.google.com/jenkins/job/vanadium-presubmit-test/ARCH=amd64,OS=linux,TEST=vanadium-js-vdl/12884/console

**Comment by aghassemi** [comment]
or fails to start, I don't see any output from browser, just node.

probably another breaking dependency creep :(

**Comment by aghassemi** [comment]
Seems stable now. Closing
