### ISSUE TITLE
Flow manager tests are flaky

### ISSUE THREAD

**Issue by rogulenko** [vanadium/issues#770]
There are several failing tests, all errors here are different:

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/719/

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/716/

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/706/

https://veyron.corp.google.com/jenkins/job/vanadium-go-test/793/

https://veyron.corp.google.com/jenkins/job/vanadium-go-test/788/

**Comment by ghost** [comment]
Will be fixed by:

https://vanadium-review.googlesource.com/#/c/16477/

**Comment by ghost** [comment]
submitted.
