### ISSUE TITLE
ns.dev.v.io users mount points get created without Read/Resolve permissions

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#771]
A few months back, @presotto and I discussed an issue where default permissions for users' mount points included only an Admin permission for themselves. This was determined to be a bug, where the expected behavior was to include '...' Resolve permissions. Dave made https://vanadium-review.googlesource.com/#/c/14461/ to address this, but either it didn't work or has been somehow reverted, as new user mount points are still being created without Resolve permissions.

It may also be worth discussing whether Read is also necessary. In the (shelved) Travel application code, I am explicitly setting the user mount point to Read/Resolve '...'. When I do Resolve-only, I cannot join SyncGroups between users (though it may be worth simplifying the example into a test to tell for sure if this is the case).

**Comment by presotto** [comment]
I screwed up pushing it out somehow.  Config files somehow don't fit
bogdans model.  I'll try again now.

Making read default is a noticeable change.  We'll have to discuss it.

**Comment by presotto** [comment]
By the way, I'd be happy with read by default, I.e. you have to go out of
your way to hide something.

**Comment by caprita** [comment]
Since we pushed the updated config to prod yesterday, should we close this issue and perhaps you can open a new one about opening up Read by default if that's something you want to do?

**Comment by AsturaPhoenix** [comment]
Sure. Verified that new users mount points and children are created with Resolve in '...'. Will create a new issue to verify Read in '...' permissions are also required for multi-user Syncgroups.
