### ISSUE TITLE
400ms to fetch 80KB from syncbase on Nexus 6

### ISSUE THREAD

**Issue by kenashcraft** [vanadium/issues#772]
I'm storing 80KB images in syncbase.  It takes about 400ms to fetch them (with a query, if that matters) on a Nexus 6.  This is a representative image:
![slide1_thumb](https://cloud.githubusercontent.com/assets/9617941/10421472/df766d8c-705d-11e5-8778-bc50f803f4ab.png)

This is really painful!  I'm going to further compress my images, but I can only do so much before they look bad.

Here's my code:

```
    private void fetchData() {
        //Process.setThreadPriority(Process.THREAD_PRIORITY_BACKGROUND);

        try {
            BatchDatabase batch = mDB.beginBatch(mVContext, null);
            Table table = batch.getTable(NOTES_TABLE);

            String query = "SELECT k, v FROM Decks WHERE Type(v) LIKE \"%Slide\" " +
                    "AND k LIKE \"" + NamingUtil.join(mDeckId, "slides") + "%\"";
            ResultStream stream = batch.exec(mVContext, query);
            // TODO(kash): Abort execution if interrupted.  Perhaps we should derive
            // a new VContext so it can be cancelled.
            for (List<VdlAny> row : stream) {
                if (row.size() != 2) {
                    throw new VException("Wrong number of columns: " + row.size());
                }
                String key = (String) row.get(0).getElem();
                Log.i(TAG, "Fetched slide " + key);
                io.v.android.apps.syncslides.Slide slide =
                        (io.v.android.apps.syncslides.Slide) row.get(1).getElem();
                Note note = (Note) table.get(mVContext, key, Note.class);
                final SyncbaseSlide newSlide = new SyncbaseSlide(
                        key, slide.getThumbnail(), note.getText());
                mHandler.post(new Runnable() {
                    @Override
                    public void run() {
                        mSlides.add(newSlide);
                        mListener.notifyItemInserted(mSlides.size() - 1);
                    }
                });
            }
        } catch (VException e) {
            Log.e(TAG, e.toString());
        }
    }
```

@rogulenko, can you work with Matt to create a microbenchmark?  Perhaps start with Go with a Put/Get of the image.  If that is ok, move to vanilla Java.  If that is ok, move to Android.

@suharshs @asadovsky

**Comment by kenashcraft** [comment]
@spetrovic77

**Comment by spetrovic77** [comment]
@rogulenko

I can help you with Java perf.

**Comment by ghost** [comment]
I did go get/put on my desktop, it takes about 4ms for the get of the image.  I'll try it with a query now.

**Comment by ghost** [comment]
Ok, I tried query too,  it was strangly slightly faster at 3.7ms per get.  I've attached my hacked up benchmark below.  Anybody see an obvious flaw?  Can someone throw a Java version together?

func V23TestSyncbasedPutGet(t *v23tests.T) {
  v23tests.RunRootMT(t, "--v23.tcp.address=127.0.0.1:0")
  clientCreds, _ := t.Shell().NewChildCredentials("server/client")
  serverCreds, _ := t.Shell().NewChildCredentials("server")
  cleanup := tu.StartSyncbased(t, serverCreds, syncbaseName, "",
    `{"Read": {"In":["root/server/client"]}, "Write": {"In":["root/server/client"]}}`)
  defer cleanup()

  ctx := t.Context()

  ctx, err := v23.WithPrincipal(ctx, clientCreds.Principal())
  if err != nil {
    panic(err)
  }

  // Read in the image.  
  data, err := ioutil.ReadFile("/usr/local/google/home/mattr/tmp/car.png")
  if err != nil {
    panic(err)
  }
  if len(data) < 10000 {
    panic("too small?")
  }

  // Create app, database and table.                                                                                                                                                                                                                                                   a := syncbase.NewService(syncbaseName).App("a")
  if err := a.Create(ctx, nil); err != nil {
    t.Errorf("unable to create an app: %v", err)
  }
  d := a.NoSQLDatabase("d", nil)
  if err := d.Create(ctx, nil); err != nil {
    t.Errorf("unable to create a database: %v", err)
  }
  ctx.Infof("crated database")
  if err := d.Table("tb").Create(ctx, nil); err != nil {
    t.Errorf("unable to create a table: %v", err)
  }
  tb := d.Table("tb")

  ctx.Infof("created table")

  // Do Put followed by Get on a row.  
  r := tb.Row("r")
  if err := r.Put(ctx, data); err != nil {
    t.Errorf("r.Put() failed: %v", err)
  }

  ctx.Infof("put a row")

  n := 1000
  start := time.Now()
  for i := 0; i < n; i++ {
    switch howGet {
    case ByQuery:
      _, res, err := d.Exec(ctx, "select v from tb")
      if err != nil {
        t.Fatal(err)
      }
      if res == nil {
        t.Fatal("res is nil?")
      }
      found := false
      for res.Advance() {
        _ = res.Result()[0].Bytes()
        // if !bytes.Equal(data, result) {  
        //  t.Errorf("data not equal.")  
        // }  
        found = true
      }
      if !found {
        t.Errorf("not found!")
      }
    case ByGet:
      var result []byte
      if err := r.Get(ctx, &result); err != nil {
        t.Errorf("r.Get() failed: %v", err)
      }
      // if !bytes.Equal(data, result) {  
      //  t.Errorf("data not equal.")  
      // }  
    }
  }
  end := time.Now()
  dur := end.Sub(start)
  ctx.Infof("%d iters in %v, avg is %v", n, dur, time.Duration(float64(dur)/float64(n)))
}

**Comment by spetrovic77** [comment]
I'll do a java version.

**Comment by ghost** [comment]
By the way based on previous experiments I expect the phone to be 5-10x slower than my desktop, which would put this in the range of 20-40ms per, which is still 10-20x off the numbers you're actually seeing.

**Comment by ghost** [comment]
James is working on this.

**Comment by spetrovic77** [comment]
Thanks to sjamesr@ and Benj, we can now load larger images much more efficiently.  According to my tests, it takes about 15ms to fetch the image data and another 15-20ms to create the bitmap from it on android.  So that adds to about 400ms on a phone for 11 images.

The 15-20ms bitmap creation overhead is likely there to stay.  I'll look at the 15ms to fetch it, but I think the timings are okay now.  So closing the bug.
