### ISSUE TITLE
Failure in client_test.go: does not receive errNoServers

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#774]
@suharshs @mattr-google 

https://dashboard.staging.v.io/?type=presubmit&n=13140#
(change https://vanadium-review.googlesource.com/#/c/15279/ and https://vanadium-review.googlesource.com/#/c/16083/ )

NOTE: the panic is because it is calling a verror routine with nil (because no error is returned)

**Comment by suharshs** [comment]
I believe this has been resolved. Reopen if it hasn't.
