### ISSUE TITLE
AWS detection means that all programs using the static runtime factory will take 1 second to initialize when not running under AWS

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#776]
The principal tool seems to have gotten ~10x slower, from 0.1 s to 1 s. See below for timing an old version of the principal tool against a new version (including the two versions' respective build metadata). I am not one to typically fret over 1 second, but since we run principal for every prompt in vbash, it gets annoying quickly :-)

`time ./oldprincipal dump
Public key : 8c:a6:3d:5a:dd:1d:d7:07:7b:8b:14:56:94:3b:a6:85
Default Blessings : caprita@caprita.mtv.corp.google.com-2490
---------------- BlessingStore ----------------
Default Blessings                caprita@caprita.mtv.corp.google.com-2490
Peer pattern                     Blessings
...                              caprita@caprita.mtv.corp.google.com-2490
---------------- BlessingRoots ----------------
Public key                                        Pattern
8c:a6:3d:5a:dd:1d:d7:07:7b:8b:14:56:94:3b:a6:85   [caprita@caprita.mtv.corp.google.com-2490]

real    0m0.131s
user    0m0.018s
sys 0m0.011s`

`$ ./oldprincipal --metadata
<metadata>
  <md id="build.Manifest"><![CDATA[
<manifest label="">
  <hooks></hooks>
  <hosts></hosts>
  <imports></imports>
  <projects>
    <project exclude="false" name="deprecated" path="deprecated" protocol="git" remote="https://vanadium.googlesource.com/deprecated" revision="6be13ca6620dd7aa0f57cde9ce84ef284b2c948a"></project>
    <project exclude="false" name="docs" path="docs" protocol="git" remote="https://vanadium.googlesource.com/docs" revision="5019a5aa5a3e5b8061fd30df5faf31eba0854070"></project>
    <project exclude="false" name="experimental" path="experimental" protocol="git" remote="https://vanadium.googlesource.com/experimental" revision="84a4e3234ee280332582b26d98133b23333f52b7"></project>
    <project exclude="false" name="infrastructure" path="infrastructure" protocol="git" remote="https://vanadium.googlesource.com/infrastructure" revision="544920c6cb91277d6832024ed0dc1cab8c17a96b"></project>
    <project exclude="false" name="release.go.jiri" path="release/go/src/v.io/jiri" protocol="git" remote="https://vanadium.googlesource.com/release.go.jiri" revision="e22d94c1c65145556f0292d4e96efb6af76cf75a"></project>
    <project exclude="false" name="release.go.v23" path="release/go/src/v.io/v23" protocol="git" remote="https://vanadium.googlesource.com/release.go.v23" revision="78bfb2a503f7412bfa0f187e613a7c83362f95c9"></project>
    <project exclude="false" name="release.go.x.devtools" path="release/go/src/v.io/x/devtools" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.devtools" revision="30f16b84f24ce6441994209fec982b2da72c65ca"></project>
    <project exclude="false" name="release.go.x.jni" path="release/go/src/v.io/x/jni" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.jni" revision="12f4096ce339aab3817bf36a9cb9585e7c6d1f13"></project>
    <project exclude="false" name="release.go.x.lib" path="release/go/src/v.io/x/lib" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.lib" revision="b5dd1d263e7dda3d44b5475b0740e682956e50f4"></project>
    <project exclude="false" name="release.go.x.ref" path="release/go/src/v.io/x/ref" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.ref" revision="8c24f2d45170ca66e1693be77fc092d4926a412a"></project>
    <project exclude="false" name="release.java" path="release/java" protocol="git" remote="https://vanadium.googlesource.com/release.java" revision="9349fa089159fc706a1961114ece41a7f6833fa6"></project>
    <project exclude="false" name="release.js.core" path="release/javascript/core" protocol="git" remote="https://vanadium.googlesource.com/release.js.core" revision="c1bf78633084a5da3223cf39c6cc3e4f326a3321"></project>
    <project exclude="false" name="release.js.syncbase" path="release/javascript/syncbase" protocol="git" remote="https://vanadium.googlesource.com/release.js.syncbase" revision="6e206e647575e44a887321bd98644ceff91ccab9"></project>
    <project exclude="false" name="release.mojo.discovery" path="release/mojo/discovery" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.discovery" revision="d4a4439a5cd7ee641c8c9f86166936ea52e82372"></project>
    <project exclude="false" name="release.mojo.shared" path="release/mojo/shared" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.shared" revision="82a0396df21755d7522e632f927954a75c6a6bb6"></project>
    <project exclude="false" name="release.mojo.syncbase" path="release/mojo/syncbase" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.syncbase" revision="31f755ba6c30b3a392b611c9785d58629518d513"></project>
    <project exclude="false" name="release.projects.browser" path="release/projects/browser" protocol="git" remote="https://vanadium.googlesource.com/release.projects.browser" revision="062128165341e0a91d90e7111af5ed37718ff2ef"></project>
    <project exclude="false" name="release.projects.chat" path="release/projects/chat" protocol="git" remote="https://vanadium.googlesource.com/release.projects.chat" revision="934ab50435cfb092e2507ae64bd8f103321c46f6"></project>
    <project exclude="false" name="release.projects.croupier" path="release/projects/croupier" protocol="git" remote="https://vanadium.googlesource.com/release.projects.croupier" revision="c0a71331198f1501dd5d779ed26ec71e8a41ab0d"></project>
    <project exclude="false" name="release.projects.media-sharing" path="release/projects/media-sharing" protocol="git" remote="https://vanadium.googlesource.com/release.projects.media-sharing" revision="967529f191ff6765061a7f90aa9ff2f09bde6074"></project>
    <project exclude="false" name="release.projects.physical-lock" path="release/projects/physical-lock" protocol="git" remote="https://vanadium.googlesource.com/release.projects.physical-lock" revision="a42baecab06db211ba8bc41c36ddc63c9d2d4101"></project>
    <project exclude="false" name="release.projects.pipe2browser" path="release/projects/pipe2browser" protocol="git" remote="https://vanadium.googlesource.com/release.projects.pipe2browser" revision="0bdfbf99adc5a6f78ea73b1d6a416e9f3ca7e111"></project>
    <project exclude="false" name="release.projects.playground" path="release/projects/playground" protocol="git" remote="https://vanadium.googlesource.com/release.projects.playground" revision="a33403b650cbed860225f581e68ba915622fd1be"></project>
    <project exclude="false" name="release.projects.reader" path="release/projects/reader" protocol="git" remote="https://vanadium.googlesource.com/release.projects.reader" revision="2c11b3a57d374a40d5dd90d5fa0b95c30eb33a76"></project>
    <project exclude="false" name="release.projects.todos" path="release/projects/todos" protocol="git" remote="https://vanadium.googlesource.com/release.projects.todos" revision="122fe9ebb4b518e1562de61b2d03b2bc5564b04b"></project>
    <project exclude="false" name="release.projects.travel" path="release/projects/travel" protocol="git" remote="https://vanadium.googlesource.com/release.projects.travel" revision="b9ee70f6883cc89d29f45f9cb685b4d05874b2f6"></project>
    <project exclude="false" name="third_party" path="third_party" protocol="git" remote="https://vanadium.googlesource.com/third_party" revision="6de518007bb2f1cd884774f6ec62d915144f1d94"></project>
    <project exclude="false" name="www" path="www" protocol="git" remote="https://vanadium.googlesource.com/www" revision="a33ebce9b05236ac8a64229e2629bb3883d1e9c3"></project>
  </projects>
  <tools></tools>
</manifest>
  ]]></md>
  <md id="build.Platform">amd64-linux</md>
  <md id="build.Pristine">false</md>
  <md id="build.Time">2015-10-08T16:49:48Z</md>
  <md id="build.User">Bogdan Caprita</md>
  <md id="go.Arch">amd64</md>
  <md id="go.OS">linux</md>
  <md id="go.Version">go1.5</md>
  <md id="v23.RPCEndpointVersion">6</md>
  <md id="v23.RPCVersionMax">11</md>
  <md id="v23.RPCVersionMin">10</md>
</metadata>`

`$ time ./newprincipal dump
Public key : e0:70:6f:8b:13:98:f8:55:6f:bc:49:4e:a1:71:c4:ee
Default Blessings : caprita@caprita.mtv.corp.google.com-2501
---------------- BlessingStore ----------------
Default Blessings                caprita@caprita.mtv.corp.google.com-2501
Peer pattern                     Blessings
...                              caprita@caprita.mtv.corp.google.com-2501
---------------- BlessingRoots ----------------
Public key                                        Pattern
e0:70:6f:8b:13:98:f8:55:6f:bc:49:4e:a1:71:c4:ee   [caprita@caprita.mtv.corp.google.com-2501]

real    0m1.034s
user    0m0.042s
sys 0m0.000s`

`$ ./newprincipal --metadata
<metadata>
  <md id="build.Manifest"><![CDATA[
<manifest label="">
  <hooks></hooks>
  <hosts></hosts>
  <imports></imports>
  <projects>
    <project exclude="false" name="deprecated" path="deprecated" protocol="git" remote="https://vanadium.googlesource.com/deprecated" revision="6be13ca6620dd7aa0f57cde9ce84ef284b2c948a"></project>
    <project exclude="false" name="docs" path="docs" protocol="git" remote="https://vanadium.googlesource.com/docs" revision="7b431ac1c4ad0bbf7ffb427ebe303278866dcc22"></project>
    <project exclude="false" name="experimental" path="experimental" protocol="git" remote="https://vanadium.googlesource.com/experimental" revision="35d851868488fae7721453b3e2dedcd953200516"></project>
    <project exclude="false" name="infrastructure" path="infrastructure" protocol="git" remote="https://vanadium.googlesource.com/infrastructure" revision="e040142898ce7c3b1331d781bd3c801655e21a04"></project>
    <project exclude="false" name="release.go.jiri" path="release/go/src/v.io/jiri" protocol="git" remote="https://vanadium.googlesource.com/release.go.jiri" revision="68254102114106c9aaf16198240fb2f8c531c207"></project>
    <project exclude="false" name="release.go.v23" path="release/go/src/v.io/v23" protocol="git" remote="https://vanadium.googlesource.com/release.go.v23" revision="e3266712035195a040f3d8b4dd0d29ba1f04286a"></project>
    <project exclude="false" name="release.go.x.devtools" path="release/go/src/v.io/x/devtools" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.devtools" revision="ea9e23cb300fdeb1d95ede649c98cd25f4211609"></project>
    <project exclude="false" name="release.go.x.jni" path="release/go/src/v.io/x/jni" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.jni" revision="ddcd7e29438be1978f571aa6668a0f63da6d1570"></project>
    <project exclude="false" name="release.go.x.lib" path="release/go/src/v.io/x/lib" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.lib" revision="b5dd1d263e7dda3d44b5475b0740e682956e50f4"></project>
    <project exclude="false" name="release.go.x.ref" path="release/go/src/v.io/x/ref" protocol="git" remote="https://vanadium.googlesource.com/release.go.x.ref" revision="e09f4426dbab0240968f440a5e42ce8c3f6cff3b"></project>
    <project exclude="false" name="release.java" path="release/java" protocol="git" remote="https://vanadium.googlesource.com/release.java" revision="bc846d32feece446ccc7c0f7fb3dfe99b9ce4be4"></project>
    <project exclude="false" name="release.js.core" path="release/javascript/core" protocol="git" remote="https://vanadium.googlesource.com/release.js.core" revision="865f47f33dc99111014a97a33701249cb241548d"></project>
    <project exclude="false" name="release.js.syncbase" path="release/javascript/syncbase" protocol="git" remote="https://vanadium.googlesource.com/release.js.syncbase" revision="7ef956ecf5ea20998ea7fbc30988cce6d86edd4e"></project>
    <project exclude="false" name="release.mojo.discovery" path="release/mojo/discovery" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.discovery" revision="d4a4439a5cd7ee641c8c9f86166936ea52e82372"></project>
    <project exclude="false" name="release.mojo.shared" path="release/mojo/shared" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.shared" revision="82a0396df21755d7522e632f927954a75c6a6bb6"></project>
    <project exclude="false" name="release.mojo.syncbase" path="release/mojo/syncbase" protocol="git" remote="https://vanadium.googlesource.com/release.mojo.syncbase" revision="da4b2f551a2667719fd4477569352c0eb136b975"></project>
    <project exclude="false" name="release.projects.browser" path="release/projects/browser" protocol="git" remote="https://vanadium.googlesource.com/release.projects.browser" revision="f8b44b2ad07a4bea1e22f6b1e0c32ac0f676ee81"></project>
    <project exclude="false" name="release.projects.chat" path="release/projects/chat" protocol="git" remote="https://vanadium.googlesource.com/release.projects.chat" revision="06d02f32a811fefb40f164a3e4fdfd6b1817aca2"></project>
    <project exclude="false" name="release.projects.croupier" path="release/projects/croupier" protocol="git" remote="https://vanadium.googlesource.com/release.projects.croupier" revision="c8bc76d8387a647eeaeabc8841d1de0d1248af8d"></project>
    <project exclude="false" name="release.projects.media-sharing" path="release/projects/media-sharing" protocol="git" remote="https://vanadium.googlesource.com/release.projects.media-sharing" revision="967529f191ff6765061a7f90aa9ff2f09bde6074"></project>
    <project exclude="false" name="release.projects.physical-lock" path="release/projects/physical-lock" protocol="git" remote="https://vanadium.googlesource.com/release.projects.physical-lock" revision="dd399d38e8fb3b191a96b1480b83bd779adb177e"></project>
    <project exclude="false" name="release.projects.pipe2browser" path="release/projects/pipe2browser" protocol="git" remote="https://vanadium.googlesource.com/release.projects.pipe2browser" revision="0bdfbf99adc5a6f78ea73b1d6a416e9f3ca7e111"></project>
    <project exclude="false" name="release.projects.playground" path="release/projects/playground" protocol="git" remote="https://vanadium.googlesource.com/release.projects.playground" revision="bed61e71f50ae42a204aaf13a59bfd3192f9cb2d"></project>
    <project exclude="false" name="release.projects.reader" path="release/projects/reader" protocol="git" remote="https://vanadium.googlesource.com/release.projects.reader" revision="08a6ae5c4c9017cee7beda432b66886ccbef6626"></project>
    <project exclude="false" name="release.projects.todos" path="release/projects/todos" protocol="git" remote="https://vanadium.googlesource.com/release.projects.todos" revision="0b6af06cb114c6a5594820dd43beda88f24c12ea"></project>
    <project exclude="false" name="release.projects.travel" path="release/projects/travel" protocol="git" remote="https://vanadium.googlesource.com/release.projects.travel" revision="1193145c3fd1ac65e3decbf0cbc1a4e36621de79"></project>
    <project exclude="false" name="third_party" path="third_party" protocol="git" remote="https://vanadium.googlesource.com/third_party" revision="6de518007bb2f1cd884774f6ec62d915144f1d94"></project>
    <project exclude="false" name="www" path="www" protocol="git" remote="https://vanadium.googlesource.com/www" revision="0e755b00cbdb80db626f17db3a8545f03c62ae3d"></project>
  </projects>
  <tools></tools>
</manifest>
  ]]></md>
  <md id="build.Platform">amd64-linux</md>
  <md id="build.Pristine">false</md>
  <md id="build.Time">2015-10-12T17:56:34Z</md>
  <md id="build.User">Bogdan Caprita</md>
  <md id="go.Arch">amd64</md>
  <md id="go.OS">linux</md>
  <md id="go.Version">go1.5</md>
  <md id="v23.RPCEndpointVersion">6</md>
  <md id="v23.RPCVersionMax">11</md>
  <md id="v23.RPCVersionMin">10</md>
</metadata>`

**Comment by asimshankar** [comment]
I traced this to https://vanadium-review.googlesource.com/#/c/16376/

What's happening is that any user of the "static" runtime factory will end up running this AWS check. As per AWS documentation, the way to get instance metadata for AWS is to make an HTTP request to 169.254.169.254 

This IP is part of the AIPA range (see https://en.wikipedia.org/wiki/Link-local_address) and thus any attempts to open a TCP connection to it do not fail fast, instead the GET request only times out at the timeout set in the code  (1 second).

It seems that the AWS folks recommend only this technique and I couldn't find any tests that would fail fast when not running under AWS. Will have to dig some more, but it seems that basically this is not an issue with the principal command line tool, but really with any service that tries to detect whether or not we're running under AWS (so use of the static and possibly roaming profiles as well).

@rthellend : Do you know about any fast-fail tests for AWS?

**Comment by rthellend** [comment]
GCE uses the same IP address to serve it's metadata, but the recommended way to access it involves a dns lookup.

On a GCE instance:
$ host metadata  
metadata.google.internal has address 169.254.169.254

The same dns lookup fails very quickly if you're not on GCE.

AWS doesn't use DNS for this. Their docs all use the IP address directly.

I'll dig further.

**Comment by rthellend** [comment]
A lot of people have the same problem. A popular solution is to look at the first 3 bytes of /sys/hypervisor/uuid. If the file isn't there or if the first 3 bytes aren't "ec2", then it's not ec2.

I'm not sure how reliable it is.
