### ISSUE TITLE
jenkins: vanadium-www-tutorials-external failure

### ISSUE THREAD

**Issue by jxson** [vanadium/issues#778]
Hello @presotto,

It looks like there is a long time failing test from an update to https://github.com/presotto/go-mdns-sd

The top-level failure is from running `go get -d v.io/x/ref/...` which fails with:

```
package v.io/x/ref/cmd/mounttable
    imports github.com/presotto/go-mdns-sd: 
        found packages dns (client.go) and mdns (dnsaux.go) in .../src/github.com/presotto/go-mdns-sd
```

Go get will pull down the most recent version while other tests use the vendored third_party version which is why this doesn't cause failures in other places.

/cc @jatinlodhia @caprita

**Comment by presotto** [comment]
Accidentally copied the subdirectory go_dns files into the main directory.  Brain in neutral.   Fixed.

**Comment by presotto** [comment]
fixed

**Comment by jxson** [comment]
@presotto the build for this is green now :D thanks!
