### ISSUE TITLE
Croupier: Hearts Deal Phase

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#781]
Syncbase performance may not be as efficient as we want. This, on top of the slowdown incurred by the log writer's proposals means that the Deal phase should be shortened as much as possible.

This could mean that for performance sake, the Deal command should be collapsed to a single command, instead of partitioned across users.

**Comment by kenashcraft** [comment]
Can you be more specific about the performance issue?

**Comment by afandria** [comment]
With my current setup, it takes about 0.5 seconds to sync settings information right now, so if I also have to handle 'proposals', it takes 2 to 3 times longer the way I've written it. Further, I have 4 deal steps, when I could instead just have 1.

If it actually takes 4-6 seconds for Dealing to finish in practice, then I have to do something to improve it. A quick solution is to combine the deal steps to gain the quick 4x performance improvement and reduce the delay to perhaps 1-1.5 seconds.

**Comment by kenashcraft** [comment]
I think if you increase the sync frequency, the sync latency will go down.

**Comment by afandria** [comment]
I didn't know I had control over that, but that's good to know.

We are also running the local 'mount table' on a raspberry pi, so that is another reason for the slowness.

**Comment by AsturaPhoenix** [comment]
Ken, at some point will there be a push-based or stream-based sync protocol similar to watch? Correct me if this is already somewhat the case; I got the impression that GetDeltas was a polling pull operation. In Baku we have planned uses for Syncbase that would benefit from quick LAN syncs that might be offered by push/watch-based sync.

**Comment by kenashcraft** [comment]
Ross, yes, we need to make it easier to have low latency sync.  The exact
implementation is still TBD.

**Comment by asadovsky** [comment]
Closing this issue as it's very general. We've filed specific issues for the "unresponsive peer slows down sync", separating VDL type information from value data, and various other known performance problems.

If you think there's a specific performance problem that Syncbase ought to address, and isn't covered by the other issues we've filed, please let us know.

**Comment by afandria** [comment]
I don't think this issue should have been closed for being general, since it's related to how Croupier is supposed to work around the Deal Phase being slow. However, I did recently rework the Deal phase to be a lot faster, so this issue should remain closed.
