### ISSUE TITLE
Croupier: Runnable by all

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#782]
Our changes for sync groups will soon hard code an IP address that we expect to be a mount table on the local network. This is not great because other Vanadium users may not be able to setup their network in such a way. They will not be able to run Croupier.

We could instead specify the global mount table, but this would require using a proxy. adb limits commands to 1024 characters, and unfortunately, we pass that limit if we add those flags.

@afandria @nlacasse

**Comment by kenashcraft** [comment]
Options:
1. Wait for the discovery code to go in.  No need for a mounttable.
2. Add a "settings" page to the app so the user has some place to type in
the IP address.

**Comment by afandria** [comment]
We could go with 2 until 1 happens.

Alternatively, instead of 2, we could compress our adb command by pushing scripts to the phones and then execute that. This would allow us to use the user's section (users/email) of the global mount table.

**Comment by afandria** [comment]
We're now able to use the proxy and global mount table.
