### ISSUE TITLE
Add examples to syncbase docs

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#783]
For instance, the difference between these would be much clearer if there was an example of each type of name:
    // Name returns the relative name of this DatabaseHandle.
    Name() string

```
// FullName returns the object name (escaped) of this DatabaseHandle.
FullName() string
```

**Comment by asadovsky** [comment]
Covered by documentation deliverables doc. Closing this issue. We may end up filing new issues for specific deliverables from the doc.
https://docs.google.com/document/d/1l3_NqBdnQ_miVaOOCsw5CkcdvdTxC-AImmqhdY7MNOg/edit#
