### ISSUE TITLE
v.io/x/ref/runtime/internal/flow/conn.TestOrdering flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#788]
panic: EOF

goroutine 217 [running]:
v.io/x/ref/runtime/internal/flow/conn.TestOrdering.func1(0xc8200b0960, 0x7f3684663270, 0xc820018b40)
    /home/veyron/jenkins/workspace/vanadium-go-race/OS/linux/P/3/root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/flowcontrol_test.go:91 +0x148
created by v.io/x/ref/runtime/internal/flow/conn.TestOrdering
    /home/veyron/jenkins/workspace/vanadium-go-race/OS/linux/P/3/root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/flowcontrol_test.go:94 +0x2a3

Observed failing both on vanadium-go-race and release-candidate-2-test jenkins projects:

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/755/OS=linux,P=3/testReport/junit/v/io_x_ref_runtime_internal_flow_conn/TestOrdering__GoRace___linux_amd64_/

https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/307/ARCH=amd64,OS=linux,TEST=vanadium-go-race-part3/console

@suharshs (RPC code churner)
@jatinlodhia (build cop)

**Comment by ghost** [comment]
Fixed a while back.
