### ISSUE TITLE
v.io/x/ref/services/xproxyd.TestSingleProxy flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#789]
```
   E1013 18:24:41.000257   79577 proxyd.go:107] f.Read failed: &lt;nil&gt;
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x4526e3a]

goroutine 98 [running]:
v.io/x/ref/runtime/internal/flow/conn.(_flw).close(0x0, 0xc82028dd00, 0x4fa5860, 0xc8203d1ea0)
    /Users/veyron/jenkins/workspace/vanadium-go-test/ARCH/amd64/OS/darwin/root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/flow.go:381 +0x2a
v.io/x/ref/runtime/internal/flow/conn.(_Conn).internalCloseLocked.func1(0x4fa5860, 0xc8200c80e0, 0xc820462180, 0xc82028dd00, 0xc820460990)
    /Users/veyron/jenkins/workspace/vanadium-go-test/ARCH/amd64/OS/darwin/root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:353 +0x18d
created by v.io/x/ref/runtime/internal/flow/conn.(*Conn).internalCloseLocked
    /Users/veyron/jenkins/workspace/vanadium-go-test/ARCH/amd64/OS/darwin/root/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:369 +0x212

Observed on vanadium-go-test project:
https://veyron.corp.google.com/jenkins/job/vanadium-go-test/829/ARCH=amd64,OS=darwin/testReport/junit/v/io_x_ref_services_xproxyd/TestSingleProxy__GoTest___darwin_amd64_/

@suharshs (RPC code churner)
@jatinlodhia (build cop)

**Comment by suharshs** [comment]
This has been resolved.
