### ISSUE TITLE
v.io/x/ref/runtime/internal/rt flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#790]
This one seems tricky, since it's panic'ing while fetching discharges, and the ipc system is up and about -- even though TestInitArgs ostensibly doesn't create or use the runtime or try to do RPC. Is the modules package sneakily calling into runtime'y things, or is the failure a result of previous test case that hasn't cleaned up properly (i.e., the runtime was shut down but left behind some goroutines spinning)?

Stack dump snippet below. Full log at: https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/306/ARCH=amd64,OS=linux,TEST=vanadium-go-race-part3/console

=== RUN   TestInitArgs
04:43:32 panic: Calling v23 method before initializing the runtime with Init().
04:43:32 You should call Init from your main or test function before calling
04:43:32 other v23 operations.
04:43:32 
04:43:32 goroutine 539 [running]:
04:43:32 v.io/v23.(_initStateData).currentRuntime(0x1fc67a0, 0x0, 0x0)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/v23/model.go:365 +0xf5
04:43:32 v.io/v23.GetClient(0xc8204eeac0, 0x0, 0x0)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/v23/model.go:272 +0x51
04:43:32 v.io/x/ref/runtime/internal/naming/namespace.(_namespace).Resolve(0xc82054e6e0, 0xc8204eeac0, 0xc82009a050, 0x4d, 0xc8205f8150, 0x1, 0x1, 0x0, 0x0, 0x0)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/naming/namespace/resolve.go:118 +0xa59
04:43:32 v.io/x/ref/runtime/internal/rpc.(_client).tryCall(0xc820014cf0, 0xc8204eeac0, 0xc82009a050, 0x4d, 0xf81dd0, 0x9, 0xc8201152a0, 0x2, 0x2, 0xc8204dca00, ...)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:415 +0x1db
04:43:32 v.io/x/ref/runtime/internal/rpc.(_client).startCall(0xc820014cf0, 0xc8204eeac0, 0xc82009a050, 0x4d, 0xf81dd0, 0x9, 0xc8201152a0, 0x2, 0x2, 0xc8204dca00, ...)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:297 +0x7a7
04:43:32 v.io/x/ref/runtime/internal/rpc.(_client).Call(0xc820014cf0, 0xc8204ee940, 0xc82009a050, 0x4d, 0xf81dd0, 0x9, 0xc8201152a0, 0x2, 0x2, 0xc8204dc9f0, ...)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:194 +0x451
04:43:32 v.io/x/ref/runtime/internal/rpc.(_dischargeClient).fetchDischarges.func1(0xc8204dc340, 0xc8203a9200, 0xc8204ee740, 0x1, 0x1, 0xc8201acae0, 0xc8205d7ce0, 0x1, 0x1, 0x0, ...)
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/rpc/discharges.go:153 +0x5dc
04:43:32 created by v.io/x/ref/runtime/internal/rpc.(*dischargeClient).fetchDischarges
04:43:32    /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/runtime/internal/rpc/discharges.go:158 +0x7aa
...

@suharshs (RPC code churner)
@jatinlodhia (build cop)

**Comment by ghost** [comment]
This is due to the previous test not cleaning up after itself properly.  I have to sheepishly admit that I've seen this one, but it's because the old dispatch client doesn't look after it's goroutines carefully.  We solved this in the new RPC system and I've been avoiding fixing this.  If it's causing a lot of problems I'll take a look.

Thanks!

**Comment by caprita** [comment]
Only saw it once thus far, and since it sounds like it'll be fixed with the new RPC system, I'm going to close the issue. Will reopen if the frequency of occurrences spikes.

**Comment by caprita** [comment]
Happened again today FYI

https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/365/ARCH=amd64,OS=linux,TEST=vanadium-go-race-part3/console
