### ISSUE TITLE
oncall dashboard show stale primary oncall information

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#792]
For the current week, I took over jkline's oncall rotation, and made the change in //depot/ops/data/mail/configs/oncall.veyron

The oncall.corp UI shows the updated oncall owner (me), but the oncall dashboard UI still shows the previously scheduled owner (jlkine)

![dashboard](https://cloud.githubusercontent.com/assets/8231272/10493293/2d1761aa-7265-11e5-8d1a-c897573413c4.jpg)
![oncall](https://cloud.githubusercontent.com/assets/8231272/10493297/3366d8ec-7265-11e5-9e32-2e073f617144.jpg)

**Comment by jinjingforever** [comment]
Our tools read [this file](https://vanadium.googlesource.com/release.go.x.devtools/+/master/data/oncall.v1.xml) to get oncall data. Whenever the oncall schedule is updated, we need to update this file. The instruction can be seen at:

https://sites.google.com/a/google.com/v-prod/oncall/pager#TOC-Swap-Change-Oncall-Shift

Could you please try it? Thanks!

**Comment by caprita** [comment]
Thanks Jing. I ran gen_rotation_file and will wait for the update to propagate. I'm guessing we can easily automate running gen_rotation_file, just a matter of finding the time to do it; is there already an issue open for doing that?

The canonical information about updating the rotation is at https://sites.google.com/a/google.com/v-prod/oncall. I wasn't even aware of https://sites.google.com/a/google.com/v-prod/oncall/pager#TOC-Swap-Change-Oncall-Shift :-) I'll go ahead and move that information to https://sites.google.com/a/google.com/v-prod/oncall

**Comment by jinjingforever** [comment]
It is not that easy to automate because it requires prodaccess and access
to piper. But maybe long term credentials can help? I haven't tried it but
feel free to file an issue to me. Thanks!

**Comment by caprita** [comment]
Change to oncall.v1.xml has taken effect. Filed #799 to capture the automation feature request.
