### ISSUE TITLE
Verify ACL requirements for multi-user Syncgroups

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#797]
I believe multi-user Syncgroups require Read permissions for all participating users on one or more names/mount points. Verify this, and if it is an issue, we might like to default users mount points to have Read in '...' permissions. On the other hand, this may be too permissive; open to counterarguments.

**Comment by asadovsky** [comment]
Covered by documentation deliverables doc. Closing this issue. We may end up filing new issues for specific deliverables from the doc.
https://docs.google.com/document/d/1l3_NqBdnQ_miVaOOCsw5CkcdvdTxC-AImmqhdY7MNOg/edit#
