### ISSUE TITLE
remove need to manually update data/oncall.v1.xml after changing oncall.veyron

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#799]
Currently, the person who changes oncall.veyron in piper must then also change data/oncall.v1.xml in gerrit (/google/data/ro/users/ji/jingjin/gen_rotation_file helps create the edits). This is annoying, and easily overlooked. We have several options:
- automate updating of oncall.v1.xml; e.g., a borg or corp cron job can do it with a piper-enabled account (https://g3doc.corp.google.com/devtools/piper/g3doc/api/index.md?cl=head, https://wiki.corp.google.com/twiki/bin/view/Main/PerforceRoleAccounts) that can read oncall.veyron
- create unified tool around rotation changes: the tool would update both oncall.veyron and data/oncall.v1.xml; the operator running the tool would still have to deal with two CLs (one in piper, one in gerrit) but the tool would handle generating the changes, creating and sending the CLs out for review (the CLs could be marked 'submit automatically upon approval' to further reduce annoyance for operator
- get rid of need for data/oncall.v1.xml altogether; if the only consumers of this file are the jiri tool and the oncall dashboard, perhaps these can read the oncall.veyron file directly from piper: when the jiri tool is run by a real user, it will have piper access assuming the user has prodaccess'd. Likewise, the oncall dashboard site is visited by a user, the page can load the oncall.corp.google.com UI as an iframe.

The last option (if feasible) results in the simplest overall system. The first option keeps everything unchanged, but introduces new jobs we need to maintain. The second option is somewhere in between.

**Comment by jinjingforever** [comment]
This is now fixed. Now we have a Jenkins job [update-internal-oncall-file](https://veyron.corp.google.com/jenkins/job/update-internal-oncall-file/) that automatically updates the internal oncall rotation file every 30 minutes. Please see more comments there.
