### ISSUE TITLE
Create Syncslides app in Flutter/Syncbase

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#801]
Create the Syncslides in Flutter/Syncbase to find integration pain points and also evaluate possible needs for additional Rx layer or other helper APIs on top of Syncbase just for Flutter.

**Comment by aghassemi** [comment]
@asadovsky

**Comment by asadovsky** [comment]
Btw, we'll probably want to build SyncSlides in Flutter as well. I'm not sure whether that's easier or harder.
Eventually we'll probably want both, but there's a question of which to start with.
Then again, building the todos app should be pretty quick given that we can simply port a lot of code - the main work is in converting the UI components from React to Flutter and switching to a mobile-friendly design.

**Comment by asadovsky** [comment]
My inclination would be to start with SyncSlides, just because it's a more compelling demo of Vanadium and also because we already have a mobile-friendly design that uses Material Design.

@nadava @kenashcraft - thoughts?

**Comment by kenashcraft** [comment]
I also think you should do Syncslides instead of todos for the reasons Adam
gave.  Furthermore, Android/Java is better supported than JS by our team,
so unless and until we port Todos to Android, Syncslides tells a more
complete story.

**Comment by aghassemi** [comment]
Sounds good. Updated the issue to reflect.
Doing Syncslides in Flutter/Dart can create a nice comparison for both our Dart v.s. Java API and also Android Java development v.s. Flutter development in general. Also gives us iOS Syncslides!

One issue is that we don't have identity and regular RPCs in Mojo yet, so we can't talk to mounttables and can't do auth yet. V23 Proxy is being worked on and seems close to be done to allow RPCs and we need to figure out auth stuff anyway, so this can help drive more requirements for Mojo.

**Comment by nadava** [comment]
+1 to Syncslides for all these reasons and a few more...

**Comment by asadovsky** [comment]
Ali's working on this app. Closing this issue as it's generic.
