### ISSUE TITLE
Tutorials: js-node and js-web are failing during browserify

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#804]
The reason is due to a package change here: https://github.com/substack/insert-module-globals/issues/55

Since we access them via browserify, it looks like it isn't trivial to pin their package version down.

Note: This may affect other JS projects that use browserify.

**Comment by afandria** [comment]
@aghassemi @nlacasse FYI, since you also have JS projects.

This has been occurring for the past ~13 hours.

**Comment by parshap** [comment]
@afandria: This should be fixed now in `insert-module-globals@6.6.3`. A fresh install of browserify will automatically get this update.

**Comment by afandria** [comment]
Thank you, it is fixed!
