### ISSUE TITLE
io.v.v23.syncbase.nosql.NoSql:58  - conditional always true

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#811]
If I'm reading this line correctly,

```
if (!e.getID().equals(Errors.CONCURRENT_BATCH)) {
```

the condition is trying to compare `String` `getID` with `IDAction` `CONCURRENT_BATCH`.

I was just using this line as an example for my own Java `VException` ID detection and noticed that mine wasn't working as expected.

It might be a bit challenging to find other instances of this error and prevent it in the future. Perhaps we should opt for a more strongly typed API than depending on Object.equals.

**Comment by AsturaPhoenix** [comment]
What was the reasoning behind making these all one exception rather than individually typed?

**Comment by asadovsky** [comment]
@spetrovic77 - IIRC at this week's status meeting you mentioned that you're switching these over to having different generated exception types for each verror type?

**Comment by spetrovic77** [comment]
Fixed at head.  If you re-run with --refresh-dependencies, you should get the new error code.
