### ISSUE TITLE
discovery tests fail race-condition checker

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#817]
v.io/x/ref/lib/discovery/util failed the race-condition checker, log output is:

18:33:51 fail v.io/x/ref/lib/discovery/util
18:33:51 === RUN   TestNetworkChange
18:33:51 ==================
18:33:51 WARNING: DATA RACE
18:33:51 Read by goroutine 10:
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChange()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:99 +0xcfd
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 
18:33:51 Previous write by goroutine 29:
18:33:51   v.io/x/ref/lib/discovery/util_test.(_mockServer).WatchNetwork()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:40 +0x37
18:33:51   v.io/x/ref/lib/discovery/util.AdvertiseServer.func1()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:38 +0x77
18:33:51 
18:33:51 Goroutine 10 (running) created at:
18:33:51   testing.RunTests()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:561 +0xaa3
18:33:51   testing.(_M).Run()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:494 +0xe4
18:33:51   main.main()
18:33:51       v.io/x/ref/lib/discovery/util/_test/_testmain.go:58 +0x20f
18:33:51 
18:33:51 Goroutine 29 (running) created at:
18:33:51   v.io/x/ref/lib/discovery/util.AdvertiseServer()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:58 +0x367
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChange()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:88 +0x721
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 ==================
18:33:51 ==================
18:33:51 WARNING: DATA RACE
18:33:51 Write by goroutine 28:
18:33:51   v.io/x/ref/lib/discovery/plugins/mock.(_plugin).UnregisterAdvertisement()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/plugins/mock/mock.go:138 +0x3f7
18:33:51   v.io/x/ref/lib/discovery/plugins/mock.(_plugin).Advertise.func1()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/plugins/mock/mock.go:31 +0xc2
18:33:51 
18:33:51 Previous read by goroutine 30:
18:33:51   v.io/x/ref/lib/discovery/plugins/mock.(_plugin).Scan.func1()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/plugins/mock/mock.go:42 +0xab
18:33:51 
18:33:51 Goroutine 28 (running) created at:
18:33:51   v.io/x/ref/lib/discovery/plugins/mock.(_plugin).Advertise()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/plugins/mock/mock.go:32 +0x109
18:33:51   v.io/x/ref/lib/discovery.(_ds).Advertise()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/advertise.go:65 +0x7f2
18:33:51   v.io/x/ref/lib/discovery/util.advertise()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:70 +0x35c
18:33:51   v.io/x/ref/lib/discovery/util.AdvertiseServer()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:30 +0x17d
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChange()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:88 +0x721
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 
18:33:51 Goroutine 30 (running) created at:
18:33:51   v.io/x/ref/lib/discovery/plugins/mock.(_plugin).Scan()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/plugins/mock/mock.go:53 +0x8a
18:33:51   v.io/x/ref/lib/discovery.(_ds).Scan()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/scan.go:36 +0x3ed
18:33:51   v.io/x/ref/lib/discovery/util_test.scan()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:164 +0xdc
18:33:51   v.io/x/ref/lib/discovery/util_test.scanAndMatch()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:148 +0x337
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChange()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:89 +0x783
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 ==================
18:33:51 --- PASS: TestNetworkChange (0.07s)
18:33:51 === RUN   TestNetworkChangeInstanceUuid
18:33:51 ==================
18:33:51 WARNING: DATA RACE
18:33:51 Read by goroutine 55:
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChangeInstanceUuid()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:131 +0x828
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 
18:33:51 Previous write by goroutine 73:
18:33:51   v.io/x/ref/lib/discovery/util_test.(_mockServer).WatchNetwork()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:40 +0x37
18:33:51   v.io/x/ref/lib/discovery/util.AdvertiseServer.func1()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:38 +0x77
18:33:51 
18:33:51 Goroutine 55 (running) created at:
18:33:51   testing.RunTests()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:561 +0xaa3
18:33:51   testing.(*M).Run()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:494 +0xe4
18:33:51   main.main()
18:33:51       v.io/x/ref/lib/discovery/util/_test/_testmain.go:58 +0x20f
18:33:51 
18:33:51 Goroutine 73 (running) created at:
18:33:51   v.io/x/ref/lib/discovery/util.AdvertiseServer()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise.go:58 +0x367
18:33:51   v.io/x/ref/lib/discovery/util_test.TestNetworkChangeInstanceUuid()
18:33:51       /home/veyron/workspace/rc/root/release/go/src/v.io/x/ref/lib/discovery/util/advertise_test.go:123 +0x5c2
18:33:51   testing.tRunner()
18:33:51       /home/veyron/workspace/rc/root/profiles/go/amd64_linux/f2e4c8b5fb3660d793b2c545ef207153db0a34b1/src/testing/testing.go:456 +0xdc
18:33:51 ==================
18:33:51 --- FAIL: TestNetworkChangeInstanceUuid (3.41s)
18:33:51    advertise_test.go:133: match failed; got {[23 180 114 61 209 26 65 197 155 218 92 236 107 112 96 39]  v.io/v23/a map[] [/@6@@addr2:123@@00000000000000000000000000000000@m@@@]}, but wanted {[]   map[] [/@6@@addr2:123@@00000000000000000000000000000000@m@@@]}

**Comment by jhahn21** [comment]
should be fixed by https://vanadium-review.googlesource.com/#/c/16947
