### ISSUE TITLE
"jiri project shell-prompt" is very slow

### ISSUE THREAD

**Issue by bprosnitz** [vanadium/issues#818]
It takes 2.1 seconds to run on my machine

**Comment by afandria** [comment]
It's slow for me too. @nlacasse

**Comment by nlacasse** [comment]
I'm working on various performance improvements to jiri.  This one is on my radar.

**Comment by nlacasse** [comment]
https://vanadium-review.googlesource.com/release.go.jiri

Before this change, `jiri project shell-prompt` takes 1.4 seconds on my machine.

After the change, it takes 0.2 seconds.
