### ISSUE TITLE
TestDatabaseCreateNameValidation is flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#825]
+cc @spetrovic77 @hpucha @rdvg @suharshs 

This test fails occasionally on Jenkins, e.g.:
https://veyron.corp.google.com/jenkins/job/vanadium-go-race/815/OS=linux,P=6/console
https://veyron.corp.google.com/jenkins/job/vanadium-go-race/848/OS=linux,P=6/console

I've tried reproducing it locally, to no avail. More specifically, I ran this command:

```
for i in {1..20}; do jiri go test v.io/v23/syncbase/nosql -test.run=TestDatabaseCreateNameValidation; done
```

The test passed 20 times, both on my Macbook Pro and on my Linux workstation (over ssh).

@rogulenko says he has been able to reproduce locally - Sergey, can you share any pertinent details of your setup?

@mattr-google says "This error means that the channel was closed while we still trying to write the request to the wire ... I'm surprised we don't see a long message explaining why the flow closed."

**Comment by rogulenko** [comment]
Steps to reproduce:
apply v.io/c/17032
jiri go test v.io/v23/syncbase/nosql -v -run TestDatabaseCreateNameValidation
wait for computer to give up)

My computer gives up after 30 seconds doing ~1000 attempts.

**Comment by rogulenko** [comment]
Error stack trace:
<rpc.Client>"/@6@tcp@127.0.0.1:59439@@83857425e22a72606c565ac6a634359e@s@root/server@@/a/안녕하세요".Create: Bad protocol or type: failed to encode arg #1: EOF:
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:836: v.io/x/ref/runtime/internal/rpc.(_flowClient).close
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:865: v.io/x/ref/runtime/internal/rpc.(_flowClient).start
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:584: v.io/x/ref/runtime/internal/rpc.(_client).tryCall
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:296: v.io/x/ref/runtime/internal/rpc.(_client).startCall
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:193: v.io/x/ref/runtime/internal/rpc.(_client).Call
release/go/src/v.io/v23/services/syncbase/nosql/service.vdl.go:1971: v.io/v23/services/syncbase/nosql.implDatabaseClientStub.Create
<autogenerated>:390: v.io/v23/services/syncbase/nosql.(_implDatabaseClientStub).Create
release/go/src/v.io/v23/syncbase/nosql/database.go:120: v.io/v23/syncbase/nosql.(_database).Create
<autogenerated>:44: v.io/x/ref/services/syncbase/testutil.(_database).Create
release/go/src/v.io/x/ref/services/syncbase/testutil/layer.go:109: v.io/x/ref/services/syncbase/testutil.TestCreateNameValidation
release/go/src/v.io/v23/syncbase/nosql/client_test.go:68: v.io/v23/syncbase/nosql_test.TestDatabaseCreateNameValidation
profiles/go/amd64_linux/cc6554f750ccaf63bcdcc478b2a60d71ca76d342/src/testing/testing.go:457: testing.tRunner
profiles/go/amd64_linux/cc6554f750ccaf63bcdcc478b2a60d71ca76d342/src/runtime/asm_amd64.s:1697: runtime.goexit
  ----- chained verror -----
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:864: v.io/x/ref/runtime/internal/rpc.(_flowClient).start
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:584: v.io/x/ref/runtime/internal/rpc.(_client).tryCall
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:296: v.io/x/ref/runtime/internal/rpc.(_client).startCall
release/go/src/v.io/x/ref/runtime/internal/rpc/client.go:193: v.io/x/ref/runtime/internal/rpc.(_client).Call
release/go/src/v.io/v23/services/syncbase/nosql/service.vdl.go:1971: v.io/v23/services/syncbase/nosql.implDatabaseClientStub.Create
<autogenerated>:390: v.io/v23/services/syncbase/nosql.(_implDatabaseClientStub).Create
release/go/src/v.io/v23/syncbase/nosql/database.go:120: v.io/v23/syncbase/nosql.(_database).Create
<autogenerated>:44: v.io/x/ref/services/syncbase/testutil.(*database).Create
release/go/src/v.io/x/ref/services/syncbase/testutil/layer.go:109: v.io/x/ref/services/syncbase/testutil.TestCreateNameValidation
release/go/src/v.io/v23/syncbase/nosql/client_test.go:68: v.io/v23/syncbase/nosql_test.TestDatabaseCreateNameValidation
profiles/go/amd64_linux/cc6554f750ccaf63bcdcc478b2a60d71ca76d342/src/testing/testing.go:457: testing.tRunner
profiles/go/amd64_linux/cc6554f750ccaf63bcdcc478b2a60d71ca76d342/src/runtime/asm_amd64.s:1697: runtime.goexit

**Comment by asadovsky** [comment]
I've confirmed that this reproduces it for me as well, typically after 1000's of attempts. Also, the corresponding table test does not fail, even with many 1000's of attempts.

**Comment by suharshs** [comment]
The fix has been submitted. https://vanadium-review.googlesource.com/#/c/17050/
