### ISSUE TITLE
Vanadium Installation Instructions Out of Date

### ISSUE THREAD

**Issue by mcpio** [vanadium/issues#828]
When attempting to install Vanadium according to the instructions in https://github.com/vanadium/docs/blob/master/installation.md, I encountered the following error when running the **jiri go install v.io/...** command:

`ERROR: "=amd64-linux@" for "base" is not available or not installed, use the "list" command to see the installed/available profiles.`

With Sergey's help, I was able to fix the problem by running **jiri v23-profile install base** prior to the command above.

**Comment by asadovsky** [comment]
Thanks for the report. Indeed our GitHub install instructions are out of date. I'll take a look.

**Comment by mcpio** [comment]
Also, the link to the Vanadium Chrome Extension 404's.

According to the todos app instructions, the link should be https://github.com/vanadium/docs/blob/master/tools/vanadium-chrome-extension.md instead of https://github.com/vanadium/docs/blob/tools/vanadium-chrome-extension.md

**Comment by asadovsky** [comment]
Fixed the broken link in this CL: https://vanadium-review.googlesource.com/#/c/17088

@cosnicolaou is going to send a CL to update the stuff around profile installation.

**Comment by asadovsky** [comment]
All fixed now.
