### ISSUE TITLE
Syncbase+mojo: List{Apps,Databases,Tables} should return strings, not objects

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#829]
Syncbase List{Apps,Databases,Tables} returns name strings in Go but in JS or Dart we return actual objects. 

Why don't we return actual types in Go instead of names? I assume common case is to use that name to get the actual struct anyway.

**Comment by asadovsky** [comment]
In javascript we return string names, not objects. This is by design, to keep methods simple and orthogonal; it's trivial to convert names to objects, e.g. in javascript you would just use map(). We should change the dart/mojo API to return strings.

**Comment by asadovsky** [comment]
Fixed. Fix was published in syncbase dart pkg version 0.0.13.
