### ISSUE TITLE
Syncbase: Must specify --name parameter to syncbased or no data will sync

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#832]
I am using a setup with Croupier here. This involves 2 or more Android phones using Syncbase via Mojo. IIRC, this has also affected @AsturaPhoenix when writing the Travel app.

A starts up the app and writes a value to a unique row in a table. A also creates a Syncgroup to share that table. It has included the --name parameter when creating syncbased.

syncbased name is croupier
Syncgroup name is <MT_NAME>/croupier/%%sync/discovery

B starts up the app, also writing a value to a unique row in a table. B joins the Syncgroup and omitted the name parameter from its syncbased.

Importantly, even though A and B can see each other (via polling, each can confirm that there are 2 members in the syncgroup), they cannot share data with each other (sync does not occur).

When B does use a non-empty --name parameter (like `foo2`), sync does work.

@asadovsky @ivanpi-mtv @hpucha

**Comment by asadovsky** [comment]
Bindu, is this a known issue / any idea why it's happening? It seems the --name flag should be completely irrelevant, except for the device that's mounting at the sgName.

**Comment by asadovsky** [comment]
Also @rdvg

**Comment by hpucha** [comment]
This looks like the same issue that Bogdan ran into.

See https://vanadium-review.googlesource.com/17147

Alex, can you confirm this is working for you now.

**Comment by afandria** [comment]
We pushed a new syncbase package. I tried this on 3 devices, so I believe the unnamed case works now. Thanks!
