### ISSUE TITLE
Dart Mojo Discovery Client

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#835]
A simple client library for discovery was written for Croupier. This could be moved to the Dart package in mojo.discovery project.

Another thing to consider is having the client wrapper return a stream of events rather than taking in a custom ScanHandler object. The reason for this is to align the API with Syncbase's Watch API.

@nlacasse @bjornick

**Comment by bjornick** [comment]
On the flip-side we'd need to write this code in all the languages, which is something we have been avoiding as much as possible.

**Comment by aghassemi** [comment]
I think I will do this soon.

**Comment by aghassemi** [comment]
https://vanadium-review.googlesource.com/#/c/19068/
