### ISSUE TITLE
--java-out-pkg option for vdl gradle plugin

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#836]
@sjamesr 

For the reader app, the vdl files are shared between the Web and Android clients.
The project directory structure looks as follows:

```
reader
reader/android
reader/vdl <-- all the vdl files are here.
reader/web
```

I want to generate the .java files from the .vdl files into `reader/android/app/generated-src/vdl/io/v/android/apps/reader` directory with the package name `io.v.android.apps.reader`.

The command line vdl tool allows this with the `--java-out-pkg="vdl->io.v.android.apps.reader"` option, but the vdl gradle plug-in does not seem to have this option.

It would be nice if I can write something like this in the gradle build script:

```
vdl {
    inputPaths += '../..'
    packageTranslations += 'vdl->io.v.android.apps.reader'
}
```

**Comment by sjamesr** [comment]
Hey YoungSeok,

Can you try patching in https://v.io/c/17115 and let me know if it works for you? You should be able to use the syntax you described above.

Thanks,
James

**Comment by yyoon** [comment]
Well, I'm not sure how I can build and use the gradle plug-in locally.
Could you please give me a bit more instructions?
After patching the code, what command should I run?

Thanks for the quick response, BTW!

**Comment by sjamesr** [comment]
Hi YoungSeok, sorry for the delay.

If you run ./gradlew --refresh-dependencies, you should get a new version of the plugin with the patch applied. Unfortunately I'm not sure of the best way to test plugin changes without publishing them to some (possibly local) Maven repository.

**Comment by yyoon** [comment]
That's alright. Can I just wait until this CL is submitted and published to the Maven repo then?

**Comment by sjamesr** [comment]
I published a version of the plugin with this patch and tried it out, it
should work for you too. Just make sure to run with --refresh-dependencies
to get the latest plugin version.

**Comment by yyoon** [comment]
Yep, it's working as expected.
