### ISSUE TITLE
Syncbase Mojo db.exists hanging during syncgroup creation

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#842]
My scenario is that I
- mount syncbased on a mounttable
- join or create a syncgroup at the start of my app (underneath the same syncbased)
- I also write to syncbase (independent of whether the group is successfully joined or created).

This normally is fine.

However, when the mounttable is down, I find that my app cannot write to syncbase anymore (because I block on a 'db.exists' call when retrieving a table handle). It takes ~90 seconds for syncbase to realize that the mounttable doesn't exist, but I would have expected local operations to occur smoothly regardless of the syncgroup creation/join attempts.

This may not be Mojo related.

@ivanpi-mtv

**Comment by aghassemi** [comment]
Might be a lock we are holding while connecting to  the Mount-table that prevents other DB operations?
- @hpucha

**Comment by afandria** [comment]
I think this also happens if the mounttable is there, but the "cloud" syncbase instance for that syncgroup is not present.

**Comment by hpucha** [comment]
Is it just the db.exists call that is hanging? Or are all local operations stuck?

Sync doesn't hold any locks in the data path. 

Not sure how the local app communicates with Syncbase in the mojo world. I assume it doesn't use the mount table/syncbase name at all?

If the mount table is down, sync will be stuck but not local operations.
If the cloud syncbase is down, only join requests should be stuck, and not even sync.

Is it possible to get any logs?

**Comment by asadovsky** [comment]
@afandria, are you using the mounttable name to bind to your syncbase instance? If so, and if the mounttable is down, then any RPCs you make to syncbase will fail, and currently we do not override any timeouts in the client, so it would have whatever's the default timeout (IIRC, several minutes). I don't think this is in any way related to sync or syncgroups. Maybe I'm misunderstanding the issue, though?

**Comment by afandria** [comment]
I haven't had a chance to update this recently, but I can clarify.

When the mounttable is down, it is completely fine for the syncgroup join/create to hang. What I don't expect is for unrelated calls, like db.exists to hang. These calls should happen independently, but I think my app is hanging because of an unexpected shared lock.

**Comment by hpucha** [comment]
I think what Adam and I are wondering is how does the mojo app talk to the local syncbase. Is it using a a Vanadium name anywhere?

**Comment by asadovsky** [comment]
Oh, hmm. I didn't notice that this was mojo-specific. On mojo, the local app (dart) talks to the local syncbase over mojo IPC, and there's no name resolution or Vanadium RPCs involved in these local ops. So, a db.exists() call should always work quickly. Alex, if/when you have this in some reproducible state, let me know and I can take a look with you.

**Comment by afandria** [comment]
I've sent some logs over offline.

Note: It looks like I've confused `db.exists` with `app.exists`, since both occur in the same function.

**Comment by afandria** [comment]
An update to this. We think that Mojo Go seems to only process one command at a time. There is a new API being proposed [here](https://codereview.chromium.org/1458583005/) that would allow asynchronous handling of requests.

**Comment by asadovsky** [comment]
We have an email thread with @rogulenko about this. Hopefully we can get the change in soon, and then I'll update Syncbase's mojo_main to use the goroutine-per-request model.

**Comment by asadovsky** [comment]
Discussion is still ongoing. I believe everyone here is on the thread.
For now, please try patching https://v.io/c/18070 and let me know if it helps.

**Comment by aghassemi** [comment]
@asadovsky Everything is a lot snappier with https://v.io/c/18070 and we don't block on joining a syncgroup anymore as well. Can we merge it until the full solution makes it to mojo?

**Comment by asadovsky** [comment]
Yes, we can merge it. +2? :)

--Adam

**Comment by afandria** [comment]
If it's submitted, please publish a new Syncbase package too!

**Comment by aghassemi** [comment]
0.17 has this change

**Comment by asadovsky** [comment]
Closing.
