### ISSUE TITLE
Croupier: Sorting required for WatchChange

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#844]
It's possible for some WatchChange to have continued, which means that a group of changes were bundled into the same "batch". The order is not guaranteed to be timestamp order, which is quite surprising and dangerous for my app.

**Comment by afandria** [comment]
@ivanpi-mtv

**Comment by afandria** [comment]
This has gotten even more important for Solitaire. If you play too quickly, the odds are very high that the watch changes get bundled, and you see the updates out of order.

**Comment by asadovsky** [comment]
@ivanpi-mtv have you filed an issue for this from the "usability fixit"? (Can we merge this issue into that one?)

**Comment by asadovsky** [comment]
@afandria Do you have a workaround for now?

**Comment by afandria** [comment]
Yes, I do. My keys happen to have timestamps inside them, so aggregating the WatchChanges in a list and manually sorting is possible for me. Then I can act upon the sorted list.
