### ISSUE TITLE
Tests: prevent warnings about "accepting incoming network connections" on OS X

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#847]
@mattr-google @asimshankar @jhahn21 

I noticed that when I run "jiri go test v.io/v23/... v.io/x/ref/..." on my OS X laptop, I get lots of warning popups about accepting incoming network connections. These are typically due to tests listening on public IPs instead of just the loopback address.

With Asim and Matt's help, I fixed a lot of these (e.g. https://v.io/c/17218), but there are a few left:
- v.io/x/ref/lib/discovery/plugins/mdns
- v.io/x/ref/runtime/internal/rpc
- v.io/x/ref/runtime/internal/rpc/test (LOTS of warning popups)
- v.io/x/ref/services/syncbase/vsync (due to discovery)

For these, it wasn't immediately obvious to me how to prevent the warnings, and indeed for the RPC tests it might be difficult since perhaps what we're trying to test depends on changing IPs (at least for the roaming tests). Matt, Asim, Jungho - any ideas?

Also: I wonder if there's some way we could instrument our code so that listening on a public IP fails by default if run from a test, unless some special flag/global is set to disable the check. This would help prevent future breakages, e.g. due to someone accidentally using v23.Init() instead of test.V23Init(). Thoughts on this?

**Comment by ghost** [comment]
@asimshankar Can you verify that this is still the case?

**Comment by asimshankar** [comment]
There are still a few tests that seem to be doing this, I will add sorting them out to my TODO list.

Assigning to myself since I seem to use OS X way more often than @mattr-google

**Comment by asimshankar** [comment]
Obsolete
