### ISSUE TITLE
Network Interface details

### ISSUE THREAD

**Issue by SagarPuneria** [vanadium/issues#851]
First i want to say sorry,for my terrible english.

Could someone please help me on how to get network interface details for every interfaces like eth0, lo, wlan0......etc .so that i can implement utilities for retrieving following network interface details as:
a.) IP Address Type
b.) IP Address 
c.) Gateway,Default Gateway and
d.) MAC Address for every interface like eth0, lo, wlan0......etc

**Comment by ghost** [comment]
Hello,

Sorry this bug was missed when you filed it.  If you're still interested could you give me some more information on what you are trying to do?

Are you trying to get this information from the Vanadium RPC system?  Are you trying to use this information to impact how RPCs are transmitted?

**Comment by SagarPuneria** [comment]
Am closing this issue.
