### ISSUE TITLE
Syncbase Feature Request to return ResumeMarker from write operations

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#853]
I'm experimenting with binding an Android TextView to a Syncbase row. In the current flavor of the binding, there is the edge case where quick successive updates in response to user input can result in multiple Syncbase put operations having been completed prior to the WatchChange from the first put operation having come back, which can result in UI stutter as the late watch event(s) "revert" the TextView briefly.

I have a few options so far for dealing with this:
1. After the put, start a new watch stream with an initial read batch (clean, but not ideal).
2. Have put return a ResumeMarker I can watch for, and ignore watch changes (for the pertinent row) until I see the ResumeMarker. This requires a guarantee that the ResumeMarker will eventually be seen in a WatchChange, and although in the case of single-row watches it is pretty clean, larger watches would need additional application logic if they wish to accomplish the same thing. This could be factored into a utility library.
3. Debounce updates from watch for a short time after a user input. This is my current strategy as it has UI applications, but it is latency-sensitive (albeit local latency, which has room for improvement on Android) so it is not perfect.
4. Disallow bidirectional binding, and require that TextViews be in "edit mode" or "view mode". Although the simplest option which will actually probably be the default for TextView bindings, it's not nice to just eliminate this feature. Also, unless entering "view mode" triggers a new watch, this may still experience stutter from rapid mode transitions (which granted are highly unlikely).

**Comment by AsturaPhoenix** [comment]
FYI @ivanpi-mtv and I discussed this and due to the extra caveats around option 2, he is recommending option 1 instead. However, he has also mentioned that timestamps may eventually be exposed through watch, and that may be an alternative mechanism we could use if canonical timestamps can be queried from the DB with sufficient resolution. Sequence IDs may be more useful, and we would probably still want to be able to attain the sequence ID for a particular modification (put/delete/commit) we made.

**Comment by asadovsky** [comment]
Hi Ross,

If changes to the text displayed in this text box are only being made on the local device, I would recommend option (4). That's also what React does:
https://facebook.github.io/react/docs/forms.html#uncontrolled-components
I would imagine that Flutter provides a similar mechanism, but it would be interesting to chat with them to find out. (We used this approach in the todos app, to prevent actively-being-edited text fields from flickering when unrelated updates arrived via sync.) Happy to chat more about this in person.

On the other hand, if you are trying to support concurrent edits to the same text field (with some edits arriving via sync), you're doing something much, much more complicated, and you'll need a UI widget that has Google-Docs-style smarts baked into it. However, given that Syncbase doesn't currently support Docs-style concurrent editing of ordered lists (note, strings are just an ordered list of bytes), I'm guessing this is not what you're trying to do.

**Comment by asadovsky** [comment]
Note, one thing that helped in the case of the todos app is that a focused field is a different UI component than a non-focused field - i.e. when a field switched from non-focused to focused or vice versa, that's a state change. While a field is non-focused, updates to the value arriving via sync cause the text value to change immediately in the UI. While a field is focused, updates to the value arriving via sync cannot cause the text value to change in the UI. Perhaps a similar strategy around managing the "focus state" of the field would help you get the user experience you're aiming for?

**Comment by AsturaPhoenix** [comment]
It's certainly what needs to happen to support strategy 4. I am indeed inclined to wait for Syncbase CRDT support before trying to offer true collaborative edit. However, it seems to me that even if Syncbase supports collaborative editing first-class, getting old updates after subsequent local edits would still be an issue (unless an entirely new API to expose this is intended). What are your plans like for this?

**Comment by asadovsky** [comment]
For collaborative text editing, there'd need to be a tight coupling between UI widget state and the state known to Syncbase on the local client. I think it's plausible that we'd end up providing our own UI widgets or plugins for developers to use. If local Syncbase RPC latency is too high to allow for UI widget state to be tightly coupled to local Syncbase state, we may have to resort to something more sophisticated, e.g.
https://hal.inria.fr/hal-00957167/document (with OT between UI and local Syncbase, and CRDT between Syncbase instances). I hope it doesn't come to that. :)

**Comment by ivanpi-mtv** [comment]
Strategy 4 - #919 
Strategy 1 - #917

**Comment by asadovsky** [comment]
Covered by issues that Ivan filed; closing.
