### ISSUE TITLE
Sync requires pre-existing hierarchy

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#857]
This issue was originally reported by @jxson. If a Syncbase instance is missing any of the app/db/table hierarchy, sync does not happen. Normally this isn't much of a problem as an app needs to create hierarchy to operate anyway, but I just ran into a case where an app that creates its table lazily tries to start a watch before the table exists.

Starting the watch first calls a db.getTable(...).get to fetch initial data, which fails with NO_EXIST, and the app falls back on defaults and starts the watch. However, the watch never produces anything since sync doesn't occur.

One possible solution might have been to lazily create the table during the initial query, but that query occurs in a read batch (with getResumeMarker) and table creation cannot currently occur in a batch.

The app is working around this by ensuring existence of the table prior to the batch.

**Comment by kenashcraft** [comment]
Our intended use is that there are a fixed number of tables and that the app ensure all of those tables exist when it starts up.  For example, there would be "Customers" and "Orders" tables, not a table per customer.

Is it not possible to create all the tables at app start up?

**Comment by hpucha** [comment]
Top of my head, I believe sync should be happening. There may be no way to get to the data. 

We perhaps ought to stop sync from proceeding in such a case. But currently there are no checks in place that should prevent from syncing.

**Comment by AsturaPhoenix** [comment]
@kenashcraft That's how I was avoiding this scenario in the Travel app. The Baku Toolkit attempts not to force this assumption on the application, but if it's reasonable then I can require that apps pre-define their hierarchy.

@hpucha That is a fair assessment. In that case it is likely that even though sync is happening, a watch on the table name without the pre-existing table just doesn't work.

**Comment by AsturaPhoenix** [comment]
@kenashcraft I am hesitant to force the pre-definition requirement because in practice lazy creation is otherwise sufficient. What is the rationale behind disallowing table creation within a batch?

**Comment by kenashcraft** [comment]
We disallow creation of a table within a batch because we were thinking about SQL-like functionality that would be hard to support.

@jakline do you have thoughts?

**Comment by jakline** [comment]
I think it's reasonable to ask that create table can be part of a write batch (although I don't think it is a must have).  I don't think it's reasonable to create a table if a watch or a query mentions a table that doesn't exist.  A "cannot access table" seems like the write error for that.  One wouldn't expect a change in the database in a read-only batch.  Even if it were a writable batch, watch and query are inherently read-only.  Also, what if one misspells the table name?  He wouldn't want a table to be created.

Having new tables sync to devices that don't yet have that table is also reasonable.  It sounds like Bindu is saying that should work.

**Comment by asadovsky** [comment]
As far as syncing goes, I'd be inclined to make sync fail if the syncgroup spec includes a table that doesn't exist. Somewhat annoyingly, this would also mean disallowing table delete if the syncbase instance is a member of any syncgroups that include that table.

OTOH, if we allow syncing a syncgroup that references a non-existent table, the "symmetric" thing to do would be to allow deleting that table. But would deleting the table wipe all the data under it? If not, would it wipe data not associated with any syncgroup? Or, would it leave all the associated syncgroups? (Even if they include other tables that still exist?)

Sigh, tables. =/ If we are anyways moving towards allowing multiple types per table, perhaps we should just allow multiple types per database and be done with it?

**Comment by AsturaPhoenix** [comment]
That does seem indicated by the Syncbase feedback about the difficulty of using the app/db/table hierarchy. On the other hand, the reader app recently started making good use of multiple tables.
- @jxson , @yyoon

Certainly modeling watch as a db operation but only allowing one table for the watch seems asymmetric, exacerbated by the ambiguous expectations in the cases where that table doesn't exist at the beginning of the watch or is deleted some time during the watch.

I would imagine that allowing multiple tables per watch + table creation/deletion within a batch + syncing table creation/deletion + surfacing table creation/deletion in a watch would be one consistent set of operations to allow. Otherwise I would imagine we would want watch to be a table-level operation so that we couldn't possibly start a watch without the table existing, but that strategy doesn't allow for the vision @asadovsky previously mentioned of someday surfacing syncgroup changes in watch. There's also the possibility of offering both kinds of watches, but that seems like extra work for not so much benefit.

**Comment by AsturaPhoenix** [comment]
@jxson, and @yyoon, it seems like the reader app could work just as well with the new tables encoded as key prefixes, wouldn't it?

**Comment by asadovsky** [comment]
Yes, the current watch API needs to change if we keep tables around - most likely we'd have it take a set of {table,prefix} pairs, i.e. the same thing as what's in a syncgroup spec.

I don't think syncing table creation/deletion makes sense as it stands - tables sit outside the scope of what's covered by syncgroups.

We wouldn't need two kind of watches in order to surface syncgroup changes. Most likely, what we'd do is: if a syncgroup spec overlaps in any way with the client's watch spec, we'd include the syncgroup's events in the watch stream. So for example, if you are watching {table:foo, prefix:bar}, and some syncgroup includes {table:foo, prefix:barbaz} or {table:foo, prefix:b} (but not {table:foo, prefix:baz}), we'd include that syncgroup's events in the watch stream.

**Comment by yyoon** [comment]
@AsturaPhoenix Yes, it would be functionally equivalent. However, I'm not sure if those two would have the same level of usability. For now, the tables are separate entities in the Vanadium namespace browser, which is really nice for debugging. Also, it could be tedious to prefix the key names with the conceptual table names every time I want to get a row from the database.

**Comment by AsturaPhoenix** [comment]
@yyoon I was actually running into the tedious part with key prefixes as well. I think general views might go down well as a client library extension.

**Comment by aghassemi** [comment]
I ran into this today and unfortunately it took me longer than should have to figure out why part of my data is not syncing. I was lazily creating tables (whether that's the right thing to do or not I think is irrelevant to my point) and the other device happened not to have one of the tables that was part of the Syncgroup.

I think the source of my issue was lack of visibility into the syncing process. I am running at default log level and normally when syncing fails, I see errors like `E1122 03:39:44.900039   13500 funcs.go:94] sync: syncClock: couldn't connect to peer {19b61392e51cd809 [] []}` in my stdout. This time I was not seeing anything and was assuming something is wrong with my code where I spent most of the time debugging.

Maybe if we log sync issues at higher log levels (error?) or surface issues like this through the API and into the application*, it mitigates some of the visibility issues.

(*Maybe watch() should expose sync related errors/warnings in a way that's hard to ignore - kind of like what Glob does. In Dart/JS for instance we can have watch return three streams: changes, errors and warnings. Then applications can handle these issues better by, for instance,  notifying the user that their data might be out of sync when they see errors and to log warning using their own environment's logging mechanism. I personally never want to look at Vanadium logs. I don't think we can expect someone writing a Flutter/Syncbase app in Dart to be constantly looking at our logs to identify issues either...)

**Comment by asadovsky** [comment]
We definitely intend to fix this, and we do not expect our eventual Syncbase users to look at logs to debug problems. Btw, we have more work than people so if anyone would like to pitch in to improve Syncbase (usability or otherwise), let me know and I can help you get going.

A couple side notes:
- Please do pre-create your hierarchy, including all tables. If you are dynamically creating tables based on user actions, chances are those should be rows / row-ranges, not tables.
- Our current watch API only allows watching a single table. We do plan to change this, but I can't promise it'll happen in the next few weeks. (Is this a problem for SyncSlides?)

**Comment by aghassemi** [comment]
It is a nice-to-have for SyncSlides, I am watching each table separately and its fine as I run the exact same code regardless of the tables I get the changes from.

**Comment by asadovsky** [comment]
Assigning to Ivan, as it's somewhat related to #922.

**Comment by aghassemi** [comment]
Closing in favour of https://github.com/vanadium/issues/issues/889
