### ISSUE TITLE
Keys returned from queries have double quotes in the actual string value

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#860]
Not sure if Mojo/Dart specific or not but when doing a "SELECT k, v FROM table", in the results array, the first item which is the key actually has a double quote character in the string. 

@asadovsky @jakline

**Comment by asadovsky** [comment]
Only for the first result's key? Or for every result's key? Is the double-quote character always in the same place within the string? (Can you show an example of the output?)

**Comment by aghassemi** [comment]
in all keys, so for `"SELECT k, v FROM table"` I get an `List<List<String, Bytes>>` result so if I do

`var row2 = result[1]`
`var row2col1 = row1[0]`

`row2col1` which happends to be `k` always starts and ends with `"`

**Comment by asadovsky** [comment]
Fixed. Fix was published in syncbase dart pkg version 0.0.13.
