### ISSUE TITLE
Race between (app/db).Exists and (app/db).Create

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#861]
I have run into this a few times where the code like

```
if( !app.Exists() ) {
 app.Create()
}
```

runs into race condition and `Create` fails with `already exists` if it gets created between `Exists` and `Create` calls.

I think an atomic `createIfNotExists` would be nice. For now, I am wrapping `create` in try catch and ignoring `exists` error.

@asadovsky

**Comment by yyoon** [comment]
+1

I had the same issues when launching the app on two devices at the same time.

**Comment by asadovsky** [comment]
Thanks, noted. A couple comments:
- Assuming you're always using the same ACL, you can just call Create() and ignore the error if it's "already exists". (Sounds like this is what you ended up doing.) Perhaps we'll add a client-side "idempotent create" helper function. 
- Various people have given feedback about the difficulty in setting up the whole hierarchy (app/db/tables), so we plan to add a client-side helper function for this. This helper will be idempotent, so you won't have to worry about handling "does not yet exist" vs. "already exists".

**Comment by aghassemi** [comment]
Idempotent client-side helpers would be great. For the server-side API, it may still make sense for `create` to never fail on `exists`. I don't see a lot of use-cases where one wants that behaviour. Even if there is a use-case for that, maybe instead of failing, `create` can return a additional `bool` indicating whether it existed or not.

**Comment by asadovsky** [comment]
Covered by #889
