### ISSUE TITLE
v.io/x/ref/runtime/internal/flow/conn::TestOrdering flaky

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#867]
https://veyron.corp.google.com/jenkins/job/vanadium-go-test/1071/ARCH=amd64,OS=linux/console

@suharshs

**Comment by caprita** [comment]
This seems like a different failure flavor, in the race test:

FAIL: TestOrdering (0.13s)
13:15:37    flowcontrol_test.go:151: Did not recieve a message from each flow in round 3: map[18:true 12:true 16:true]

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/994/OS=linux,P=3/console

**Comment by ghost** [comment]
This should be fixed by.

https://vanadium-review.googlesource.com/#/c/17580/
