### ISSUE TITLE
TestV23SyncbasedCompEval integration test fails

### ISSUE THREAD

**Issue by caprita** [vanadium/issues#871]
https://veyron.corp.google.com/jenkins/job/vanadium-integration-test/1066/OS=linux/consoleFull

The only known issue is timeout in the RPC stack (https://github.com/vanadium/issues/issues/870). If you think that the syncbase test failure may be due to hanging RPC, it's ok to defer further investigation on this issue (though perhaps a clearer failure message would help).

**Comment by asadovsky** [comment]
@hpucha @rdvg 
I think this is the same issue as #849 - Bindu/Raja, were you able to reproduce this at all?
Closing this issue since it's a dup.
