### ISSUE TITLE
Usability issues around syncgroup discovery

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#874]
This issue is the sibling of #873, and serves as a placeholder for usability issues related to syncgroup discovery. These issues have been summarized in the [Syncbase discovery scenarios doc](https://docs.google.com/document/d/19HV8L4UZ8dM9PgJX72hDbKqGDdM9mQJOwMVG4D9GtF4/edit#), and usability improvements have been proposed in the [Proposed new syncgroup API doc](https://docs.google.com/document/d/1ZTygJZg7SzQrcKoi9mtLxPduj3ZL5k8_1Kr_DMCh5Sc/edit#) (work in progress).

For now, we'll use this GitHub issue to track our progress. Once we've further fleshed out our plans, we will likely split up this issue into more specific issues for each action item.

**Comment by asadovsky** [comment]
Assigning to myself for tracking, as this is more "app developer centric" than Syncbase-implementation-centric. Based on recent discussions with @asimshankar, @jhahn21, and co, our immediate plan is to provide a "discovery-like" API for app developers that do something along the lines of "global discovery", and see how far that takes us. We will plan on incorporating that API into the Syncbase documentation and example apps, so the sooner it's available, the better.

@asimshankar, @jhahn21, can you give any time estimate / is there an issue for tracking? Someone from our end (e.g. me) can also pitch in to help with this.

**Comment by asadovsky** [comment]
Also cc-ing @aghassemi and @kenashcraft (for their SyncSlides experience) and @hpucha and @rdvg (since this bears some relation to syncgroup discovery).

**Comment by jhahn21** [comment]
I created an issue #1077 for it. I think I can start working on it in 2 weeks after finishing larger payload support.

**Comment by aghassemi** [comment]
Closing this one in favor of #1077
