### ISSUE TITLE
Peer selection: avoid slowdown caused by unresponsive peers

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#880]
There's a bunch we can do to improve peer selection, as described in [this document](https://docs.google.com/document/d/1PjVbj5Gy-7cRqZPwu-er7WYa81U16-Oj6nzic49oAB8/edit#).

This GitHub issue is for tracking a specific problem that several users have noticed: when a peer becomes unresponsive, sync slows down for all other peers. This happens because currently peers are selected at random, and once a peer is selected, sync issues a GetDeltas RPC to that peer with a 2s timeout; until the RPC times out, the Syncbase instance issuing this RPC will not receive updates from its other peers.

**Comment by hpucha** [comment]
https://vanadium-review.googlesource.com/#/c/18273/

fixes this issue by maintaining peer health proactively.

**Comment by asadovsky** [comment]
w00t!!

:tada: :balloon: :confetti_ball:

Closing this issue since, per @aghassemi's testing, this resolves the pressing issue.
