### ISSUE TITLE
Syncbase client libs: need API for collision-safe UIDs

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#886]
Syncbase recommends developers use UIDs as row keys, syncgroup names, etc. in various situations, but currently we don't provide a helper function to generate UIDs. We should provide such helpers in all of our client libraries.

@jxson referenced https://www.npmjs.com/package/cuid when raising this issue.

**Comment by kenashcraft** [comment]
Java has a UUID class, but it generates really long strings that aren't fun to read.

**Comment by asadovsky** [comment]
FYI, mrschmidt@google plans to work on this.
Marking as unassigned since he doesn't yet have a GitHub account.

**Comment by AsturaPhoenix** [comment]
TODOs has something similar:

https://vanadium-review.googlesource.com/#/c/21880/

It uses the local clock as a basis, allowing watch streams to modify the
basis for tail insertion and including perturbation based on a
compressed-encoded UUID. In theory it should allow arbitrary insertion as
well with little modification.

**Comment by afandria** [comment]
TODOs' implementation is nice because it generally guarantees that insertion order is preserved.

One minor caveat is that the watch streams need to participate in keeping the "most recent UUID" up-to-date.

**Comment by schmidt-sebastian** [comment]
This is now submitted with https://vanadium-review.googlesource.com/#/c/22549/
