### ISSUE TITLE
Proposal: Change  the v23.Init API

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#891]
# Changing v23.Init

Here is a proposal to change the API for `v23.Init` slightly. If you have any
objections or suggestions, please make them known (by commenting on this or
talking to me) and if there are no blocking objections I will start doing this
sometime in the next week or two.

(Brought to you by @mattr-google @suharshs @asimshankar)
(FYI: @jhahn21 and @bjornick)
## Background

Today, all Vanadium applications are effectively required to call `v23.Init` as
that creates the `*context.T` object which is a parameter to all the public API
functions.

All platform dependent functionality encapsulated in a
[_runtime factory_](https://godoc.org/v.io/v23#RuntimeFactory). Currently,
there can be only one runtime factory in the process' address space and
the `init` function of each package defining a runtime factory registers it
as the one global function. This leads to the following usage pattern in
`package main` of each application:

```
package main

import (
   "v.io/v23"
   _ "v.io/x/ref/runtime/factory/roaming" // Unnamed import
)

func main() {
  // Initialize the context, the call below uses the runtime
  // factory registered via the unnamed-import above
  ctx, shutdown := v23.Init()
  defer shutdown()
  doSomething(ctx)
}
```
### Problems?

There are a few rough edges with this API:
1. This mechanism provides no way to base runtime initialization on state not
   available in global variables.
   variables. For example, for Mojo, runtime initialization requires access
   to the mojo `application.Context`, and for Android access to
   [`android.content.Context`](https://vanadium-review.googlesource.com/#/c/17348/4/android-lib/src/main/java/io/v/android/v23/V.java).
   The current API provides no hints that this is the case and instead developers are
   expected to know that they have to call additional functions to
   provide platform specific context information to global state used by
   the runtime factory initialization.
2. The unnamed import is a requirement since a runtime factory must be
   registered. However, the API provides no hint that this is the case. The
   call to `v23.Init` may be far removed (say in some library package) from
   where the runtime is imported (which practically must be in the `main`
   package), in which case it isn't obvious to the developer how to fix the
   panic they will see at runtime (See #795).
3. The packages implementing a runtime factory register it in their `init`
   function, which makes code-reuse slightly problematic. For example,
   the [Android runtime factory](https://vanadium-review.googlesource.com/#/c/17350/)
   is _almost_ a duplicate of the [roaming](https://vanadium.googlesource.com/release.go.x.ref/+/master/runtime/factories/roaming/)
   one, but not quite. Avoiding this means splitting the runtime implementation
   into more packages with one top level silly package that just has an `init`
   function.
4. "One factory per address space" makes test organization cumbersome. Two
   tests in the same package cannot use different runtimes. For example, this
   happens in the RPC implementation where some tests are in the same package
   as the RPC implementation and others are forced into a separate package since
   they test using a different runtime.
### Proposal

To fix the above issues, the proposal is to do away with the unnamed imports
(and registration via the `init` function of the runtime factory implementation)
and thereby make the state required for initialization explicit in the API.

This will lead to `package main` looking more like:

```
package main

import (
  "v.io/v23"
  "v.io/x/ref/runtime/factory/roaming"
)

func main() {
  ctx, shutdown := v23.Init(roaming.New())
  defer shutdown()
  doSomething(ctx)
}
```

Providing the runtime explicitly to `v23.Init` allows things like the android
context to be explicitly provided where needed. For example, when using Vanadium
from within Mojo, this will become:

```
package mojo

import (
  "v.io/v23"
  "v.io/v23/context"
  "v.io/x/ref/runtime/mojo"
  "mojo/public/go/application"
)

type delegate struct {
  ctx      *context.T
  shutdown func()
}

func (d *delegate) Initialize(actx application.Context) {
  d.ctx, d.shutdown = v23.Init(mojo.New(actx))
  ...
}
```

**Comment by jhahn21** [comment]
How can we avoid duplication of runtime implementation? I'm not sure whether we need two mojo factories like mojo-static or mojo-roaming, but if so do we need to create two runtime factor?
Or maybe can we do like

```
import (
  "v.io/x/ref/runtime/roaming"
  "v.io/x/ref/runtime/mojo"
)
...

d.ctx, d.shutdown = v23.Init(mojo.New(actx, roaming.New()))

```

**Comment by asimshankar** [comment]
@jhahn21: That is one option, but in this particular case I would imagine that mojo.New returns something that basically defers to the roaming one. So, it would instantiate the roaming runtime and return something composed with it. Currently, one runtime cannot "import" another in its implementation because of the registration in the `init` function,

(On a related note, I'm hoping to do away with "static" and "generic" and instead just have 3 profiles: "commandline", "android" and "mojo")

**Comment by asadovsky** [comment]
Is there any update on this?

I ran into a situation where the "one factory per address space" restriction is really annoying: Some tests run the mount table in a subprocess using v23test.StartRootMountTable, which compiles mounttabled using v23test.BuildGoPkg. I'd like to change v23test.StartRootMountTable to avoid compilation by running the mount table using v23test.FuncCmd, which runs the original (test) executable with different configuration to have it split off into mount table code instead of test code.

The problem is that some of these tests use the "fake" runtime factory, whereas the mount table must be run with the "generic" or "roaming" factory.

**Comment by ghost** [comment]
@asadovsky This doesn't really address the general problem, but for your specific case, why run the mounttable as a separate process at all?  Isn't it easier to just call test.V23InitWithMounttable()?

**Comment by asadovsky** [comment]
@mattr-google Thanks for the suggestion. It turned out that most of my test failures were fixed by switching from "generic" profile to "roaming" (thus enabling glob handlers) - thanks for helping me debug that. Also, your suggestion of using test.V23InitWithMounttable() was handy for my one remaining broken test.

So, all good from my end now, though I still hope we implement the proposal described in this issue.

**Comment by asimshankar** [comment]
Obsolete
