### ISSUE TITLE
Syncbase Mojo Dart: Requires an account to use

### ISSUE THREAD

**Issue by afandria** [vanadium/issues#892]
`syncbase_server.mojo` automatically crashes if the Android phone does not have any accounts set up. (Interestingly, there's no pop-up; it just doesn't even give you the chance of adding a new one.)

It also fails if you decide to choose cancel when picking an account. I feel like canceling is still a valid choice, so the program should never crash even if no account was found.

```
panic:
failed to select an account for user: 0xd5e05d38
goroutine 17 [running, locked to thread]:
main.(*delegate).Initialize
(0xd5d79440, 0xc5539530, 0xd5cd1f90)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_main.go:43 +0xdc
mojo/public/go/application.(*ApplicationImpl).Initialize(
0xd5cd1f90, 0xc5539468, 0xd5cc5ab0, 0xd5d759b0, 0xd5d79560, 0x2b, 0x0, 0x0)
/usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/application/application_impl.go:101 +0x16c
mojo/public/interfaces/application/application.(*application_Stub).Accept(0xd5d75990,
0xd5cc1d00, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/out/Debug/gen/go/src/mojo/public/interfaces/application/application/application.mojom.go:673 +0x2fc
mojo/public/go/bindings.(*Stub).ServeRequest(0xd5d8b820
, 0x0, 0x0)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/bindings/stub.go:48 +0x98
mojo/public/go/application.Run
(0xc5539378, 0xd5d79440, 0x4)
    /usr/local/google/home/alexfandrianto/mojo/src/mojo/public/go/application/application_impl.go:83 +0x228
main.MojoMain(0x4, 0xf72bc8c4
)
    /usr/local/google/home/alexfandrianto/Documents/vanadium_root/release/go/src/v.io/x/ref/services/syncbase/syncbased/mojo_main.go:79 +0xa4

```

I am not a fan of this new flow (for development purposes) because it requires an account before we can run syncbase. However, if we accept that an account picker should show up, I don't think we should panic simply because no account was chosen (or the phone started with no account). Instead, I'd prefer the default principal to be used, or better yet, allow a custom principal to be used by the program.

@asimshankar @aghassemi

**Comment by asadovsky** [comment]
Sent https://vanadium-review.googlesource.com/#/c/17695/.

Ideally, it would be easy to configure Mojo shell to start with some sort of synthetic account for testing purposes - is there no way to do this?

**Comment by afandria** [comment]
I don't think we can do that since the account flow seems specific to Android.

Croupier has been sending in a blessing manually in earlier versions of Syncbase, by using the `v23.credentials` flag. What's happening to that now? Can we continue to use that instead?

**Comment by afandria** [comment]
It looks like the reactionary dust has settled and that we've mostly acclimated to this change. The bugs are being worked out and should mostly be gone once https://github.com/vanadium/issues/issues/943 is fixed.
