### ISSUE TITLE
Discovery: security exception claims ACCESS_COARSE_LOCATION not present (it is)

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#899]
The momentshare app has these elements in its AndroidManifest.xml
      uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"
     uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"

Scanning works, in the sense that I see advertisements, but when starting a discovery scan i consistently see this:

11-16 11:18:58.458 11031-11417/io.v.momentshare D/MainActivity: Starting scan.
11-16 11:18:58.651 11031-11417/io.v.momentshare D/BluetoothGattServer: registerCallback()
11-16 11:18:58.651 11031-11417/io.v.momentshare D/BluetoothGattServer: registerCallback() - UUID=e5411456-a9be-42e2-9bbe-28f615cf57ca
11-16 11:18:58.653 11031-11042/io.v.momentshare D/BluetoothGattServer: onServerRegistered() - status=0 serverIf=5
11-16 11:18:58.659 11031-11417/io.v.momentshare D/BluetoothAdapter: STATE_ON
11-16 11:18:58.663 11031-11045/io.v.momentshare D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder: Caught a RuntimeException from the binder stub implementation.
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder: java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.os.Parcel.readException(Parcel.java:1599)
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.os.Parcel.readException(Parcel.java:1552)
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:772)
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:324)
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
11-16 11:18:58.672 11031-11045/io.v.momentshare W/Binder:     at android.os.Binder.execTransact(Binder.java:453)
11-16 11:19:00.664 11031-11417/io.v.momentshare D/MainActivity: Scan started.

**Comment by bjornick** [comment]
This is a problem in M. You need to specifically ask for these permissions from the user.  Listing them in the manifest is not sufficient.  See: http://developer.android.com/training/permissions/requesting.html

**Comment by monopole** [comment]
obsolete
