### ISSUE TITLE
Implement routine for binding to debug names

### ISSUE THREAD

**Issue by mattr-google** [vanadium/issues#9]
The problem is, given a name a/b/c/d and a debug suffix 'vtrace', I want to produce the correct name of the form:

a/b/__debug/vtrace

Originally I wanted to write a function:

func ResolveDebug(name, debugSuffix string) (resolvedName string, err error)

However this does not work. The resolveName return argument would have to be an array because names can resolve to a number of endpoints. But if we return an array, there isn't a reasonable way to use it in StartCall (or some stub wrapped version). Users would have to repeat all the logic to filter the names according to capabilities, try them all in parallel, etc.

We could do this by having yet another special syntax for names:

StartCall('a/b/c/d/__debug/vtrace', 'method', ...)

This would internally realize that the /__debug/ means we want to specially reparent the vtrace onto the root of the server hosting the object a/b/c/d and return the right things from resolve.

I find this kind of complicated and surprising, so I don't really like it, but I can't think of a great alternative.

What do other people think? @tatatodd  @presotto

**Comment by ghost** [comment]
This hasn't been necessary.
