### ISSUE TITLE
Update diagrams on site to reflect blessings syntax change

### ISSUE THREAD

**Issue by monopole** [vanadium/issues#901]
We've gone from slash to colon, so need to adjust diagrams, e.g.

https://v.io/images/tut/security04-alice-carol-succeed-bob-fails.svg

**Comment by asimshankar** [comment]
@lnizix : I believe you authored these diagrams? Would you mind updating them or telling me how to? :)
Thanks.

CCing myself (@asimshankar)

**Comment by asadovsky** [comment]
Do we know if @lnizix is seeing this? (Perhaps her GitHub notifications aren't set up right?) I'll send her a quick email.

**Comment by asimshankar** [comment]
https://vanadium-review.googlesource.com/18986
should resolve this.

Will close this out once that change is submitted and the site has caught up with the change

**Comment by asimshankar** [comment]
I believe all images have been updated, if there were some that were missed I hope a new bug will be created.
