### ISSUE TITLE
syncbased: default --root-dir usually inaccessible

### ISSUE THREAD

**Issue by ivanpi-mtv** [vanadium/issues#904]
`syncbased` flag `--root-dir` defaults to `/var/lib/syncbase`, which is usually inaccessible to the user (owned by root), causing `syncbased` to fail.
A better default might be a subdirectory of the user's home directory, current directory, or `/tmp` (depending on if the default behaviour should be a persistent database or a temporary testing one).

**Comment by asadovsky** [comment]
I'll take care of this one. I'll probably just use `filepath.Join(os.TempDir(), "syncbase")`.

**Comment by asadovsky** [comment]
Fixed in https://vanadium-review.googlesource.com/#/c/20858/

If -root-dir is not specified, we use a fresh temporary directory. Seems "good enough" for now, closing the issue.
