### ISSUE TITLE
Syncbase: cloud syncbase instance doesn't always sync with local instance

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#907]
@asadovsky @hpucha 

I'm having some sync issues with Reader Android app. The basic syncbase setup is the same as in #848. There is a cloudsync instance running with syncbased, and the Android Reader app is running its own local syncbase instance. The syncgroup is hosted on cloudsync, and the local syncbase joins the group. Both instances are mounted on the global mount table using proxy.

I expect that the cloudsync instance to replicate all the local data, but that's not always happening.

When the sync is not happening, every two seconds, the Android client is generating the following set of logs.
(NOTE: The peer `{96614e42328460f1}` is the cloudsync instance.)

```
11-17 12:13:28.267 28354-28744/io.v.android.apps.reader E/STDERR: E1117 18:13:28.266790   28354 funcs.go:94] sync: syncClock: received network error: gojni:<rpc.Client>"/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync".GetTime: Canceled: [/@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync:/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync.GetTime: gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: : gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: error reading from unknown: EOF]
11-17 12:13:28.267 28354-28528/io.v.android.apps.reader E/vlog: E1117 18:13:28.266790   28354 funcs.go:94] sync: syncClock: received network error: gojni:<rpc.Client>"/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync".GetTime: Canceled: [/@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync:/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync.GetTime: gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: : gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: error reading from unknown: EOF]
11-17 12:13:28.267 28354-28528/io.v.android.apps.reader W/vlog: E1117 18:13:28.266790   28354 funcs.go:94] sync: syncClock: received network error: gojni:<rpc.Client>"/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync".GetTime: Canceled: [/@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync:/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync.GetTime: gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: : gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: error reading from unknown: EOF]
11-17 12:13:28.267 28354-28528/io.v.android.apps.reader I/vlog: E1117 18:13:28.266790   28354 funcs.go:94] sync: syncClock: received network error: gojni:<rpc.Client>"/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync".GetTime: Canceled: [/@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync:/ns.dev.v.io:8101/users/youngseokyoon@google.com/reader/rendezvous/96614e42328460f1/%%sync.GetTime: gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: : gojni:<client>tryCreateFlow /@6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@/%%sync: error reading from unknown: EOF]
11-17 12:13:28.267 28354-28744/io.v.android.apps.reader E/STDERR: E1117 18:13:28.267694   28354 funcs.go:94] sync: syncClock: couldn't connect to peer {96614e42328460f1 }
11-17 12:13:28.276 28354-28528/io.v.android.apps.reader E/vlog: E1117 18:13:28.267694   28354 funcs.go:94] sync: syncClock: couldn't connect to peer {96614e42328460f1 }
11-17 12:13:28.276 28354-28528/io.v.android.apps.reader W/vlog: E1117 18:13:28.267694   28354 funcs.go:94] sync: syncClock: couldn't connect to peer {96614e42328460f1 }
11-17 12:13:28.276 28354-28528/io.v.android.apps.reader I/vlog: E1117 18:13:28.267694   28354 funcs.go:94] sync: syncClock: couldn't connect to peer {96614e42328460f1 }
11-17 12:13:28.652 28354-28528/io.v.android.apps.reader E/vlog: E1117 18:13:28.652903   28354 conn.go:484] Error sending tearDown on connection to @6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@: EOF
11-17 12:13:28.653 28354-28528/io.v.android.apps.reader W/vlog: E1117 18:13:28.652903   28354 conn.go:484] Error sending tearDown on connection to @6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@: EOF
11-17 12:13:28.653 28354-28464/io.v.android.apps.reader E/STDERR: E1117 18:13:28.652903   28354 conn.go:484] Error sending tearDown on connection to @6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@: EOF
11-17 12:13:28.653 28354-28528/io.v.android.apps.reader I/vlog: E1117 18:13:28.652903   28354 conn.go:484] Error sending tearDown on connection to @6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@: EOF
```

On the cloudsync console, I'm seeing these errors:

```
E1117 10:12:42.597992   62959 conn.go:484] Error sending tearDown on connection to @6@wsh@104.197.5.136:8110@@9427e52e41ee2a03c244f7946407aa0a@s@dev.v.io/u/youngseokyoon@google.com@@: EOF
E1117 10:12:50.540806   62959 conn.go:484] Error sending tearDown on connection to @6@tcp@100.110.114.19:46987@@00000000000000000000000000000000@s@@@: EOF
E1117 10:12:58.927067   62959 conn.go:484] Error sending tearDown on connection to @6@ws@104.197.5.136:8110@@00000000000000000000000000000000@s@@@: EOF
E1117 10:13:03.818736   62959 conn.go:484] Error sending tearDown on connection to @6@ws@172.17.166.57:8000@@00000000000000000000000000000000@s@@@: websocket: close sent
```

This might be related to the latency issue I reported in #848.

**Comment by asadovsky** [comment]
Your description suggests that the Android client is attempting to reach the cloudsync instance (96614e42328460f1) but is unable to do so. Some questions:
- When you say "both instances are mounted on the global mount table using proxy", what do you mean by that? Are you referring to the --name flag passed to Syncbase, or to the "Syncbase id" mount entries that sync creates?
- What are your mounttable ACLs set to? If you configure those ACLs to be completely open, does that help?
- If you attempt to send RPCs to those Syncbase id mount entries, e.g. using the vrpc tool, does that work? `$JIRI_ROOT/release/go/bin/vrpc -v23.credentials=creds signature [name]`

**Comment by asadovsky** [comment]
Also, we should confirm with @hpucha that when Syncbase is serving with v23 proxy, that the mount entries created by sync also use the proxy.

**Comment by asadovsky** [comment]
Also @rdvg

**Comment by ghost** [comment]
Can you try again but run both sides with the V23_RPC_TRANSITION_STATE=none?

So you would do:
V23_RPC_TRANSITION_STATE=none myprogram --args...

Your errors suggest that a tcp connection is established, but no data is ever received over it.  This is likely related to the rpc transition.

**Comment by yyoon** [comment]
@asadovsky Here are my answers to your questions:
1. Let me be more specific about the proxy settings. I'm talking about the ones, not the ones under the rendezvous table.
   - For Cloudsync, I'm passing `--v23.proxy="/ns.dev.v.io:8101/proxy"` as an argument.  
     The name looks like `--name="users/youngseokyoon@google.com/reader/cloudsync"`.
   -  For Android, I'm using the following code to enable proxy.
     
     ``` java
       mVContext = V.init(mContext);
       try {
           mVContext = V.withListenSpec(
                   mVContext, V.getListenSpec(mVContext).withProxy("proxy"));
       } catch (VException e) {
           handleError("Couldn't setup vanadium proxy: " + e.getMessage());
       }
     ```
   - The Android syncbase instance is mounted with the name `"users/youngseokyoon@google.com/android/reader/<device_id>/syncbase"`.
2. I'm already using completely open ACLs for everything.
3. Well, I can see the app/db/table hierarchy from the namespace browser like this:
   ![image](https://cloud.githubusercontent.com/assets/1309817/11224619/c5195898-8d2a-11e5-97e2-ae5a29e286e7.png)
   
   It seems like I don't have the vrpc tool installed, though. How do I build it?

**Comment by yyoon** [comment]
@mattr-google I could try that for the cloudsync instance which uses syncbased, but how can I do the same for the Android client? Any ideas?

**Comment by ghost** [comment]
If you can change the code then in your main before you initialize the runtime do os.Setenv?

**Comment by yyoon** [comment]
The above error messages are no longer shown once I set V23_RPC_TRANSITION_STATE=none for cloudsync. However, the not-synchronizing problem is still there, unfortunately.

The synchronization works for a while (about a minute from the start?) and then stops working at some point. I'm also experiencing the problems mentioned in #856 too.

@asadovsky how can I get more detailed sync logs from syncbased? I'm using `--v=5` and `--vmodule="vsync*=5"`. Are these the correct parameters to use?

**Comment by hpucha** [comment]
Just -vpath=vsync*=5 is sufficient for sync logs.

Alternately, v=5 will dump logs from all of Vanadium.

**Comment by asadovsky** [comment]
What makes you think that sync stops working? I ask because @afandria and Emily Shack (whose GitHub username I don't have) reported a possibly-related problem today: they found that their watch stream stops reporting updates after a while, even though updates are still happening.

**Comment by yyoon** [comment]
Oh, that's interesting. I was only using watch streams to check for updates, and the data may be actually updating internally. I'll go ahead and check if it is the case.

**Comment by ghost** [comment]
Hello,

Suharsh and I have identified a bug that can cause failures when you stream a lot of data through a proxy.  The logs you printed are actually not consistent with that bug, so I'm not sure you are encountering it.  The fix is currently in presubmits, but I hope to check it in very soon.  I'll update when that is done, then perhaps you can try again.

**Comment by yyoon** [comment]
Thanks for letting me know. Today I'm seeing lots of "Ignoring data message for unknown flow on connection to ..." messages, but I see those messages even when the sync is working.

I'll try again when the it's fixed, anyways.

**Comment by asadovsky** [comment]
Kishore hit what we believe to be the same issue. It appears that Suharsh's proxy fix addressed the issue. Marking as closed; feel free to reopen or file a new issue if you continue to have problems.

**Comment by yyoon** [comment]
I started testing with the latest vanadium-android lib, and it seems to work fine now. I'll continue testing and recreate an issue if I see this problem again.
