### ISSUE TITLE
Syncbase: Watch stream stops seeing updates after a while

### ISSUE THREAD

**Issue by emshack** [vanadium/issues#913]
@asadovsky @afandria @mattr-google 

Alex and I are having some issues with the watch stream in the Croupier Go app. When the app is started up, three separate goroutines are called:

```
go watch.Update(u)
go watch.PrintStream("Stream 1", u)
go watch.PrintStream("Stream 2", u)
```

These correspond to the following code:

```
func PrintStream(prefix string, u *uistate.UIState) {
    stream, err := client.WatchData(u)
    if err != nil {
        fmt.Println("WatchData error:", err)
    }
    for {
        if updateExists := stream.Advance(); updateExists {
            c := stream.Change()
            if c.ChangeType == nosql.PutChange {
                var value []byte
                if err := c.Value(&value); err != nil {
                    fmt.Println("Value error:", err)
                }
                valueStr := string(value)
                fmt.Println(prefix, valueStr)
            }
        }
    }
}

func Update(u *uistate.UIState) {
    stream, err := client.WatchData(u)
    if err != nil {
        fmt.Println("WatchData error:", err)
    }
    for {
        if updateExists := stream.Advance(); updateExists {
            c := stream.Change()
            if c.ChangeType == nosql.PutChange {
                var value []byte
                if err := c.Value(&value); err != nil {
                    fmt.Println("Value error:", err)
                }
                valueStr := string(value)
                fmt.Println(valueStr)
                updateType := strings.Split(valueStr, "|")[0]
                switch updateType {
                case gamelog.Deal:
                    onDeal(valueStr, u)
                case gamelog.Pass:
                    onPass(valueStr, u)
                case gamelog.Take:
                    onTake(valueStr, u)
                case gamelog.Play:
                    onPlay(valueStr, u)
            case gamelog.Ready:
                    onReady(valueStr, u)
                }
            } else {
                fmt.Println("Unexpected ChangeType: ", c.ChangeType)
            }
        }
        fmt.Println(stream.Err())
    }
}
```

And in the client package:

```
func WatchData(u *uistate.UIState) (nosql.WatchStream, error) {
    db := u.Service.App(util.AppName).NoSQLDatabase(util.DbName, nil)
    prefix := ""
    resumeMarker, err := db.GetResumeMarker(u.Ctx)
    if err != nil {
        fmt.Println("RESUMEMARKER ERR: ", err)
    }
    return db.Watch(u.Ctx, util.LogName, prefix, resumeMarker)
}
```

If I run the app with one device, that is, it creates a syncgroup but no other devices join, there are no issues getting the local watch updates. However, when a device is added, one of the devices eventually stops getting updates. It can send updates to syncbase, and all other devices in the syncgroup receive them, but the affected device can no longer see any updates, even local ones. The two streams called by PrintStream continue to see updates, but the one called by Update does not. Also, the stream.Err() line at the end of Update() stops printing anything, whereas when the device is still getting updates, it prints <nil> with every update. This is a sample of the output I'm seeing when the error occurs:

```
11-18 13:59:37.751 11326 11369 I GoLog   : Stream 1 Take|2:END
11-18 13:59:37.751 11326 11369 I GoLog   : Take|2:END
11-18 13:59:37.752 11326 11369 I GoLog   : <nil>
11-18 13:59:37.812 11326 11369 I GoLog   : Stream 2 Take|2:END
11-18 13:59:42.946 11326 11345 I GoLog   : Stream 2 Take|1:END
11-18 13:59:42.946 11326 11345 I GoLog   : Stream 1 Take|1:END
11-18 13:59:42.949 11326 11345 I GoLog   : Take|1:END
11-18 13:59:42.952 11326 11345 I GoLog   : <nil>
11-18 13:59:51.549 11326 11345 I GoLog   : Stream 1 Play|1:classic c2:END
11-18 13:59:51.550 11326 11350 I GoLog   : Stream 2 Play|1:classic c2:END
11-18 13:59:51.554 11326 11350 I GoLog   : Play|1:classic c2:END
11-18 13:59:55.237 11326 11350 I GoLog   : Stream 2 Play|2:classic cj:END
11-18 13:59:55.237 11326 11350 I GoLog   : Stream 1 Play|2:classic cj:END
11-18 14:00:31.676 11326 11368 I GoLog   : Stream 2 Play|2:classic c5:END
11-18 14:00:31.731 11326 11368 I GoLog   : Stream 1 Play|2:classic c5:END
```

Here, the Update() watch stream stopped updating for the last two syncbase updates, Play|2:classic cj:END and Play|2:classic c5:END

**Comment by emshack** [comment]
Sorry, didn't mean to submit yet, still in progress

**Comment by emshack** [comment]
Update: I have fixed this by putting all calls made by Update (onDeal, onPass, etc.) in separate go routines. It appears the animations were stacking, and preventing the watch stream from reporting more updates.

**Comment by asadovsky** [comment]
Can you say more about what you mean by "animations were stacking, and preventing the watch stream from reporting more updates"? What specifically would stop the watch stream from reporting updates? Was the whole machine grinding to a halt or something?

**Comment by emshack** [comment]
For example, the onTake() method:

```
func onTake(value string, u *uistate.UIState) {
    // logic
    playerInt, _ := parsePlayerAndCards(value, u)
    p := u.CurTable.GetPlayers()[playerInt]
    passed := p.GetPassedTo()
    for _, c := range passed {
        p.AddToHand(c)
    }
    u.CurTable.GetPlayers()[playerInt].SetDoneTaking(true)
    if u.CurPlayerIndex >= 0 {
        u.Cards = u.CurTable.GetPlayers()[u.CurPlayerIndex].GetHand()
    }
    if p.HasTwoOfClubs() {
        u.CurTable.SetFirstPlayer(p.GetPlayerIndex())
        // UI
        if u.CurView == uistate.Play && u.CurPlayerIndex != playerInt {
            view.LoadPlayView(u)
        }
    }
    // UI
    if u.CurView == uistate.Table {
        reposition.AnimateTableCardTake(passed, u.CurTable.GetPlayers()[playerInt], u)
        reposition.SetTableDropColors(u)
    }
}
```

This calls AnimateTableCardTake()

```
func AnimateTableCardTake(cards []*card.Card, p *player.Player, u *uistate.UIState) {
    for cardNum, animCard := range cards {
        destinationPos := p.GetPassedFrom()[cardNum].GetInitial()
        if cardNum < len(cards)-1 {
            animateCardNoChannel(animCard, destinationPos, animCard.GetDimensions(), u)
        } else {
            c := make(chan bool)
            animateCardMovement(c, animCard, destinationPos, animCard.GetDimensions(), u)
            <-c
        }
    }
}

func animateCardMovement(c chan bool, animCard *card.Card, endPos, endDim *coords.Vec, u *uistate.UIState) {
    node := animCard.GetNode()
    startPos := animCard.GetCurrent()
    startDim := animCard.GetDimensions()
    iteration := 0
    node.Arranger = arrangerFunc(func(eng sprite.Engine, node *sprite.Node, t clock.Time) {
        iteration++
        if iteration < animationFrameCount {
            curXY := animCard.GetCurrent()
            curDim := animCard.GetDimensions()
            XYStep := endPos.MinusVec(startPos).DividedBy(animationFrameCount)
            dimStep := endDim.MinusVec(startDim).DividedBy(animationFrameCount)
            newVec := curXY.PlusVec(XYStep)
            dimVec := curDim.PlusVec(dimStep)
            animCard.Move(newVec, dimVec, eng)
        } else if iteration == animationFrameCount {
            animCard.Move(endPos, endDim, eng)
            c <- true
        }
    })
}
```

Because the onTake() call was not in a separate go routine, Update() had to wait until the animation was over to continue. If more than one update happened during this time, it stopped getting notified about future updates, even if the blocking animation ended. The whole app did not freeze, all local functionality still worked, but the watch stream created by Update() stopped seeing any updates.

**Comment by asadovsky** [comment]
Interesting. I can't say I understand why Update() would stop seeing updates in this case. If the client is slow to process items on the stream, eventually they'll pile up in the client's buffer and I believe our streaming implementation might block the server's goroutine from sending more updates. But once the client "catches up", I would expect the stream to unblock and pass through more items.

@mattr-google @tatatodd @suharshs will know exactly what the RPC system does in the case of "slow client", and whether the behavior you describe is expected.

**Comment by asadovsky** [comment]
Re-opening for now, until we hear from an RPC person.

**Comment by tatatodd** [comment]
A slow client should only cause the server to pause sending data, but after the client reads more buffered data, the server should resume sending data.  This should be true regardless of how slow the client is at reading the data.  Eventually we may choose to kill the flows; I'm not sure if we do that right now.

Are you sure the calls made by Update (e.g. onTake, etc) aren't just blocking forever?  That would explain why your Update goroutine would stop seeing updates, and would also explain why spawning those operations onto different goroutines seems to fix the problem.  Note that if this is the case, some of those goroutines are going to stick around forever.

**Comment by emshack** [comment]
After a lot of debugging and making sure none of my go routines were hanging forever, I am no longer having a problem with seeing watch updates. I think it was indeed a problem with some hidden go routines blocking forever. I'm going to go ahead and close this issue.
