### ISSUE TITLE
RPC2 Rollout cleanup

### ISSUE THREAD

**Issue by asimshankar** [vanadium/issues#916]
The new RPC system was rolled out today. Just jotting down some cleanups left:
- [x] Switch the device manager to use bidirectional RPC instead of running a proxy (@suharshs?)
- [x] Ensure the new proxy is being monitored (@suharshs?)
- [ ] Figure out why the RPC load test shows a +30% increase in latency (@mattr-google) (Relevant links: [Dashboard](https://app.google.stackdriver.com/monitoring/1009385/rpc-load-test), [RPC loadtest job showing the flip](https://veyron.corp.google.com/jenkins/job/vanadium-go-rpc-load/6524/))

**Comment by ghost** [comment]
The first two items are done, I filed https://github.com/vanadium/issues/issues/1003 for the third.
