### ISSUE TITLE
Syncbase Watch: getting initial state + watching too much boilerplate

### ISSUE THREAD

**Issue by ivanpi-mtv** [vanadium/issues#917]
Common use cases of Watch are:
- scanning the initial state and watching for updates; currently, this requires starting a read-only batch, scanning, getting the resume marker, aborting the batch, then watching;
- watching only for updates going forward, not caring for existing state; this requires first fetching the resume marker, then watching.

This currently results in a large amount of boilerplate code and unnecessary RPC roundtrips (especially for `GetResumeMarker()`).

The issues can mostly be resolved by fully implementing the `v23/services/watch` specification:
- the first case can frequently be simplified by implementing Watch from "beginning of time" (empty resume marker, see `v23/services/watch.ResumeMarker`), passing the current state as the first batch of updates in the watch stream;
- <strike>the second case is simplified by implementing Watch from `"now"` (see `v23/services/watch.ResumeMarker`).</strike> already implemented

For the more complex cases (initial scan processing being different from watch processing), a read-only RunInBatch-like helper could be provided. To reduce the number of RPC roundtrips, BeginBatch could return the resume marker. Also see #906 

@kenashcraft (syncslides), @afandria (croupier), @ivanpi-mtv (sensorlog)

**Comment by ivanpi-mtv** [comment]
The second case (watching from "now") appears to be already implemented, but poorly documented.

**Comment by afandria** [comment]
To elaborate, I have switched from `await db.getResumeMarker()` to `UTF8.encode("now")`, and my app seems to continue functioning as before.

**Comment by aghassemi** [comment]
+1 for this. Being able to get initial values and watch with a special resume marker (I believe empty resume marker is the indicator based on the V23 Watch API) would be very useful for flutter version of SyncSlides since the UI code makes no distinction between change events coming in later and the initial values, so even initial values can come in as Put change types and the same code would work ( This is essentially what I am doing currently, changing rows coming in from the initial queries to change events so same code gets reused )

**Comment by ivanpi-mtv** [comment]
#693 is a duplicate.

**Comment by ivanpi-mtv** [comment]
v.io/c/{19947,19948,19949,19951,19952} implement watch from empty resume marker (with initial state). Remaining work is returning the resume marker from BeginBatch and possibly adding RunInReadOnlyBatch.

**Comment by ivanpi-mtv** [comment]
RunInBatch now works with readonly batches, making the more complex case less cumbersome.
v.io/c/20270 , v.io/c/20381 , v.io/c/20386 , v.io/c/20498

Returning the resume marker from BeginBatch would likely have a marginal benefit, if any.
