### ISSUE TITLE
Allow easier way to get WatchChanges from batches as a single event.

### ISSUE THREAD

**Issue by aghassemi** [vanadium/issues#930]
We should writer a stream transformer for the Dart library that anyone can use to get "batched" changes during watch. Currently they need to check `watchChange.continued` and do their own sequencing like in https://vanadium-review.googlesource.com/#/c/17901/1/lib/src/syncbase/log_writer.dart 

Would be great if users can just do:

`await for (BachedWatchChange c in watchStream.transform(BatchTransformer))`

`BachedWatchChange` could just have a `List<WatchChange>` as property.

@afandria @nlacasse

**Comment by afandria** [comment]
That would be great since Syncbase should have internal timestamps. This overlaps with the Syncbase improvements proposed in #918

**Comment by asadovsky** [comment]
Dup of #928, closing.
