### ISSUE TITLE
Flaky vsync tests

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#931]
I've seen a couple of syncbase tests flaking:

https://veyron.corp.google.com/jenkins/job/vanadium-go-test/1189/ARCH=amd64,OS=linux/testReport/junit/v/io_x_ref_services_syncbase_vsync/TestClockGetTime__GoTest___linux_amd64_/
https://veyron.corp.google.com/jenkins/job/vanadium-go-test/1188/ARCH=amd64,OS=linux/testReport/junit/v/io_x_ref_services_syncbase_vsync/TestNeighborhoodAwarePeerSelector__GoTest___linux_amd64_/

Have you seen this before?  Can you take a look? Let me know if it seems RPC related.

**Comment by asadovsky** [comment]
@jatinlodhia 
I just submitted CL https://vanadium-review.googlesource.com/#/c/17806 which might affect the TestClockGetTime flakiness. In general, that test is somewhat sensitive to RPC timings, and in particular is more likely to fail if client->server request transit time (for a local RPC) is significantly different from server->client response transit time. We can easily "deflake" it by loosening its threshold from 1ms to something like 10ms:
https://cs.corp.google.com/#vanadium/release/go/src/v.io/x/ref/services/syncbase/vsync/clock_test.go&l=40

**Comment by hpucha** [comment]
The fix for neighborhood one is checked in.

**Comment by asadovsky** [comment]
I'll include a tweak to the TestClockGetTime threshold in CL 18211, and will close this issue once that CL is checked in.

**Comment by asadovsky** [comment]
Merged my CL, closing the issue.
