### ISSUE TITLE
Chat web ui test failing

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#936]
https://veyron.corp.google.com/jenkins/job/vanadium-chat-web-ui-test/679/testReport/junit/(root)/vanadium-chat-web-ui-test/Make_test_ui/

**Comment by suharshs** [comment]
Seems flaky. Its fixed now. Will reopen if it happens again.

**Comment by suharshs** [comment]
Another flake :(
https://veyron.corp.google.com/jenkins/job/vanadium-chat-web-ui-test/683/testReport/junit/(root)/vanadium-chat-web-ui-test/Make_test_ui/

**Comment by afandria** [comment]
I don't think this is a flake. I think it's real. We probably parse the blessing string when showing who's speaking in the Chat app. The switch to `:` instead of `/` is messing us up.

I just got

```
dev.v.io:u:alexfandrianto@google.com:chrome:https%3A%2F%2Fchat.staging.v.io
```

**Comment by afandria** [comment]
The UI test now expects something slightly different for the member name.

We used to get `alexfandrianto@google.com`, but now we see `dev.v.io/u/alexfandrianto@google.com`

In theory, the next extension push will fix this.

**Comment by nlacasse** [comment]
This is fixed.  Asim needed to do a "make clean" before publishing the extension.
