### ISSUE TITLE
Inconsistent return types of Syncbase list methods

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#937]
@spetrovic77 @sjamesr

This is a minor issue, but there is inconsistency among the list methods in Java Syncbase lib.

In `SyncbaseApp` class:

```
List<String> listDatabases(VContext ctx);
```

In `Database` class:

```
List<String> listSyncgroupNames(VContext ctx);
```

In `DatabaseCore` class:

```
String[] listTables(VContext ctx);
```

I guess the last `listTables` method should return a `List<String>` instead.

**Comment by sjamesr** [comment]
Addressed in https://vanadium-review.googlesource.com/#/c/17990/

It will go into Vanadium 0.2
