### ISSUE TITLE
Go bench failing

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#938]
@mattr-google 

I am seeing two different types of flaky failures when I run the go-bench. (Note that for some reason these real failures don't mark go-bench as failed, but still show up in the console log for the test)

(1) Failed to encode request due to EOF.
https://veyron.corp.google.com/jenkins/job/vanadium-go-bench/1095/console

(2) Hanging and timeout:
stacktrace here: https://veyron.corp.google.com/jenkins/job/vanadium-go-bench/1094/console

For (2), looking into the stacktrace, it seems that a writer is stuck waiting for their turn. This could happen of notifyNextWriter doesn't get called, but it seems that it is called properly everywhere.

**Comment by suharshs** [comment]
Digging deeper: It appears that the conn is closing due to " Closing connection: benchmark.test:<client>tryCreateFlow /@6@tcp@127.0.0.1:34824@@653dbb2c7111e11a252926ff372c7826@l@test-blessing@@: connection closed remotely: benchmark.test: A remote process has sent more data than allowed.."

Looking into it now.

**Comment by suharshs** [comment]
https://vanadium-review.googlesource.com/#/c/18025/1

Resolves this.

**Comment by ghost** [comment]
I'm going to look at fixing this in a nicer way.

**Comment by ghost** [comment]
This is fixed by https://vanadium-review.googlesource.com/#/c/18374/
