### ISSUE TITLE
Android Vanadium account manager: Couldn't create blessing

### ISSUE THREAD

**Issue by yyoon** [vanadium/issues#941]
I'm trying to get a blessing using the Vanadium account manager app, but it failed with the following toast.

![image](https://cloud.githubusercontent.com/assets/1309817/11377266/dadf84da-9299-11e5-9308-508e4c649642.png)

Could this be related to the new RPC? @mattr-google @suharshs

**Comment by suharshs** [comment]
I don't think the account manager APK has been updated since we have begun the RPC transition. @sjamesr, could we update the APK?

Additionally, can we somehow automate this? Perhaps build a new APK daily with the staging or prod push?

**Comment by yyoon** [comment]
Resolved by the new account manager apk.
