### ISSUE TITLE
vanadium-mojo-syncbase-test fails with "/home/veyron/workspace/pt/root/.jiri_v23_profiles: no such file or directory"

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#947]
I just got this failure on a presubmit run on an unrelated syncbase CL.
https://dashboard.staging.v.io/?arch=amd64&class=vanadium-mojo-syncbase-test&job=vanadium-mojo-syncbase-test&n=16263&os=linux&part=0&suite=vanadium-mojo-syncbase-test&test=Init&type=presubmit
https://vanadium-review.googlesource.com/#/c/18056/

Perhaps some Jenkins nodes are configured properly, or perhaps there's a race condition somewhere with how the tests are run?

**Comment by nlacasse** [comment]
That's strange.

The WARNING below is not actually an error.  It just means that there is no .jiri-v23-profiles file yet, which will happen if no profiles have been installed.

```
WARNING: /home/veyron/workspace/pt/root/.jiri_v23_profiles doesn't exist
```

Something failed when installing the base profile, causing it to exit with 255, but I don't see what the actual error is.

**Comment by nlacasse** [comment]
Also, the FAIL about `/home/veyron/workspace/pt/root/.jiri_v23_profiles: no such file or directory` is printed by the jiri tool when it Stat's that file to see if it exists.  It should not cause the jiri tool to exit unexpectedly.

cc @cosnicolaou

**Comment by cosnicolaou** [comment]
I've not been able to repro this - can you do so? I think the warning message is a red herring - i.e. the failure is much later than that. I can see that the profiles.InstallDependencies function is being called and it appears to succeed and the failure occurs after that. I'll add some more logging to see if we can track this down should it occur again. Watch for a CL from me sometime today.

**Comment by cosnicolaou** [comment]
ok, v.io/c/18075 & v.io/c/18076

**Comment by asadovsky** [comment]
I haven't seen this recently; closing the issue.
