### ISSUE TITLE
TestV23IdentityServer is very flaky

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#948]
This test has been failing a lot in my presubmits lately, e.g.:
https://vanadium-review.googlesource.com/#/c/18065/1

I searched for the test name in our GitHub issue tracker but didn't find any open issues, so I'm filing one and assigning to @suharshs.

+cc @asimshankar @ankurtaly

**Comment by suharshs** [comment]
duplicate of https://github.com/vanadium/issues/issues/830

 Will try to take a look this week.
