### ISSUE TITLE
Jenkins monitoring fails to seek blessings

### ISSUE THREAD

**Issue by AsturaPhoenix** [vanadium/issues#963]
```
05:20:08 GETTING LATEST BINARIES...
05:20:13 CHECKING PRODUCTION SERVICES...
05:20:13 ERROR: vrun:<rpc.Client>"identity/role/vprod/monitor".SeekBlessings:invalid blessing extension in certificate(for failed to decode result #0: vrun:invalid blessing extension in certificate(for vprod/monitor:dev.v.io:u:o:115326827446942418468:account-2@vanadium-internal.iam.gserviceaccount.com): vrun:invalid blessing extension(vprod/monitor:dev.v.io:u:o:115326827446942418468:account-2@vanadium-internal.iam.gserviceaccount.com has / as a substring))
```

**Comment by AsturaPhoenix** [comment]
- @asimshankar

**Comment by AsturaPhoenix** [comment]
Correlating binary update against stage-3 rollout to determine whether to roll back stage 3 to stage 2 to avoid bothering Asim before business hours.

Path to eventual solution includes whether roles should be colon-delimited or a translation is needed.

**Comment by AsturaPhoenix** [comment]
It doesn't seem straightforward to determine how "stable binaries" are picked up, so there's not really an indication that a rollback will fix the issue quickly. Naively changing the role delimiter to ":" didn't work either.

**Comment by AsturaPhoenix** [comment]
There's no "Prod-incident" label; does https://sites.google.com/a/google.com/v-prod/oncall/incident-response need to be updated?

**Comment by AsturaPhoenix** [comment]
Paged Asim.

**Comment by AsturaPhoenix** [comment]
I also don't have permissions to https://pantheon.corp.google.com/storage/browser/vanadium-release/?pli=1&project=vanadium-internal to look at the release binaries.

Pinging/paging @bjornick as secondary on-call.

**Comment by AsturaPhoenix** [comment]
I am also unable to use vbash (to push reverted binaries):

```
rosswang@rosswang-glaptop0 (dev.v.io:u:rosswang@google.com):~/vanadium $ release/go/bin/vbecome --role=identity/role/vprod/admin
ERROR: vbecome:<rpc.Client>"identity/role/vprod/admin".SeekBlessings: No usable servers found: identity/role/vprod/admin vbecome:<rpc.Client>"identity/role/vprod/admin".ResolveStep: Client does not trust server: [/(dev.v.io:role:vprod)@ns.dev.v.io:8101/identity/role/vprod/admin:identity/role/vprod/admin.ResolveStep: vbecome:<client>tryCreateFlow /(dev.v.io:role:vprod)@ns.dev.v.io:8101/identity/role/vprod/admin: Client does not trust server: failed to authorize flow with remote blessings: dev.v.io/role:vprod:service/mounttabled : vbecome:<client>tryCreateFlow /(dev.v.io:role:vprod)@ns.dev.v.io:8101/identity/role/vprod/admin: blessings in endpoint @6@@ns.dev.v.io:8101@@ac1638eca0cc9bdb0fb2021dad1237b9@m@dev.v.io:role:vprod@@ not matched by blessings presented: [dev.v.io/role:vprod:service/mounttabled] (rejected [])]

rosswang@rosswang-glaptop0 (dev.v.io:u:rosswang@google.com):~/vanadium $ release/go/bin/vbecome --role="/(dev.v.io/role)@ns.dev.v.io:8117/vprod/admin"
ERROR: app:"vprod/admin".SeekBlessings: Access denied: app:"vprod/admin".SeekBlessings: not authorized to call vprod/admin.SeekBlessings: app:"vprod/admin".SeekBlessings: Does not exist or access denied
```

**Comment by AsturaPhoenix** [comment]
Also unable to gsutil root creds even after auth (probably because I don't have access to vanadium-internal); considering paging @jinjingforever, but we're approaching business hours and @asimshankar  and @bjornick haven't responded yet so maybe we don't have a "tier-1" expectation yet.

**Comment by asimshankar** [comment]
I've rolled back a change to get this going:
https://vanadium-review.googlesource.com/#/c/18131/

However, I'm not clear on where the monitoring data collector binaries are generated from. I'm going to poke around for a while, and maybe just copy over the Nov 30th binaries

**Comment by AsturaPhoenix** [comment]
If it helps, here's the script:
http://veyron-jenkins.cbf.corp.google.com/jenkins/job/monitoring-data-collector/configure

I was going to just hope that the release process would get the binaries where they needed to go, but I don't think I have release permissions yet (above vbash failures).

**Comment by asimshankar** [comment]
Ah, it's the vanadium-go-snapshot job (I think - since the times correlate). Triggered a fresh build for that.

**Comment by asimshankar** [comment]
You should be able to use vbash now (after syncing past https://vanadium-review.googlesource.com/#/c/18131/)

**Comment by bjornick** [comment]
how long has it been since the go-snapshot job run?  What is the trigger for it?

**Comment by asimshankar** [comment]
Looking at https://veyron.corp.google.com/jenkins/job/vanadium-go-snapshot/, seems like it just runs once a day.

I manually triggered it and once the downstream job finished (vanadium-go-binaries) the oncall-data-collector etc. jobs seem to have picked up the change and are now green.

**Comment by asimshankar** [comment]
Looks like the monitoring jobs are green and the staging release has deployed successfully. Want to close this out @AsturaPhoenix ?

**Comment by caprita** [comment]
re: Prod-incident github label:
Looks like there is such a label now. Did you add that this morning? If so, thanks :-)

re: oncall response:
We are best-effort during non-business hours. This means no paging of other folks on the team. It's ok if we enter business hours in a broken state, and the expectation is that during business hours everyone chips in to help as needed/determined by the oncall owner

re: binaries generated by vanadium-go-binaries:
I wasn't aware of this particular use case for these binaries; the canonical use is for the regression suite, and perhaps we should just build fresh binaries with each run of oncall-data-collector/exporter rather than relying on the snapshotted binaries.

**Comment by AsturaPhoenix** [comment]
Sure

@caprita:
Prod-incident github label:
Hm? I didn't add it, and I still can't see it (and this is on a different computer than this morning, so I don't think it's a caching issue)

oncall response:
Gotcha. Thanks! We might like to add that to the playbook--the wording at https://sites.google.com/a/google.com/v-prod/oncall/incident-response might lead newbies like me to page everybody.

**Comment by AsturaPhoenix** [comment]
Wording updated; outage created: [http://o/270011](http://o/270011)

**Comment by caprita** [comment]
Thanks. Re: github issues, the label was there in the veyron project but is
indeed missing from the vanadium project (a bit of history -- we used to
have all issues in the veyron project, then we moved the public issues to
the vanadium project and kept internal issues in veyron). We want to
completely move away from the veyron project altogether, with internal
issues going to buganizer instead. I'm looking into updating the incident
response instructions to point to buganizer instead.

**Comment by jinjingforever** [comment]
@caprita The reason to copy binaries from snapshots is mainly because it is much faster. All these monitoring related jobs run every minute, and the updating/building process might take 30-40 seconds in some cases which will make them overrun.

**Comment by rthellend** [comment]
https://vanadium-review.googlesource.com/18142 addresses the issue with roled.
