### ISSUE TITLE
Replace no-arg GetDeltas with Ping

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#970]
Here https://cs.corp.google.com/#vanadium/release/go/src/v.io/x/ref/services/syncbase/vsync/initiator.go&l=154

GetDeltas is called with no arguments.  This call always results in an error because the server is expecting two arguments.  This RPC is only used to get the identity of the remote end, so this isn't a huge problem, but it does write an error message to the logs which can lead people who are debugging to investigate a red herring.

Now that you are adding a Ping RPC, maybe you could call that instead.

**Comment by asadovsky** [comment]
Thanks for filing this and for the suggestion, Matt! I'll go ahead and make this change soon.

**Comment by hpucha** [comment]
Would be preferable to just fix the arguments in the GetDeltas call and not change the RPC. I'll do that in my current pending CL.

**Comment by asadovsky** [comment]
OK, sounds good, thanks Bindu! (I would've had you review my CL otherwise, in any case.)
Switching assignee to Bindu.

**Comment by hpucha** [comment]
This has been fixed in https://vanadium-review.googlesource.com/#/c/18273
