### ISSUE TITLE
Ping test flaky

### ISSUE THREAD

**Issue by suharshs** [vanadium/issues#971]
I sometimes get presubmit flakes on the ping test
https://dashboard.staging.v.io/?arch=amd64&class=v.io%2Fx%2Fref%2Fservices%2Fsyncbase%2Fping&job=vanadium-go-test&n=16613&os=darwin&part=0&suite=v.io%2Fx%2Fref%2Fservices%2Fsyncbase%2Fping&test=TestPingInParallel+%5BGoTest+-+darwin%2Camd64%5D&type=presubmit

**Comment by asadovsky** [comment]
Make local RPC reliably fast and this will go away. :)
Just kidding, I'll do something to deflake this.
Is there any way to inject a fake RPC system for testing purposes?
If not, I'll change my code to allow injecting a fake RPC client that dispatches to a provided implementation.

**Comment by suharshs** [comment]
:)
There is a fake runtime factory:
https://cs.corp.google.com/#vanadium/release/go/src/v.io/x/ref/runtime/factories/fake/rpc.go

So you can inject a client, server, etc.
Here is an example of a test that uses this.
https://cs.corp.google.com/#vanadium/release/go/src/v.io/x/ref/services/wspr/internal/lib/signature_manager_test.go&q=signature_manager_test.go%20package:%5Evanadium$&l=1

I am not actually sure this will be very helpful for writing your test simply.

If I understand your test correctly, would mocking the clock of the ping package be simpler?

**Comment by asadovsky** [comment]
+cc @mattr-google

Yeah, that's another option, but it'd mean I'm still setting up servers to handle the RPCs in my tests. If I'm going to fake the timings somehow, I was hoping to avoid running servers altogether.

That said, this client injection mechanism looks too hard to use for my needs. I have to implement the rpc.Client (and ClientCall, etc.) interface? I'm pretty sure it would take me hours or days to get that right, and result in lots of boilerplate code.

Are there any plans to make this simpler? What I want is a way to inject method implementations for my client methods, and have everything else get defaulted to something reasonable.

In any case, for now I'll go with your suggestion of injecting a clock.

**Comment by asadovsky** [comment]
Actually, scratch that. Injecting a clock is also difficult here, because part of what I'm testing is the behavior of context cancellation. I really do want to inject an RPC client implementation.

Looks like I might have to try using this not-so-easy-to-use client injection framework. Maybe there's something I'm missing that will make my life easier for this case of just wanting to inject a single RPC method implementation and nothing else?

**Comment by ghost** [comment]
First, it is not possible to make the RPC system reliably fast on Jenkins.  I have seen cases where goroutines don't get any runtime in a 250ms window.  In the face of that, there is just nothing we can do so we definitely have to make tests resilient to time.

I don't see why a mock client should be difficult to write.  There are only a few methods and you know which will be called.  But I don't think that will work reliably either.  I think you'll have to use a fake clock.

Let's chat in person.
MattR

**Comment by asadovsky** [comment]
Submitted v.io/c/18318
