### ISSUE TITLE
Proxy silently loses servers

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#976]
The issue is that we see one syncbase that is unable to communicate with the other.  Both syncbases are running through the prod proxy.  One will be able to communicate, the other will get an error trying to establish a flow:

I1202 13:28:27.060981  121680 flow.go:465] closing 10(0xc8203e8b00): syncbased:<client>tryCreateFlow /@6@wsh@172.17.166.57:8000@@f9b830cb\
88cce5e0b344341aedaa36c2@s@dev.v.io:u:youngseokyoon@google.com@@/%%sync/cloudsync: flow closed remotely.

The proxy says:

E1202 13:28:26.654562    5697 proxy.go:233] failed to handle incoming connection: app: : app: bidi routing id not in cache.

As of yet we're not sure why the connection is being lost.  The server doesn't seem to know that the connection is closed.

Both @yyoon and @AsturaPhoenix have seen this bug.  @suharshs and I have been debugging it.

**Comment by suharshs** [comment]
https://vanadium-review.googlesource.com/#/c/18286/
