### ISSUE TITLE
Syncbase table destroy doesn't delete rows

### ISSUE THREAD

**Issue by asadovsky** [vanadium/issues#977]
There might be other problems with it, too. They'll be apparent when you look at the code.

App destroy has similar problems, so it would be good to fix that too. I bet the fix will look very similar.

**Comment by ivanpi-mtv** [comment]
Table's row deletion fixed by https://vanadium-review.googlesource.com/#/c/18333/
Working on app's database deletion.

**Comment by ivanpi-mtv** [comment]
App's database deletion fixed by https://vanadium-review.googlesource.com/#/c/18491/
