### ISSUE TITLE
v.io/x/ref/services/debug/debuglib is flaky

### ISSUE THREAD

**Issue by bjornick** [vanadium/issues#981]
See: https://veyron.corp.google.com/jenkins/job/release-candidate-2-test/ARCH=amd64,OS=linux,TEST=vanadium-go-race-part2/481/console

@rthellend

**Comment by bjornick** [comment]
Adding bogdan since he's looking at it now

**Comment by caprita** [comment]
I stared at this (and the test) for a while and am not really sure what failed. The output says 'fail' but then doesn't show any errors (the vtrace output is expected and part of successful runs), and in the end it prints 'ok':

04:58:50 fail v.io/x/ref/services/debug/debuglib
04:58:50 === RUN   TestDebugServer
04:58:50 Vtrace traces:
04:58:50 Trace - 0xe7a2be3bbb03c8eb2c581106168d8008 (2015-12-04 04:58:49.145610 PST, ??)
04:58:50     Span - Missing Data [id: 00000000 parent 00000000](??, ??)
04:58:50         Span - <rpc.Client>"/@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/logs/test.INFO".Size [id: 168d800a parent 168d8009](0, 9.481175ms)
04:58:50             Span - <client>tryCreateFlow /@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/logs/test.INFO [id: 168d800b parent 168d800a](323.552µs, 545.364µs)
04:58:50             Span - "debug/logs/test.INFO".Size [id: 168d800c parent 168d800a](2.334297ms, 6.6114ms)
04:58:50 Trace - 0xe7a2be3bbb03c8eb2c581106168d800d (2015-12-04 04:58:49.155192 PST, ??)
04:58:50     Span - Missing Data [id: 00000000 parent 00000000](??, ??)
04:58:50         Span - <rpc.Client>"/@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/logs/nosuchfile.INFO".Size [id: 168d800f parent 168d800e](0, 7.900279ms)
04:58:50             Span - <client>tryCreateFlow /@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/logs/nosuchfile.INFO [id: 168d8010 parent 168d800f](329.963µs, 564.321µs)
04:58:50             Span - "debug/logs/nosuchfile.INFO".Size [id: 168d8011 parent 168d800f](3.069586ms, 3.299861ms)
04:58:50 Trace - 0xe7a2be3bbb03c8eb2c581106168d8012 (2015-12-04 04:58:49.163250 PST, ??)
04:58:50     Span - Missing Data [id: 00000000 parent 00000000](??, ??)
04:58:50         Span - <rpc.Client>"/@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/stats/testing/foo".Value [id: 168d8014 parent 168d8013](0, 7.441619ms)
04:58:50             Span - <client>tryCreateFlow /@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/stats/testing/foo [id: 168d8015 parent 168d8014](448.501µs, 670.904µs)
04:58:50             Span - "debug/stats/testing/foo".Value [id: 168d8016 parent 168d8014](3.323861ms, 4.433627ms)
04:58:50 Trace - 0xe7a2be3bbb03c8eb2c581106168d8017 (2015-12-04 04:58:49.170782 PST, ??)
04:58:50     Span - Missing Data [id: 00000000 parent 00000000](??, ??)
04:58:50         Span - <rpc.Client>"/@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/stats/testing/nobodyhome".Value [id: 168d8019 parent 168d8018](0, 7.365383ms)
04:58:50             Span - <client>tryCreateFlow /@6@tcp@127.0.0.1:35542@@309b158bcdb27c5e0189426180f217a7@s@test-blessing@@/debug/stats/testing/nobodyhome [id: 168d801a parent 168d8019](369.301µs, 595.68µs)
04:58:50             Span - "debug/stats/testing/nobodyhome".Value [id: 168d801b parent 168d8019](2.887206ms, 3.179257ms)
04:58:50 ok     v.io/x/ref/services/debug/debuglib  1.714s

One thing that's conspicuously missing is the snippet at the end:

--- PASS: TestDebugServer (0.24s)
    dispatcher_test.go:185: got &{{stats/testing/foo [] false false}}
PASS

(or the equivalent for FAIL). I don't know enough about go's test framework to understand why that's missing or whether it can cause the test to appear as having failed (or perhaps it did fail, but the error got swallowed). I'm tempted to wait for another failure with perhaps more output.

**Comment by jinjingforever** [comment]
See #989 for possible cause.
