### ISSUE TITLE
PingInParallel test is faling

### ISSUE THREAD

**Issue by bjornick** [vanadium/issues#984]
I can't find the corresponding change because jenkins didn't show the list of changes for the first failing instance.  It's been reliably failing since 9pm yesterday

https://veyron.corp.google.com/jenkins/job/vanadium-go-test/1287/ARCH=amd64,OS=linux/console

**Comment by asadovsky** [comment]
Thanks - I'm aware of this and will get a fix in shortly.
(It turns out that, loosely speaking, timing-based tests just don't work on Jenkins.)

**Comment by asadovsky** [comment]
Submitted v.io/c/18318
