### ISSUE TITLE
Memory leak in RPC

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#991]
@rthellend reports:

rpsbot was crashing the pis. It looks like there's a memory leak somewhere. I'm running 3 instances on kubernetes now.

conn.NewDialed and conn.NewAccepted are growing pretty fast (~1MB per minute).

Here's a sample heap profile.

$ debug pprof run vlab/rps/player/root@rpsbot-sjx9d/__debug/pprof heap -text --nodecount=10
Running: jiri go tool pprof '-text' '--nodecount=10' 'http://127.0.0.1:49207/pprof/heap'
Fetching profile from http://127.0.0.1:49207/pprof/heap
Saved profile in /home/rthellend/pprof/pprof.127.0.0.1:49207.inuse_objects.inuse_space.001.pb.gz
48.18MB of 57.86MB total (83.26%)
Dropped 343 nodes (cum <= 0.29MB)
Showing top 10 nodes out of 127 (cum >= 1MB)
      flat  flat%   sum%        cum   cum%
   20.74MB 35.85% 35.85%    20.74MB 35.85%  v.io/x/ref/runtime/internal/flow/conn.NewDialed
   15.86MB 27.41% 63.27%    16.86MB 29.14%  v.io/x/ref/runtime/internal/flow/conn.NewAccepted
       3MB  5.19% 68.45%        3MB  5.19%  v.io/x/ref/runtime/internal/lib/framer.(_framer).ReadMsg
    1.53MB  2.65% 71.10%     1.53MB  2.65%  v.io/x/ref/runtime/internal/rpc/stream/crypto.(_cbox).Seal
    1.50MB  2.59% 73.70%     1.50MB  2.59%  v.io/v23/vom.NewDecoder
    1.50MB  2.59% 76.29%     1.50MB  2.59%  v.io/v23/context.WithValue
    1.03MB  1.78% 78.07%     1.03MB  1.78%  regexp.(_bitState).reset
       1MB  1.73% 79.80%        1MB  1.73%  v.io/x/ref/runtime/internal/rpc/stream/crypto.(_cbox).Open
       1MB  1.73% 81.53%        1MB  1.73%  v.io/v23/vom.NewTypeDecoder
       1MB  1.73% 83.26%        1MB  1.73%  v.io/v23/vom.newSwitchedEncbuf

$ debug pprof run vlab/rps/player/root@rpsbot-sjx9d/__debug/pprof heap -gif | sed -n '2,$p' > rpsbot-heap.gif

Twenty minutes later...
   56.32MB 38.91% 38.91%    56.32MB 38.91%  v.io/x/ref/runtime/internal/flow/conn.NewDialed
   36.57MB 25.27% 64.19%    37.57MB 25.96%  v.io/x/ref/runtime/internal/flow/conn.NewAccepted

@suharshs

**Comment by rthellend** [comment]
More information from pprof...

heap profile: 341: 14448128 [5438: 36892432] @ heap/1048576
118: 7733248 [150: 9830400] @ 0x44e4b5 0x94c0d3 0x83ad0a 0x8395f6 0x85ef17 0x46b121
    0x94c0d3    v.io/x/ref/runtime/internal/flow/conn.NewDialed+0xc3            /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:161
    0x83ad0a    v.io/x/ref/runtime/internal/flow/manager.(_manager).internalDial+0x16ca /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/flow/manager/manager.go:755
    0x8395f6    v.io/x/ref/runtime/internal/flow/manager.(_manager).Dial+0x96       /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/flow/manager/manager.go:647
    0x85ef17    v.io/x/ref/runtime/internal/rpc.(*xclient).tryCreateFlow+0x6f7      /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/rpc/xclient.go:208

78: 5111808 [88: 5767168] @ 0x44e4b5 0x94d04d 0x83d53e 0x46b121
    0x94d04d    v.io/x/ref/runtime/internal/flow/conn.NewAccepted+0x1ad                 /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/flow/conn/conn.go:241
    0x83d53e    v.io/x/ref/runtime/internal/flow/manager.(*proxyFlowHandler).HandleFlow.func1+0x2fe /usr/local/google/home/rthellend/vanadium/release/go/src/v.io/x/ref/runtime/internal/flow/manager/manager.go:577

**Comment by ghost** [comment]
The problem is that you cache connections with their blessing names and then apply blessing name authorization.  You get these blessing names from the endpoint, but client connections are dialed with endpoint-free blessings (to preserve privacy during setup).  So if we have peers A and B then:

B -> A:ablessing, A caches B:_ and B caches A:ablessing
A -> B:bblessing, The cached B:_ is ignored because it doesn't match bblessing so we replace it with a newly dialed B:bblessing, and on the other side we eject A:ablessing and replace it with A:_
B -> A, which does the opposite ignore, eject.

We end up dialing a new connection for every RPC.

One way to fix particular case would be to always cache a connection with its validated peer names instead of the blessings claimed in the incoming endpoint, however this ignores the larger problem that the conncache doesn't know about the real auth policy the flow is going to perform, instead it's always doing endpoint auth checking, which might be totally wrong which would result in the same ping-ponging behavior.

I think what actually has to happen is that we need to pipe the peer authorizer into the cache lookup and actually evaluate it there.

I'm working on a change to this effect.

Another issue is that even though all these conns won't be used again (since their not in the cache at either end, they're in the unmappedConnections set on both sides) we never close them unless we hit a file descriptor limit.  We should do two things:
1. Servers should lame-duck connections that they remove from their cache, they will eventually be closed after the client acknowledges this status, and anyway the client should be using the bidi capable connection.
2.  Add some kind of knob to set the maximum memory we use for the conncache.

I will file separate bugs for these issues.

**Comment by ghost** [comment]
This is fixed by https://vanadium-review.googlesource.com/#/c/18800/
